const {test,expect}=require('playwright/test');
const {APP}=require('./helpers/app-target');
const task=(id,extra={})=>({id,parentId:'',state:'未着手',impact_level:2,title:id,owner:'Alice',due:'2026-09-10',planned_duration_days:1,summary:'',repeat:'',completed:false,source:'',asana_task_id:'',history:[],dependencies:[],sortOrder:1000,...extra});
async function boot(page){await page.setViewportSize({width:1440,height:800});await page.goto(APP);await page.evaluate(()=>localStorage.clear());await page.reload();await page.evaluate(xs=>{applyJsonObject({schema_version:'2.5',items:xs},'pbl029','pbl029.json',null,{remember:false,writePermissionGranted:false});selectTask('A')},[task('A'),task('B',{owner:'Bob',sortOrder:2000})])}
async function key(page,key){if(/^[\x20-\x7e]$/.test(key))return page.keyboard.press(key);return page.evaluate(k=>document.activeElement.dispatchEvent(new KeyboardEvent('keydown',{key:k,bubbles:true,cancelable:true})),key)}

test('PBL029-UI-01 Priority precedes Owner on one desktop row with compact local sizing',async({page})=>{await boot(page);const geometry=await page.evaluate(()=>{const priorityEl=document.getElementById('priorityFilterSelect'),ownerEl=document.getElementById('ownerFilterButton'),priority=priorityEl.getBoundingClientRect(),owner=ownerEl.getBoundingClientRect(),style=getComputedStyle(priorityEl);return{order:priorityEl.compareDocumentPosition(ownerEl)&Node.DOCUMENT_POSITION_FOLLOWING,sameRow:Math.abs(priority.y-owner.y)<3,width:priority.width,height:priority.height,ownerHeight:owner.height,font:parseFloat(style.fontSize),text:priorityEl.options[0].text}});expect(geometry.order).toBeTruthy();expect(geometry.sameRow).toBe(true);expect(geometry.text).toBe('優先度: すべて');expect(geometry.width).toBeGreaterThan(85);expect(geometry.width).toBeLessThan(130);expect(Math.abs(geometry.height-geometry.ownerHeight)).toBeLessThanOrEqual(4);expect(geometry.font).toBeLessThanOrEqual(11)});

test('PBL029-UI-02 compact layout preserves Owner OR and Priority threshold behavior',async({page})=>{await boot(page);await page.evaluate(()=>{ownerFilterValues=new Set(['Alice','Bob']);setPriorityFilter(2)});expect(await page.evaluate(()=>visible().map(row=>row.x.id))).toEqual(['A','B']);await page.evaluate(()=>setPriorityFilter(3));expect(await page.evaluate(()=>visible().map(row=>row.x.id))).toEqual([]);await page.evaluate(()=>clearOwnerFilter());expect(await page.evaluate(()=>ownerFilterValues.size)).toBe(0)});

test('PBL029-S-01 S/s/full-width variants open Search through the same UI',async({page})=>{for(const value of ['S','s','Ｓ','ｓ']){await boot(page);await key(page,value);await expect(page.locator('#taskSearchInput')).toBeFocused();await expect(page.locator('#taskSearchPopup')).toBeVisible()}});

test('PBL029-S-02 bare S opens Search while Alt+S remains a compatible toggle alias',async({page})=>{await boot(page);await page.keyboard.press('s');await expect(page.locator('#taskSearchPopup')).toBeVisible();await page.keyboard.press('Escape');await expect(page.locator('#taskSearchPopup')).toBeHidden();await page.keyboard.press('Alt+s');await expect(page.locator('#taskSearchInput')).toBeFocused();await page.keyboard.press('Alt+s');await expect(page.locator('#taskSearchPopup')).toBeHidden()});

test('PBL029-S-03 input, textarea, contenteditable, inline editor and IME retain S ownership',async({page})=>{await boot(page);for(const selector of ['#b_title','#workspaceInfoEditor','#row_A .titleText']){const target=page.locator(selector);if(selector==='#workspaceInfoEditor'){await page.locator('#workspaceInfoPanel .workspaceInfoDisplay').click()}await target.focus();await key(page,'s');await expect(page.locator('#taskSearchPopup')).toBeHidden()}await page.locator('#b_title').focus();await page.locator('#b_title').dispatchEvent('compositionstart',{data:'ｓ'});await page.locator('#b_title').dispatchEvent('keydown',{key:'ｓ',isComposing:true,keyCode:229});await expect(page.locator('#taskSearchPopup')).toBeHidden();await page.locator('#b_title').dispatchEvent('compositionend',{data:'ｓ'})});

test('PBL029-GUIDE-01 guide documents current shortcuts and removes obsolete Alt+M/Alt+I',async({page})=>{await boot(page);const guide=page.locator('#shortcutHelp');await expect(guide).toContainText('S＝検索');await expect(guide).toContainText('T＝ToDo ツリー順');await expect(guide).toContainText('P＝Project 詳細');await expect(guide).toContainText('1/2');await expect(guide).toContainText('E＝期限編集');await expect(guide).toContainText('F2＝タイトル編集');await expect(guide).toContainText('Alt+T＝TOP');await expect(guide).not.toContainText('Alt+M');await expect(guide).not.toContainText('Alt+I')});

test('PBL029-PROTECT-01 T/P/1/2 and D→E remain unchanged beside S',async({page})=>{await boot(page);await page.keyboard.press('p');expect(await page.evaluate(()=>displayModeKey())).toBe('project-detail');await page.keyboard.press('2');expect(await page.evaluate(()=>displayModeKey())).toBe('project-simple');await page.keyboard.press('t');expect(await page.evaluate(()=>displayModeKey())).toBe('todo-tree');await page.keyboard.press('2');expect(await page.evaluate(()=>displayModeKey())).toBe('todo-date');await page.keyboard.press('d');await page.keyboard.press('e');await expect(page.locator('#row_A #d0')).toBeFocused()});

test('PBL029-PROTECT-02 D→digit, F2, Enter and Insert remain unchanged',async({page})=>{await boot(page);await page.keyboard.press('d');await page.keyboard.press('1');await expect(page.locator('#row_A #d0')).toBeFocused();await page.keyboard.press('Escape');await page.keyboard.press('F2');await expect(page.locator('#row_A .titleText')).toBeFocused();await page.keyboard.press('Escape');await page.evaluate(()=>selectTask('A'));await page.keyboard.press('Enter');expect(await page.evaluate(()=>draftKind)).toBe('same');await page.locator(`#row_${await page.evaluate(()=>draftTaskId)} .titleText`).press('Escape');await page.evaluate(()=>selectTask('A'));await page.keyboard.press('Insert');expect(await page.evaluate(()=>draftKind)).toBe('child')});
