const {test,expect}=require('playwright/test');
const {APP}=require('./helpers/app-target');
const task=(id,extra={})=>({id,parentId:'',state:'未着手',impact_level:0,title:id,owner:'',due:'',summary:'',repeat:'',completed:false,source:'',asana_task_id:'',history:[],dependencies:[],sortOrder:1000,...extra});
async function fresh(page,items){await page.goto(APP);await page.evaluate(()=>localStorage.clear());await page.reload();await page.evaluate(xs=>applyJsonObject({schema_version:'2.5',workspace_info_markdown:'',items:xs},'pbl020','pbl020.json',null,{remember:false,writePermissionGranted:false}),items)}
async function ids(page){return page.evaluate(()=>visible().map(row=>row.x.id))}
async function setOwners(page,values){await page.evaluate(values=>{ownerFilterValues=new Set(values);localStorage.setItem(PBL020_OWNER_KEY,JSON.stringify(values));render()},values)}

test('PBL020-01 Owner single/multiple/unset/mixed/none use OR and zero means no filter',async({page})=>{await fresh(page,[task('alice',{owner:'Alice'}),task('bob',{owner:'Bob'}),task('unset'),task('space',{owner:'　 '})]);await setOwners(page,['Alice']);expect(await ids(page)).toEqual(['alice']);await setOwners(page,['Alice','Bob']);expect(await ids(page)).toEqual(['alice','bob']);await setOwners(page,['__UNSET__']);expect(new Set(await ids(page))).toEqual(new Set(['unset','space']));await setOwners(page,['Alice','__UNSET__']);expect(new Set(await ids(page))).toEqual(new Set(['alice','unset','space']));await setOwners(page,[]);expect(new Set(await ids(page))).toEqual(new Set(['alice','bob','unset','space']))});

test('PBL020-02 Priority thresholds use impact_level 0..3 only',async({page})=>{await fresh(page,[0,1,2,3].map(level=>task('p'+level,{impact_level:level})));for(const [level,expected] of [[0,['p0','p1','p2','p3']],[1,['p1','p2','p3']],[2,['p2','p3']],[3,['p3']]]){await page.evaluate(v=>setPriorityFilter(v),level);expect(await ids(page)).toEqual(expected)}});

test('PBL020-03 Owner OR, Priority and management end-state combine with AND',async({page})=>{await fresh(page,[task('a2-open',{owner:'Alice',impact_level:2}),task('b3-open',{owner:'Bob',impact_level:3}),task('a1-open',{owner:'Alice',impact_level:1}),task('a3-closed',{owner:'Alice',impact_level:3,completed:true}),task('c3-open',{owner:'Carol',impact_level:3})]);await setOwners(page,['Alice','Bob']);await page.evaluate(()=>setPriorityFilter(2));await page.locator('#vOpen').click();expect(await ids(page)).toEqual(['a2-open','b3-open']);await page.locator('#vDone').click();expect(await ids(page)).toEqual(['a3-closed']);await page.locator('#vAll').click();expect(new Set(await ids(page))).toEqual(new Set(['a2-open','b3-open','a3-closed']))});

test('PBL020-04 ToDo tree adds only required ancestors and never pulls nonmatching descendants',async({page})=>{await fresh(page,[task('root',{owner:'Alice'}),task('parent',{parentId:'root',owner:'Bob'}),task('match',{parentId:'parent',owner:'Carol'}),task('other',{parentId:'root',owner:'Bob'}),task('root2',{owner:'Carol'}),task('child2',{parentId:'root2',owner:'Bob'})]);await setOwners(page,['Carol']);const rows=await page.evaluate(()=>visible().map(row=>({id:row.x.id,context:row.context,depth:row.depth})));expect(rows).toEqual([{id:'root',context:true,depth:0},{id:'parent',context:true,depth:1},{id:'match',context:false,depth:2},{id:'root2',context:false,depth:0}]);expect(rows.map(x=>x.id)).not.toContain('other');expect(rows.map(x=>x.id)).not.toContain('child2')});

test('PBL020-05 shared ancestors are de-duplicated and hierarchy order is stable',async({page})=>{await fresh(page,[task('root'),task('a',{parentId:'root',owner:'Alice',sortOrder:1000}),task('b',{parentId:'root',owner:'Alice',sortOrder:2000})]);await setOwners(page,['Alice']);expect(await ids(page)).toEqual(['root','a','b'])});

test('PBL020-06 ToDo date filtering preserves due order, ties and undated-last behavior',async({page})=>{await fresh(page,[task('late',{owner:'Alice',due:'2026-08-20'}),task('early',{owner:'Alice',due:'2026-08-01'}),task('tie2',{owner:'Alice',due:'2026-08-10',sortOrder:2000}),task('tie1',{owner:'Alice',due:'2026-08-10',sortOrder:1000}),task('none',{owner:'Alice'}),task('excluded',{owner:'Bob',due:'2026-07-01'})]);await setOwners(page,['Alice']);await page.locator('#dmTodoDate').click();expect(await ids(page)).toEqual(['early','tie1','tie2','late','none'])});

test('PBL020-07 Project detail/simple return identical rows; only Summary differs and Priority stays',async({page})=>{await fresh(page,[task('a',{owner:'Alice',impact_level:2,summary:'summary'}),task('b',{owner:'Bob',impact_level:3,summary:'other'})]);await setOwners(page,['Alice']);await page.locator('#dmProjectDetail').click();const detail=await ids(page);await expect(page.locator('.ganttRow[data-task-id="a"] .sum')).toBeVisible();await expect(page.locator('.ganttRow[data-task-id="a"] .impactStars')).toBeVisible();await page.locator('#dmProjectSimple').click();expect(await ids(page)).toEqual(detail);await expect(page.locator('.ganttRow[data-task-id="a"] .sum')).toHaveCount(0);await expect(page.locator('.ganttRow[data-task-id="a"] .impactStars')).toBeVisible()});

test('PBL020-08 all filter states survive four modes and reload through UI-state LocalStorage',async({page})=>{await fresh(page,[task('a',{owner:'Alice',impact_level:2})]);await setOwners(page,['Alice']);await page.evaluate(()=>setPriorityFilter(2));await page.locator('#vAll').click();for(const id of ['dmTodoTree','dmTodoDate','dmProjectDetail','dmProjectSimple']){await page.locator('#'+id).click();expect(await page.evaluate(()=>({owners:[...ownerFilterValues],priority:priorityFilterThreshold,view}))).toEqual({owners:['Alice'],priority:2,view:'all'})}await page.reload();expect(await page.evaluate(()=>({owners:[...ownerFilterValues],priority:priorityFilterThreshold}))).toEqual({owners:['Alice'],priority:2})});

test('PBL020-09 filter changes are UI-only: JSON, dirty and Undo remain unchanged',async({page})=>{await fresh(page,[task('a',{owner:'Alice',impact_level:2})]);const before=await page.evaluate(()=>({json:JSON.stringify(persistableData()),dirty,undo:undoStack.length,revision:dataRevision}));await setOwners(page,['Alice']);await page.evaluate(()=>setPriorityFilter(2));await page.locator('#vAll').click();expect(await page.evaluate(()=>({json:JSON.stringify(persistableData()),dirty,undo:undoStack.length,revision:dataRevision}))).toEqual(before)});

test('PBL020-10 Owner candidates refresh after edit/add/DB switch while stale selection stays safe',async({page})=>{await fresh(page,[task('a',{owner:'Alice'})]);await setOwners(page,['Alice']);await page.evaluate(()=>{itemById('a').owner='Bob';render()});expect(await page.evaluate(()=>ownerFilterCandidates())).toEqual(['Alice','Bob']);expect(await ids(page)).toEqual([]);await page.evaluate(()=>applyJsonObject({schema_version:'2.5',items:[{...data.items[0],id:'c',owner:'Carol'}]},'next','next.json',null,{remember:false,writePermissionGranted:false}));expect(await page.evaluate(()=>ownerFilterCandidates())).toEqual(['Alice','Carol']);expect(await ids(page)).toEqual([])});

test('PBL020-11 hiding selection with Task Detail open remains coherent and wrong task is not targeted',async({page})=>{await fresh(page,[task('a',{owner:'Alice'}),task('b',{owner:'Bob'})]);await page.evaluate(()=>{selectTask('a');openTaskDetailPane('a')});await setOwners(page,['Bob']);expect(await ids(page)).toEqual(['b']);expect(await page.evaluate(()=>({selectedTaskId,taskDetailPaneTaskId,open:taskDetailPaneOpen}))).toEqual({selectedTaskId:'a',taskDetailPaneTaskId:'a',open:true});expect(await page.evaluate(()=>itemById(taskDetailPaneTaskId).id)).toBe('a')});

test('PBL020-12 filters coexist with mode shortcuts, PBL028 D→E, D→digit, F2 and input guards',async({page})=>{await fresh(page,[task('a',{owner:'Alice',due:'2026-08-20'})]);await setOwners(page,['Alice']);await page.evaluate(()=>selectTask('a'));await page.keyboard.press('p');expect(await page.evaluate(()=>displayModeKey())).toBe('project-detail');await page.keyboard.press('2');expect(await page.evaluate(()=>displayModeKey())).toBe('project-simple');await page.keyboard.press('t');expect(await page.evaluate(()=>displayModeKey())).toBe('todo-tree');await page.keyboard.press('d');await page.keyboard.press('e');await expect(page.locator('#row_a #d0')).toBeFocused();await page.keyboard.press('Escape');await page.keyboard.press('F2');await expect(page.locator('#row_a .titleText')).toBeFocused();await page.keyboard.type('tp12');expect(await page.evaluate(()=>displayModeKey())).toBe('todo-tree')});
