const {test,expect}=require('playwright/test');
const {installFsAccessMock}=require('./helpers/fs-access-mock');
const {APP}=require('./helpers/app-target');

test.setTimeout(30_000);
const task=(id='T',extra={})=>({id,parentId:'',state:'',impact_level:0,title:id,owner:'',due:'',summary:'',repeat:'',completed:false,source:'',asana_task_id:'',history:[],dependencies:[],sortOrder:1000,...extra});
const snap=(id,at=id)=>({snapshot_id:id,captured_at:at,product_version:'3.2.0',schema_version:'3.2',snapshot_format_version:'1.0',items:[task('H-'+id)]});
const root=(snapshots=[],items=[task('LIVE')],schema='3.2')=>({schema_version:schema,workspace_info_markdown:'workspace',items,snapshots});

async function boot(page){await installFsAccessMock(page);await page.goto(APP);await page.evaluate(()=>localStorage.clear());await page.reload();await expect(page).toHaveTitle('ASANYA v3.2.0')}
async function adopt(page,id,value,options={}){const text=JSON.stringify(value);await page.evaluate(async({id,text,options})=>{const handle=__fsMock.create(id,{name:options.name||id+'.json',text,writePermission:'granted',...options}),file=await handle.getFile();await applyJsonObject(JSON.parse(text),'phase2',file.name,handle,{remember:false,writePermissionGranted:true,fileText:text,fileModified:file.lastModified,fileSize:file.size})},{id,text,options});return text}
async function create(page){await page.evaluate(()=>{window.__snapshotResult=createManualSnapshot()});return page.evaluate(()=>window.__snapshotResult)}
test.beforeEach(async({page})=>boot(page));

test('PBL042-P2-01: button is beside location action and clean direct creation persists canonical metadata/payload only',async({page})=>{
  await adopt(page,'primary',root([], [task('LIVE',{planned_duration_days:0,actual_start:'2026-09-01',actual_start_source:'user',runtimeLeak:'no'})]));
  expect(await page.locator('#dbStatus .dbMain button').allTextContents()).toEqual(expect.arrayContaining(['保存場所を確認','スナップショット作成']));
  const buttons=await page.locator('#dbStatus .dbMain button').allTextContents();expect(buttons.indexOf('スナップショット作成')).toBe(buttons.indexOf('保存場所を確認')+1);
  const undoBefore=await page.evaluate(()=>({undo:undoStack.length,redo:redoStack.length}));expect(await create(page)).toBe(true);
  const result=await page.evaluate(()=>({saved:JSON.parse(__fsMock.snapshot('primary').text),runtime:data.snapshots,dirty,auto:!!autoSaveTimer,undo:undoStack.length,redo:redoStack.length,toast:toast.textContent}));
  expect(result.saved.snapshots).toHaveLength(1);const s=result.saved.snapshots[0];expect(s).toMatchObject({product_version:'3.2.0',schema_version:'3.2',snapshot_format_version:'1.0'});expect(s.snapshot_id).toMatch(/^snapshot-/);expect(new Date(s.captured_at).toISOString()).toBe(s.captured_at);expect(s.items[0]).not.toHaveProperty('runtimeLeak');expect(result.runtime).toEqual(result.saved.snapshots);expect({undo:result.undo,redo:result.redo}).toEqual(undoBefore);expect(result.dirty).toBe(false);expect(result.auto).toBe(false);expect(result.toast).toContain('スナップショットを作成しました');
});

test('PBL042-P2-02: all safety gates expose a disabled reason and never force editor commit',async({page})=>{
  await page.evaluate(value=>applyJsonObject(value,'fallback','fallback.json',null,{remember:false,writePermissionGranted:false}),root());await expect(page.locator('#snapshotCreateBtn')).toBeDisabled();await expect(page.locator('#snapshotCreateBtn')).toHaveAttribute('title',/直接保存/);
  await adopt(page,'primary',root());const cases=await page.evaluate(()=>{const out={};dirty=true;refreshDbStatus();out.dirty=snapshotCreationBlockReason();dirty=false;autoSaveTimer=1;refreshDbStatus();out.autosave=snapshotCreationBlockReason();autoSaveTimer=null;saveInProgress=true;refreshDbStatus();out.saving=snapshotCreationBlockReason();saveInProgress=false;conflictDetected=true;refreshDbStatus();out.conflict=snapshotCreationBlockReason();conflictDetected=false;draftTaskId='draft';refreshDbStatus();out.draft=snapshotCreationBlockReason();draftTaskId='';return out});expect(cases).toEqual({dirty:expect.stringContaining('未保存'),autosave:expect.stringContaining('未保存'),saving:expect.stringContaining('保存処理'),conflict:expect.stringContaining('外部更新'),draft:expect.stringContaining('新規タスク')});
  await page.evaluate(()=>{render();document.querySelector('.titleText[contenteditable]')?.focus()});await expect(page.locator('#snapshotCreateBtn')).toBeDisabled();expect(await page.evaluate(()=>snapshotCreationBlockReason())).toContain('編集中');
  await page.evaluate(()=>document.activeElement?.blur());await page.evaluate(()=>openSummaryModal('LIVE'));await expect(page.locator('#snapshotCreateBtn')).toBeDisabled();await page.locator('#summaryModalCancel').click();
});

test('PBL042-P2-02B: ordinary, Workspace, Task Detail, Actual, and recurrence editors share the gate',async({page})=>{
  await adopt(page,'primary',root([], [task('LIVE',{repeat:'毎週',recurrence_rule:{type:'weekly',weekdays:[1]},recurrence_schedule_date:'2026-09-14'})]));const before=await page.evaluate(()=>__fsMock.snapshot('primary').text);
  await page.evaluate(()=>setMode('team'));await page.locator('.ganttRow[data-task-id="LIVE"] .ownerInput').focus();await expect(page.locator('#snapshotCreateBtn')).toBeDisabled();await page.locator('.ganttRow[data-task-id="LIVE"] .ownerInput').blur();
  await page.evaluate(()=>workspaceInfoBeginEdit());await expect(page.locator('#snapshotCreateBtn')).toBeDisabled();await page.locator('#workspaceInfoEditor').blur();
  await page.evaluate(()=>openTaskDetailPane('LIVE'));const detailInput=page.locator('#taskDetailPane input').first();await detailInput.focus();await expect(page.locator('#snapshotCreateBtn')).toBeDisabled();await detailInput.blur();
  await page.evaluate(()=>openActualEditor('LIVE'));await expect(page.locator('#snapshotCreateBtn')).toBeDisabled();await page.locator('.actualEditorActions button').first().click();
  await page.evaluate(()=>openRecurrenceEditor(0));await expect(page.locator('#snapshotCreateBtn')).toBeDisabled();await page.evaluate(()=>cancelRecurrenceEditor());
  expect(await page.evaluate(()=>({writes:__fsMock.snapshot('primary').writeCount,text:__fsMock.snapshot('primary').text,snapshots:data.snapshots.length}))).toEqual({writes:0,text:before,snapshots:0});
});

test('PBL042-P2-03: immediate external update aborts without write or runtime adoption',async({page})=>{const original=await adopt(page,'primary',root());await page.evaluate(()=>__fsMock.mutate('primary',JSON.stringify({schema_version:'3.2',items:[{external:true}],snapshots:[]})));expect(await create(page)).toBe(false);expect(await page.evaluate(()=>({count:data.snapshots.length,writes:__fsMock.snapshot('primary').writeCount,conflict:conflictDetected}))).toEqual({count:0,writes:0,conflict:true});expect(original).not.toBe(await page.evaluate(()=>__fsMock.snapshot('primary').text))});

test('PBL042-P2-04: final pre-write freshness check closes the race window',async({page})=>{await adopt(page,'primary',root());await page.evaluate(()=>__fsMock.configure('primary',{mutateAfterGetFileCall:2,mutateText:JSON.stringify({schema_version:'3.2',items:[],snapshots:[]})}));expect(await create(page)).toBe(false);expect(await page.evaluate(()=>({snapshots:data.snapshots.length,writes:__fsMock.snapshot('primary').writeCount,conflict:conflictDetected}))).toEqual({snapshots:0,writes:0,conflict:true})});

for(const failure of ['failCreateWritable','failWrite','failClose'])test(`PBL042-P2-05-${failure}: persistence failure preserves clean runtime and stored history`,async({page})=>{const history=[snap('s1','2026-09-01T00:00:00.000Z')],original=await adopt(page,'primary',root(history));await page.evaluate(failure=>__fsMock.configure('primary',{[failure]:true}),failure);expect(await create(page)).toBe(false);expect(await page.evaluate(()=>({runtime:data.snapshots,stored:__fsMock.snapshot('primary').text,dirty,auto:!!autoSaveTimer}))).toEqual({runtime:history,stored:original,dirty:false,auto:false})});

test('PBL042-P2-06A: Schema 3.1 migration cancel leaves original untouched',async({page})=>{const original=await adopt(page,'primary',root([], [task('L')],'3.1'));await page.evaluate(()=>{window.__snapshotResult=createManualSnapshot()});await expect(page.locator('.impactUpgradeDialog')).toBeVisible();await page.locator('#impactUpgradeCancel').click();expect(await page.evaluate(()=>window.__snapshotResult)).toBe(false);expect(await page.evaluate(()=>__fsMock.snapshot('primary').text)).toBe(original);expect(await page.evaluate(()=>data.snapshots)).toEqual([])});
test('PBL042-P2-06B: Schema 3.1 backup failure leaves original untouched',async({page})=>{const original=await adopt(page,'primary',root([], [task('L')],'3.1'));await page.evaluate(()=>{__fsMock.create('backup',{name:'backup.json',failWrite:true});__fsMock.queueSave('backup');window.__snapshotResult=createManualSnapshot()});await expect(page.locator('.impactUpgradeDialog')).toBeVisible();await page.locator('#impactUpgradeAccept').click();expect(await page.evaluate(()=>window.__snapshotResult)).toBe(false);expect(await page.evaluate(()=>__fsMock.snapshot('primary').text)).toBe(original);expect(await page.evaluate(()=>data.snapshots)).toEqual([])});

test('PBL042-P2-07: Schema 3.1 creation writes exact backup first, then one Schema 3.2 snapshot transaction',async({page})=>{const original=await adopt(page,'primary',root([], [task('L')],'3.1'),{name:'legacy.json'});await page.evaluate(()=>{__fsMock.create('backup',{name:'legacy_schema3.1.json'});__fsMock.queueSave('backup');window.__snapshotResult=createManualSnapshot()});await page.locator('#impactUpgradeAccept').click();expect(await page.evaluate(()=>window.__snapshotResult)).toBe(true);const result=await page.evaluate(()=>({backup:__fsMock.snapshot('backup').text,primary:JSON.parse(__fsMock.snapshot('primary').text),calls:__fsMock.calls()}));expect(result.backup).toBe(original);expect(result.primary.schema_version).toBe('3.2');expect(result.primary.snapshots).toHaveLength(1);expect(result.calls.findIndex(x=>x.op==='write'&&x.id==='backup')).toBeLessThan(result.calls.findIndex(x=>x.op==='write'&&x.id==='primary'))});

test('PBL042-P2-08: retention cancel, Escape and backdrop are non-destructive',async({page})=>{const history=Array.from({length:5},(_,i)=>snap('s'+i,`2026-09-0${i+1}T00:00:00.000Z`)),original=await adopt(page,'primary',root(history));for(const action of ['button','escape','backdrop']){await page.locator('#snapshotCreateBtn').click();await expect(page.locator('.snapshotRetentionDialog')).toBeVisible();if(action==='button')await page.locator('.snapshotRetentionDialog [data-choice="cancel"]').click();else if(action==='escape')await page.keyboard.press('Escape');else await page.locator('.askBack').click({position:{x:2,y:2}});expect(await page.evaluate(()=>({history:data.snapshots,text:__fsMock.snapshot('primary').text,writes:__fsMock.snapshot('primary').writeCount}))).toEqual({history,text:original,writes:0})}});

test('PBL042-P2-09: oldest replacement is deterministic with snapshot_id tie-break and one staged write',async({page})=>{const history=[snap('z','2026-09-01T00:00:00.000Z'),snap('a','2026-09-01T00:00:00.000Z'),snap('b','2026-09-02T00:00:00.000Z'),snap('c','2026-09-03T00:00:00.000Z'),snap('d','2026-09-04T00:00:00.000Z')];await adopt(page,'primary',root(history));await page.locator('#snapshotCreateBtn').click();await page.locator('[data-choice="oldest"]').click();await expect.poll(()=>page.evaluate(()=>__fsMock.snapshot('primary').writeCount)).toBe(1);const ids=await page.evaluate(()=>data.snapshots.map(x=>x.snapshot_id));expect(ids).not.toContain('a');expect(ids).toContain('z');expect(ids).toHaveLength(5)});

test('PBL042-P2-10: explicit target requires exactly one choice and replaces only that snapshot',async({page})=>{const history=Array.from({length:5},(_,i)=>snap('s'+i,`2026-09-0${i+1}T00:00:00.000Z`));await adopt(page,'primary',root(history));await page.locator('#snapshotCreateBtn').click();await page.locator('[data-choice="select"]').click();const accept=page.locator('.snapshotTargetDialog [data-action="accept"]');await expect(accept).toBeDisabled();await page.locator('input[value="s3"]').check();await expect(accept).toBeEnabled();await accept.click();await expect.poll(()=>page.evaluate(()=>__fsMock.snapshot('primary').writeCount)).toBe(1);const ids=await page.evaluate(()=>data.snapshots.map(x=>x.snapshot_id));expect(ids).not.toContain('s3');expect(ids.filter(x=>x.startsWith('snapshot-'))).toHaveLength(1);expect(ids).toHaveLength(5)});

test('PBL042-P2-11: failed replacement preserves all five runtime and persisted snapshots',async({page})=>{const history=Array.from({length:5},(_,i)=>snap('s'+i,`2026-09-0${i+1}T00:00:00.000Z`)),original=await adopt(page,'primary',root(history));await page.evaluate(()=>__fsMock.configure('primary',{failWrite:true}));await page.locator('#snapshotCreateBtn').click();await page.locator('[data-choice="oldest"]').click();await expect.poll(()=>page.evaluate(()=>saveState)).toBe('error');expect(await page.evaluate(()=>({history:data.snapshots,text:__fsMock.snapshot('primary').text,dirty}))).toEqual({history,text:original,dirty:false})});
