const {test,expect}=require('playwright/test');
const {APP}=require('./helpers/app-target');

const task=(id,extra={})=>({id,parentId:'',title:id,state:'未着手',owner:'',due:'2026-09-10',planned_duration_days:2,summary:`summary-${id}`,repeat:'',completed:false,dependencies:[],sortOrder:1000,impact_level:2,...extra});
const row=(page,id,team=false)=>page.locator(team?`.ganttRow[data-task-id="${id}"]`:`#row_${id}`);
async function boot(page,items,{view='open',mode='personal',date=false,detail=true}={}){await page.setViewportSize({width:1100,height:600});await page.goto(APP);await page.evaluate(()=>localStorage.clear());await page.reload();await page.evaluate(({items,view,mode,date,detail})=>{applyJsonObject({schema_version:'2.5',workspace_info_markdown:'',items},'pbl027','pbl027.json',null,{remember:false,writePermissionGranted:false});setView(view);if(mode==='personal'){setMode('personal');setSortMode(date?'date':'tree')}else{projectDetailVisible=detail;setMode('team')}clearUndoHistory('pbl027');dirty=false},{items,view,mode,date,detail});}
async function settle(page){await page.waitForTimeout(950)}

test('PBL027 normal End visibly holds committed state and faithful ToDo geometry before exit',async({page})=>{await boot(page,[task('A'),task('B',{sortOrder:2000}),task('C',{sortOrder:3000})],{date:true});const source=await row(page,'A').evaluate(el=>{const r=el.getBoundingClientRect();return{left:r.left,width:r.width,cells:[...el.children].map(cell=>{const x=cell.getBoundingClientRect();return{left:x.left,width:x.width}})}}),before=await row(page,'B').evaluate(el=>el.getBoundingClientRect().top);await row(page,'A').locator('.doneBtn').click();const ghost=page.locator('.pbl027ExitGhost[data-task-id="A"]');await expect(ghost).toBeVisible();await expect(ghost.locator('.doneBtn')).toHaveClass(/done/);await expect(ghost.locator('.doneBtn')).toHaveText('✓');const heldGeometry=await ghost.evaluate(el=>{const r=el.getBoundingClientRect(),row=el.querySelector('tr');return{left:r.left,width:r.width,cells:[...row.children].map(cell=>{const x=cell.getBoundingClientRect();return{left:x.left,width:x.width}})}});expect(Math.abs(heldGeometry.left-source.left)).toBeLessThan(1);expect(Math.abs(heldGeometry.width-source.width)).toBeLessThan(1);heldGeometry.cells.forEach((cell,index)=>{expect(Math.abs(cell.left-source.cells[index].left)).toBeLessThan(2);expect(Math.abs(cell.width-source.cells[index].width)).toBeLessThan(2)});expect(await ghost.evaluate(el=>({hidden:el.getAttribute('aria-hidden'),pointer:getComputedStyle(el).pointerEvents,focusable:[...el.querySelectorAll('button,input,select,textarea,[contenteditable=true]')].filter(node=>!node.disabled&&node.tabIndex>=0).length}))).toEqual({hidden:'true',pointer:'none',focusable:0});expect(await page.evaluate(()=>itemById('A').completed)).toBe(true);await expect(row(page,'A')).toHaveCount(0);await expect(row(page,'B')).toHaveClass(/pbl027Survivor/);await page.waitForTimeout(300);expect(await ghost.evaluate(el=>getComputedStyle(el).opacity)).toBe('1');expect(await ghost.evaluate(el=>el.getBoundingClientRect().height)).toBeGreaterThan(10);const held=await row(page,'B').evaluate(el=>el.getBoundingClientRect().top);expect(held).toBeCloseTo(before,0);await page.waitForTimeout(350);const during=await row(page,'B').evaluate(el=>el.getBoundingClientRect().top);expect(during).toBeLessThan(before-1);await settle(page);await expect(ghost).toHaveCount(0);const final=await row(page,'B').evaluate(el=>el.getBoundingClientRect().top);expect(final).toBeLessThan(before);expect(during).toBeGreaterThanOrEqual(final-1)});

test('PBL027 Reopen holds its committed state; Undo enters and Redo exits symmetrically',async({page})=>{await boot(page,[task('A',{state:'完了',completed:true}),task('B',{state:'完了',completed:true,sortOrder:2000})],{view:'done',date:true});await row(page,'A').locator('.doneBtn').click();const reopenGhost=page.locator('.pbl027ExitGhost[data-task-id="A"]');await expect(reopenGhost).toBeVisible();await expect(reopenGhost.locator('.doneBtn')).toHaveText('○');expect((await reopenGhost.locator('.doneBtn').getAttribute('class')).split(/\s+/)).not.toContain('done');await page.waitForTimeout(300);await expect(reopenGhost).toBeVisible();await settle(page);await page.keyboard.press('Control+z');await expect(row(page,'A')).toBeVisible();await expect(row(page,'A')).toHaveClass(/pbl027Entry/);expect(await page.evaluate(()=>itemById('A').completed)).toBe(true);await settle(page);await page.keyboard.press('Control+y');await expect(page.locator('.pbl027ExitGhost[data-task-id="A"]')).toBeVisible();expect(await page.evaluate(()=>itemById('A').completed)).toBe(false);await settle(page)});

test('PBL027 All view updates state without fake exit or entry',async({page})=>{await boot(page,[task('A'),task('B',{sortOrder:2000})],{view:'all'});await row(page,'A').locator('.doneBtn').click();await expect(row(page,'A')).toBeVisible();await expect(page.locator('.pbl027ExitGhost,.pbl027Entry')).toHaveCount(0);expect(await page.evaluate(()=>itemById('A').completed)).toBe(true)});

test('PBL027 selection and Task Detail remain bound to hidden task',async({page})=>{await boot(page,[task('A'),task('B',{sortOrder:2000})]);await row(page,'A').locator('.taskDetailOpenBtn').click();await row(page,'A').locator('.doneBtn').click();await expect(row(page,'A')).toHaveCount(0);expect(await page.evaluate(()=>selectedTaskId)).toBe('A');await expect(page.locator('#taskDetailPane')).toBeVisible();expect(await page.evaluate(()=>taskDetailPaneTaskId)).toBe('A');expect(await page.locator('.pbl027ExitGhost').evaluate(el=>[...el.querySelectorAll('button,input,select,textarea,[contenteditable=true]')].every(node=>node.disabled||node.tabIndex<0))).toBe(true)});

test('PBL027 cascade holds one committed simultaneous group and one Undo restores it',async({page})=>{await boot(page,[task('P'),task('C',{parentId:'P',state:'完了',sortOrder:2000}),task('G',{parentId:'C',state:'中止',sortOrder:3000})]);await row(page,'P').locator('.doneBtn').click();const ghosts=page.locator('.pbl027ExitGhost');await expect(ghosts).toHaveCount(3);const primary=page.locator('.pbl027ExitGhost.pbl027Primary[data-task-id="P"]');await expect(primary).toHaveCount(1);await expect(primary.locator('.doneBtn')).toHaveText('✓');await page.waitForTimeout(300);await expect(ghosts).toHaveCount(3);expect(await page.evaluate(()=>({closed:data.items.map(x=>x.completed),undo:undoStack.length}))).toEqual({closed:[true,true,true],undo:1});await settle(page);await page.keyboard.press('Control+z');await expect(row(page,'P')).toHaveClass(/pbl027Entry/);await expect(row(page,'C')).toHaveClass(/pbl027Entry/);await expect(row(page,'G')).toHaveClass(/pbl027Entry/);expect(await page.evaluate(()=>data.items.map(x=>x.completed))).toEqual([false,false,false])});

test('PBL027 a row retained as ToDo hierarchy context does not fake an exit',async({page})=>{await boot(page,[task('P',{state:'完了',completed:true,owner:'other'}),task('C',{parentId:'P',state:'完了',completed:true,owner:'match',sortOrder:2000})],{view:'done'});await page.evaluate(()=>{ownerFilterValues=new Set(['match']);render()});await expect(row(page,'P')).toHaveClass(/contextRow/);await row(page,'P').locator('.doneBtn').click();await expect(row(page,'P')).toBeVisible();await expect(page.locator('.pbl027ExitGhost[data-task-id="P"]')).toHaveCount(0);await expect(row(page,'P')).toHaveClass(/contextRow/)});

for(const detail of[true,false])test(`PBL027 Project ${detail?'detail':'simple'} preserves row geometry and horizontal scroll`,async({page})=>{await boot(page,[task('A'),task('B',{due:'2027-12-10',sortOrder:2000}),task('C',{due:'2025-01-10',sortOrder:3000})],{mode:'team',detail});await page.setViewportSize({width:720,height:600});await page.waitForTimeout(80);await page.evaluate(()=>{ganttView.scrollLeft=Math.min(60,ganttView.scrollWidth-ganttView.clientWidth);projectOuterScrollLeft=ganttView.scrollLeft;setGanttTimelineScroll(120)});const horizontal=await page.evaluate(()=>({outer:ganttView.scrollLeft,timeline:ganttTimelineScrollLeft}));expect(horizontal.outer).toBeGreaterThan(0);expect(horizontal.timeline).toBeGreaterThan(0);const source=await row(page,'A',true).evaluate(el=>{const r=el.getBoundingClientRect(),left=el.querySelector('.ganttLeftPane').getBoundingClientRect(),clip=el.querySelector('.ganttTimelineClip').getBoundingClientRect();return{row:{left:r.left,width:r.width,height:r.height},left:{left:left.left,width:left.width},clip:{left:clip.left,width:clip.width}}});await row(page,'A',true).locator('.doneBtn').dispatchEvent('click');const ghost=page.locator('.pbl027ExitGhost[data-task-id="A"]');await expect(ghost).toBeVisible();await expect(ghost.locator('.doneBtn')).toHaveText('✓');const held=await ghost.evaluate(el=>{const row=el.querySelector('.ganttRow'),r=row.getBoundingClientRect(),left=row.querySelector('.ganttLeftPane').getBoundingClientRect(),clip=row.querySelector('.ganttTimelineClip').getBoundingClientRect();return{row:{left:r.left,width:r.width,height:r.height},left:{left:left.left,width:left.width},clip:{left:clip.left,width:clip.width}}});for(const part of['row','left','clip'])for(const key of Object.keys(source[part]))expect(Math.abs(held[part][key]-source[part][key])).toBeLessThan(2);expect(await row(page,'B',true).locator('.sum').count()).toBe(detail?1:0);await settle(page);const after=await page.evaluate(()=>({outer:ganttView.scrollLeft,timeline:ganttTimelineScrollLeft}));expect(after.outer).toBe(horizontal.outer);expect(after.timeline).toBeCloseTo(horizontal.timeline,6)});

test('PBL027 active filters use final rendered membership and do not invent entries',async({page})=>{await boot(page,[task('A',{owner:'x',impact_level:3}),task('B',{owner:'y',impact_level:1,sortOrder:2000})]);await page.evaluate(()=>{ownerFilterValues=new Set(['x']);priorityFilterThreshold=2;render()});await row(page,'A').locator('.doneBtn').click();await expect(page.locator('.pbl027ExitGhost[data-task-id="A"]')).toBeVisible();await settle(page);await page.keyboard.press('Control+z');await expect(row(page,'A')).toHaveClass(/pbl027Entry/);await expect(row(page,'B')).toHaveCount(0)});

test('PBL027 recurring Close stays on PBL030 Due path without exit visual',async({page})=>{await boot(page,[task('R',{repeat:'毎年',recurrence_rule:{type:'yearly',month:9,day:10}}),task('B',{due:'2027-01-01',sortOrder:2000})],{date:true});const before=await page.evaluate(()=>itemById('R').due);await row(page,'R').locator('.doneBtn').click();await expect(row(page,'R')).toBeVisible();await expect(page.locator('.pbl027ExitGhost,.pbl027Entry')).toHaveCount(0);expect(await page.evaluate(()=>({id:itemById('R').id,due:itemById('R').due,closed:itemById('R').completed}))).toEqual({id:'R',due:'2027-09-10',closed:false});expect(await page.evaluate(()=>itemById('R').due)).not.toBe(before)});

test('PBL027 reduced motion completes immediately and rapid next action leaves no visual residue',async({page})=>{await page.emulateMedia({reducedMotion:'reduce'});await boot(page,[task('A'),task('B',{sortOrder:2000})],{date:true});await row(page,'A').locator('.doneBtn').click();await page.waitForTimeout(40);await expect(page.locator('.pbl027ExitGhost,.pbl027Entry,.pbl027Survivor')).toHaveCount(0);await row(page,'B').locator('.doneBtn').click();await page.waitForTimeout(40);await expect(page.locator('.pbl027ExitGhost,.pbl027Entry,.pbl027Survivor')).toHaveCount(0);expect(await page.evaluate(()=>undoStack.length)).toBe(2)});
