const {test,expect}=require('playwright/test');
const {APP}=require('./helpers/app-target');

const task=(id,extra={})=>({id,parentId:'',state:'未着手',impact_level:2,title:id,owner:'',due:'',planned_duration_days:null,summary:`Summary ${id}`,repeat:'',completed:false,source:'',asana_task_id:'',history:[],dependencies:[],sortOrder:1000,...extra});
const items=[task('A',{due:'2026-09-20'}),task('A1',{parentId:'A',due:'2026-09-05'}),task('B',{due:'2026-09-10',sortOrder:2000}),task('C',{sortOrder:3000})];

async function boot(page){await page.setViewportSize({width:1440,height:800});await page.goto(APP);await page.evaluate(()=>localStorage.clear());await page.reload();await page.evaluate(items=>{applyJsonObject({schema_version:'2.5',workspace_info_markdown:'',items},'pbl019','pbl019.json',null,{remember:false,writePermissionGranted:false});setView('all');selectTask('A')},items)}
const state=page=>page.evaluate(()=>({mode,sortMode,detail:projectDetailVisible,key:displayModeKey(),selected:selectedTaskId,summary:data.items.find(x=>x.id==='A')?.summary||''}));
async function sendKey(page,key){if(/^[\x20-\x7e]$/.test(key)){await page.keyboard.press(key);return}await page.evaluate(key=>document.activeElement.dispatchEvent(new KeyboardEvent('keydown',{key,bubbles:true,cancelable:true})),key)}

test('PBL019-01 visible controls map exactly to the four agreed modes',async({page})=>{await boot(page);const controls=page.locator('#displayModeControls button');await expect(controls).toHaveCount(4);for(const [id,expected] of [['dmTodoTree',{mode:'personal',sortMode:'tree',detail:true,key:'todo-tree'}],['dmTodoDate',{mode:'personal',sortMode:'date',detail:true,key:'todo-date'}],['dmProjectDetail',{mode:'team',sortMode:'tree',detail:true,key:'project-detail'}],['dmProjectSimple',{mode:'team',sortMode:'tree',detail:false,key:'project-simple'}]]){await page.locator('#'+id).click();expect(await state(page)).toMatchObject(expected);await expect(page.locator('#'+id)).toHaveClass(/on/)}});

test('PBL019-02 T variants always resolve to ToDo tree from other modes',async({page})=>{for(const start of['todo-date','project-detail','project-simple'])for(const key of['T','t','Ｔ','ｔ']){await boot(page);await page.evaluate(start=>setDisplayMode(start),start);await sendKey(page,key);expect(await state(page)).toMatchObject({mode:'personal',sortMode:'tree',key:'todo-tree'})}});

test('PBL019-03 P variants always resolve to Project detail from other modes',async({page})=>{for(const start of['todo-tree','todo-date','project-simple'])for(const key of['P','p','Ｐ','ｐ']){await boot(page);await page.evaluate(start=>setDisplayMode(start),start);await sendKey(page,key);expect(await state(page)).toMatchObject({mode:'team',sortMode:'tree',detail:true,key:'project-detail'})}});

test('PBL019-04 contextual 1/2 and full-width digits stay within current family',async({page})=>{for(const [start,key,expected] of [['todo-date','1','todo-tree'],['todo-tree','２','todo-date'],['project-simple','１','project-detail'],['project-detail','2','project-simple']]){await boot(page);await page.evaluate(start=>setDisplayMode(start),start);await sendKey(page,key);expect((await state(page)).key).toBe(expected)}});

test('PBL019-05 Project detail/simple differ only by Summary while Priority remains visible',async({page})=>{await boot(page);await page.evaluate(()=>setDisplayMode('project-detail'));await expect(page.locator('#ganttView .projectInfoTable th[data-c="summary"]')).toBeVisible();await expect(page.locator('#ganttView .projectInfoTable th[data-c="impact"]')).toBeVisible();const detailCols=await page.evaluate(()=>cols());await page.evaluate(()=>setDisplayMode('project-simple'));await expect(page.locator('#ganttView .projectInfoTable th[data-c="summary"]')).toHaveCount(0);await expect(page.locator('#ganttView .projectInfoTable th[data-c="impact"]')).toBeVisible();const simpleCols=await page.evaluate(()=>cols());expect(detailCols.filter(x=>x!=='summary')).toEqual(simpleCols);expect(await state(page)).toMatchObject({summary:'Summary A'})});

test('PBL019-06 ToDo date mode preserves established date/tie/undated flattening',async({page})=>{await boot(page);await page.evaluate(()=>setDisplayMode('todo-date'));expect(await page.locator('#tbl tbody tr[id^="row_"]').evaluateAll(rows=>rows.map(row=>row.id.slice(4)))).toEqual(['A1','B','A','C']);expect(await page.locator('#tbl tbody .indent').evaluateAll(nodes=>nodes.map(n=>getComputedStyle(n).width))).toEqual(['0px','0px','0px','0px']);await page.evaluate(()=>setDisplayMode('todo-tree'));expect(await page.locator('#tbl tbody tr[id^="row_"]').evaluateAll(rows=>rows.map(row=>row.id.slice(4)))).toEqual(['B','A','A1','C'])});

test('PBL019-07 editing and IME guards retain ownership of T/P/1/2',async({page})=>{await boot(page);const title=page.locator('#row_A .titleText');await title.focus();await title.pressSequentially('TP12');await expect(title).toContainText('TP12');expect((await state(page)).key).toBe('todo-tree');await page.locator('#workspaceInfoPanel .workspaceInfoDisplay').click();const area=page.locator('#workspaceInfoEditor');await area.fill('TP12');await expect(area).toHaveValue('TP12');expect((await state(page)).key).toBe('todo-tree');await page.locator('body').evaluate(el=>{el.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true,data:''}));for(const key of['Ｔ','Ｐ','１','２'])el.dispatchEvent(new KeyboardEvent('keydown',{key,isComposing:true,keyCode:229,bubbles:true,cancelable:true}))});expect((await state(page)).key).toBe('todo-tree');await page.locator('body').dispatchEvent('compositionend',{data:'ＴＰ１２'})});

test('PBL019-08 PBL-028 D→E/digit, F2 and Enter remain protected',async({page})=>{await boot(page);await page.keyboard.press('D');await page.keyboard.press('E');await expect(page.locator('#row_A #d0')).toBeFocused();await page.locator('#row_A #d0').press('Escape');await page.keyboard.press('D');await page.keyboard.press('1');await expect(page.locator('#row_A #d0')).toBeFocused();await page.locator('#row_A #d0').press('Escape');await page.keyboard.press('F2');await expect(page.locator('#row_A .titleText')).toBeFocused();await page.locator('#row_A .titleText').press('Escape');await page.evaluate(()=>selectTask('A'));await page.keyboard.press('Enter');expect(await page.evaluate(()=>({draft:!!draftTaskId,kind:draftKind}))).toEqual({draft:true,kind:'same'})});

test('PBL019-09 LocalStorage restoration and DB replacement preserve the current philosophy',async({page})=>{await boot(page);await page.evaluate(()=>setDisplayMode('project-simple'));expect(await page.evaluate(()=>({mode:localStorage.getItem('yos_mode'),sort:localStorage.getItem('yos_sortMode'),detail:localStorage.getItem(PROJECT_DETAIL_KEY)}))).toEqual({mode:'team',sort:'tree',detail:'0'});await page.evaluate(items=>applyJsonObject({schema_version:'2.5',workspace_info_markdown:'B',items},'B','b.json',null,{remember:false}),[task('B2')]);expect((await state(page)).key).toBe('project-simple');await page.reload();expect(await page.evaluate(()=>({mode,sortMode,detail:projectDetailVisible,key:displayModeKey()}))).toEqual({mode:'team',sortMode:'tree',detail:false,key:'project-simple'})});

test('PBL019-10 Project widths, alignment, scroll and Task Detail survive detail/simple switching',async({page})=>{await boot(page);await page.evaluate(()=>{projectWidths.summary=360;setDisplayMode('project-detail');setGanttTimelineScroll(180);openTaskDetailPane('A')});const before=await page.evaluate(()=>({summary:projectWidths.summary,timeline:ganttTimelineScrollLeft,pane:taskDetailPaneOpen,task:taskDetailPaneTaskId}));await page.evaluate(()=>setDisplayMode('project-simple'));await page.waitForTimeout(50);await page.evaluate(()=>setDisplayMode('project-detail'));await page.waitForTimeout(50);expect(await page.evaluate(()=>({summary:projectWidths.summary,timeline:ganttTimelineScrollLeft,pane:taskDetailPaneOpen,task:taskDetailPaneTaskId}))).toEqual(before);const aligned=await page.evaluate(()=>{const head=document.querySelector('#ganttView .ganttHeader .ganttLeftPane').getBoundingClientRect(),row=document.querySelector('#ganttView .ganttRow[data-task-id="A"] .ganttLeftPane').getBoundingClientRect();return Math.abs(head.width-row.width)});expect(aligned).toBeLessThanOrEqual(1)});
