const {test,expect}=require('playwright/test');
const {installFsAccessMock}=require('./helpers/fs-access-mock');
const {APP}=require('./helpers/app-target');

const task=(id,extra={})=>({id,parentId:'',state:'',impact_level:0,title:id,owner:'',due:'',summary:'',repeat:'',completed:false,source:'',asana_task_id:'',history:[],dependencies:[],sortOrder:1000,...extra});
const snapshot=(id,day,items=[task(id)])=>({snapshot_id:id,captured_at:`2026-09-${String(day).padStart(2,'0')}T08:00:00.000Z`,product_version:'3.2.0',schema_version:'3.2',snapshot_format_version:'1.0',items});
async function boot(page,snapshots,{handle=false}={}){
  await installFsAccessMock(page);await page.goto(APP);await page.evaluate(()=>localStorage.clear());await page.reload();
  await page.evaluate(async({snapshots,handle})=>{const root={schema_version:'3.2',workspace_info_markdown:'',items:[{id:'LIVE',parentId:'',state:'',impact_level:0,title:'Live',owner:'',due:'',summary:'',repeat:'',completed:false,source:'',asana_task_id:'',history:[],dependencies:[],sortOrder:1}],snapshots},text=JSON.stringify(root),fileHandle=handle?__fsMock.create('primary',{name:'primary.json',text,writePermission:'granted'}):null,file=fileHandle?await fileHandle.getFile():null;await applyJsonObject(root,'phase4',file?.name||'fallback.json',fileHandle,{remember:false,writePermissionGranted:!!fileHandle,fileText:fileHandle?text:null,fileModified:file?.lastModified??null,fileSize:file?.size??null});clearUndoHistory('phase4');dirty=false;refreshDbStatus()},{snapshots,handle});
}
async function choose(page,ids){await page.locator('#snapshotCompareBtn').click();for(const id of ids)await page.locator(`input[name="snapshotCompareTarget"][value="${id}"]`).check();await page.locator('.snapshotComparisonDialog [data-action="accept"]').click()}

test('PBL042-P4-01 comparison availability depends only on loaded valid Snapshot count',async({page})=>{
  for(const count of[0,1,2,5]){await boot(page,Array.from({length:count},(_,i)=>snapshot('s'+i,i+1)));const button=page.locator('#snapshotCompareBtn');await expect(button).toBeVisible();expect(await button.isEnabled()).toBe(count>=2)}
  await boot(page,[snapshot('a',1),snapshot('b',2)],{handle:false});await expect(page.locator('#snapshotCompareBtn')).toBeEnabled();await expect(page.locator('#snapshotCreateBtn')).toBeDisabled();
});

test('PBL042-P4-02 modal is on demand, newest-first, exactly-two, and independent of retention selection',async({page})=>{
  await boot(page,[snapshot('old',1),snapshot('mid',2),snapshot('new',3)]);await expect(page.locator('.snapshotComparisonDialog')).toHaveCount(0);await page.locator('#snapshotCompareBtn').click();const inputs=page.locator('input[name="snapshotCompareTarget"]');expect(await inputs.evaluateAll(nodes=>nodes.map(node=>node.value))).toEqual(['new','mid','old']);await expect(page.locator('.snapshotComparisonDialog')).toContainText('2026/09/03');const accept=page.locator('.snapshotComparisonDialog [data-action="accept"]');await expect(accept).toBeDisabled();await inputs.nth(0).check();await expect(accept).toBeDisabled();await inputs.nth(1).check();await expect(accept).toBeEnabled();await expect(inputs.nth(2)).toBeDisabled();await inputs.nth(0).uncheck();await expect(inputs.nth(2)).toBeEnabled();await expect(accept).toBeDisabled();
});

test('PBL042-P4-03 selection order never controls chronology and output defaults to complete AI view',async({page})=>{
  const snapshots=[snapshot('old',1,[task('A',{title:'Before'}),task('same')]),snapshot('new',3,[task('A',{title:'After'}),task('same')])];await boot(page,snapshots);await choose(page,['new','old']);const drawer=page.locator('#snapshotOutputDrawer');await expect(drawer).toHaveClass(/open/);await expect(page.locator('#snapshotOutputAiTab')).toHaveClass(/active/);const ai=await page.locator('#snapshotOutputAi').inputValue(),json=await page.locator('#snapshotOutputJson').inputValue();expect(ai.startsWith(SNAPSHOT_PROMPT_FOR_TEST)).toBeTruthy();expect(ai.endsWith(json)).toBeTruthy();const parsed=JSON.parse(json);expect(parsed.comparison.before.snapshot_id).toBe('old');expect(parsed.comparison.after.snapshot_id).toBe('new');expect(parsed.tasks).toHaveLength(2);expect(parsed.summary.total_tasks).toBe(2);await expect(page.locator('#snapshotOutputPair')).toContainText('→');
});

const SNAPSHOT_PROMPT_FOR_TEST='以下はASANYAで抽出した2時点間のTask差分です。\nこの期間に何が変わったのか、分かりやすく要約してください。';

test('PBL042-P4-04 Cancel, Escape, backdrop, and ambiguous chronology are read-only',async({page})=>{
  await boot(page,[snapshot('a',1),snapshot('b',2)]);const before=await page.evaluate(()=>({data:JSON.stringify(data),dirty,undo:undoStack.length,redo:redoStack.length,state:JSON.stringify(snapshotComparisonState)}));for(const close of['cancel','escape','backdrop']){await page.locator('#snapshotCompareBtn').click();if(close==='cancel')await page.locator('.snapshotComparisonDialog [data-action="cancel"]').click();else if(close==='escape')await page.keyboard.press('Escape');else await page.locator('.askBack').click({position:{x:2,y:2}});await expect(page.locator('.snapshotComparisonDialog')).toHaveCount(0)}expect(await page.evaluate(()=>({data:JSON.stringify(data),dirty,undo:undoStack.length,redo:redoStack.length,state:JSON.stringify(snapshotComparisonState)}))).toEqual(before);
  const equal=[snapshot('x',1),{...snapshot('y',2),captured_at:snapshot('x',1).captured_at}];await boot(page,equal);await choose(page,['x','y']);expect(await page.locator('#snapshotOutputDrawer.open').count()).toBe(0);await expect(page.locator('#toast')).toContainText('比較できませんでした');
});

test('PBL042-P4-05 AI and JSON drafts edit independently, survive tabs, and reset only active view',async({page})=>{
  await boot(page,[snapshot('a',1),snapshot('b',2,[task('b',{summary:'new'})])]);await choose(page,['a','b']);const ai=page.locator('#snapshotOutputAi'),json=page.locator('#snapshotOutputJson'),reset=page.locator('#snapshotOutputReset'),originalAi=await ai.inputValue(),originalJson=await json.inputValue();await ai.fill('AI edit 日本語');await page.locator('#snapshotOutputJsonTab').click();await json.fill('{"edited":true}');await page.locator('#snapshotOutputAiTab').click();await expect(ai).toHaveValue('AI edit 日本語');await reset.click();await expect(ai).toHaveValue(originalAi);await page.locator('#snapshotOutputJsonTab').click();await expect(json).toHaveValue('{"edited":true}');await reset.click();await expect(json).toHaveValue(originalJson);expect(await page.evaluate(()=>snapshotComparisonState.semanticDiff.summary.total_tasks)).toBe(2);
});

test('PBL042-P4-06 copy uses exact active edited value, supports fallback, and reports failure honestly',async({page})=>{
  await page.addInitScript(()=>{Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:text=>{window.__copied=text;return Promise.resolve()}}})});await boot(page,[snapshot('a',1),snapshot('b',2)]);await choose(page,['a','b']);const ai=page.locator('#snapshotOutputAi');await ai.fill('edited AI');await page.locator('#snapshotOutputCopy').click();expect(await page.evaluate(()=>window.__copied)).toBe('edited AI');await page.locator('#snapshotOutputJsonTab').click();const json=page.locator('#snapshotOutputJson');await json.fill('edited JSON');await page.locator('#snapshotOutputCopy').click();expect(await page.evaluate(()=>window.__copied)).toBe('edited JSON');
  await page.evaluate(()=>{Object.defineProperty(navigator,'clipboard',{configurable:true,value:null});document.execCommand=command=>{window.__fallback=command;return true}});await page.locator('#snapshotOutputCopy').click();expect(await page.evaluate(()=>window.__fallback)).toBe('copy');await page.evaluate(()=>document.execCommand=()=>false);await page.locator('#snapshotOutputCopy').click();await expect(page.locator('#toast')).toContainText('コピーに失敗');await expect(json).toHaveValue('edited JSON');
});

test('PBL042-P4-07 a successful new comparison replaces canonical output and both edited drafts',async({page})=>{
  await boot(page,[snapshot('a',1,[task('T',{title:'A'})]),snapshot('b',2,[task('T',{title:'B'})]),snapshot('c',3,[task('T',{title:'C'})])]);await choose(page,['a','b']);await page.locator('#snapshotOutputAi').fill('old AI edit');await page.locator('#snapshotOutputJsonTab').click();await page.locator('#snapshotOutputJson').fill('old JSON edit');await page.locator('#snapshotOutputClose').click();await choose(page,['b','c']);expect(await page.locator('#snapshotOutputAi').inputValue()).not.toContain('old AI edit');expect(await page.locator('#snapshotOutputJson').inputValue()).not.toContain('old JSON edit');expect(JSON.parse(await page.locator('#snapshotOutputJson').inputValue()).comparison.before.snapshot_id).toBe('b');await expect(page.locator('#snapshotOutputAiTab')).toHaveClass(/active/);
});

test('PBL042-P4-08 UI comparison, editing, reset, close, and copy never mutate product or persistence state',async({page})=>{
  await page.addInitScript(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:()=>Promise.resolve()}}));await boot(page,[snapshot('a',1),snapshot('b',2)],{handle:true});const before=await page.evaluate(()=>({data:JSON.stringify(data),dirty,undo:undoStack.length,redo:redoStack.length,writes:__fsMock.snapshot('primary').writeCount,text:__fsMock.snapshot('primary').text}));await choose(page,['a','b']);await page.locator('#snapshotOutputAi').fill('edit');await page.locator('#snapshotOutputReset').click();await page.locator('#snapshotOutputCopy').click();await page.locator('#snapshotOutputClose').click();expect(await page.evaluate(()=>({data:JSON.stringify(data),dirty,undo:undoStack.length,redo:redoStack.length,writes:__fsMock.snapshot('primary').writeCount,text:__fsMock.snapshot('primary').text}))).toEqual(before);
});

test('PBL042-P4-09 editable output owns shortcut and composition keys without Task actions',async({page})=>{
  await boot(page,[snapshot('a',1),snapshot('b',2)]);await choose(page,['a','b']);for(const tab of['ai','json']){await page.locator(tab==='ai'?'#snapshotOutputAiTab':'#snapshotOutputJsonTab').click();const textarea=page.locator(tab==='ai'?'#snapshotOutputAi':'#snapshotOutputJson');await textarea.fill('abc');await textarea.focus();await page.keyboard.press('End');await page.keyboard.press('Enter');await page.keyboard.type('N B C');await page.keyboard.press('Backspace');await page.keyboard.press('Delete');await textarea.dispatchEvent('compositionstart',{data:'に'});await textarea.dispatchEvent('compositionend',{data:'日本'});expect(await page.evaluate(()=>({items:data.items.length,completed:data.items[0].completed,undo:undoStack.length}))).toEqual({items:1,completed:false,undo:0})}
});

test('PBL042-P4-10 long output is complete, scrollable, editable, and keeps actions reachable',async({page})=>{
  const many=Array.from({length:120},(_,i)=>task('T'+String(i).padStart(3,'0'),{summary:('長い概要'+i+'\n').repeat(20)}));await boot(page,[snapshot('a',1,many),snapshot('b',2,many.map((item,i)=>i===0?{...item,title:'changed'}:item))]);await choose(page,['a','b']);const textarea=page.locator('#snapshotOutputAi'),full=await textarea.inputValue();expect(full.length).toBeGreaterThan(90000);expect(await textarea.evaluate(el=>el.scrollHeight>el.clientHeight)).toBeTruthy();await textarea.press('End');await textarea.pressSequentially('追記');await expect(page.locator('#snapshotOutputReset')).toBeVisible();await expect(page.locator('#snapshotOutputCopy')).toBeVisible();expect(await textarea.inputValue()).toContain('T119');
});

test('PBL042-P4-FU-01 new comparison starts both views at top and ordinary tab switching preserves per-view scroll',async({page})=>{
  const many=Array.from({length:100},(_,i)=>task('T'+String(i).padStart(3,'0'),{summary:('scroll '+i+'\n').repeat(25)})),snapshots=[snapshot('a',1,many),snapshot('b',2,many.map((item,i)=>i===0?{...item,title:'B'}:item)),snapshot('c',3,many.map((item,i)=>i===0?{...item,title:'C'}:item))];await boot(page,snapshots);await choose(page,['a','b']);const ai=page.locator('#snapshotOutputAi'),json=page.locator('#snapshotOutputJson');expect(await ai.evaluate(el=>({top:el.scrollTop,start:el.selectionStart}))).toEqual({top:0,start:0});expect(await ai.inputValue()).toContain(SNAPSHOT_PROMPT_FOR_TEST);expect(await ai.inputValue()).not.toContain('Sprint Incrementとして');await ai.evaluate(el=>el.scrollTop=600);const aiScroll=await ai.evaluate(el=>el.scrollTop);expect(aiScroll).toBeGreaterThan(0);await page.locator('#snapshotOutputJsonTab').click();expect(await json.evaluate(el=>({top:el.scrollTop,start:el.selectionStart}))).toEqual({top:0,start:0});await json.evaluate(el=>el.scrollTop=800);const jsonScroll=await json.evaluate(el=>el.scrollTop);expect(jsonScroll).toBeGreaterThan(0);await page.locator('#snapshotOutputAiTab').click();expect(await ai.evaluate(el=>el.scrollTop)).toBe(aiScroll);await page.locator('#snapshotOutputJsonTab').click();expect(await json.evaluate(el=>el.scrollTop)).toBe(jsonScroll);await page.locator('#snapshotOutputClose').click();await choose(page,['b','c']);expect(await ai.evaluate(el=>({top:el.scrollTop,start:el.selectionStart}))).toEqual({top:0,start:0});await page.locator('#snapshotOutputJsonTab').click();expect(await json.evaluate(el=>({top:el.scrollTop,start:el.selectionStart}))).toEqual({top:0,start:0});
});
