const {test,expect}=require('playwright/test');
const {APP}=require('./helpers/app-target');
const task=(id,parentId='',sortOrder=1000)=>({id,parentId,title:id,state:'未着手',owner:'',due:'',planned_duration_days:null,summary:'',repeat:'',completed:false,dependencies:[],sortOrder,impact_level:1});
async function boot(page,mode='todo-tree'){
  await page.setViewportSize({width:1280,height:720});await page.goto(APP);await page.evaluate(()=>localStorage.clear());await page.reload();
  await page.evaluate(({items,mode})=>{applyJsonObject({schema_version:'2.5',workspace_info_markdown:'',items},'pbl021','pbl021.json',null,{remember:false,writePermissionGranted:false});setView('all');setDisplayMode(mode);clearUndoHistory('pbl021');dirty=false},{items:[task('ROOT'),task('CHILD','ROOT',2000),task('OTHER','',3000)],mode});
}
async function rect(locator){return locator.evaluate(el=>{const r=el.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height}})}
async function titleControls(page,id='ROOT'){return page.locator(`#row_${id} .titleWrap`).evaluate(el=>[...el.children].map(node=>({cls:node.className,text:node.textContent.trim(),x:node.getBoundingClientRect().x}))) }
async function projectFixture(page){await boot(page,'project-detail');await page.evaluate(()=>{const make=(id,parentId='',sortOrder=1000)=>({id,parentId,title:id,state:'未着手',owner:'',due:'',planned_duration_days:null,summary:'',repeat:'',completed:false,dependencies:[],sortOrder,impact_level:1});applyJsonObject({schema_version:'2.5',items:[make('A'),make('A1','A',2000),make('A1a','A1',3000),make('B','',4000),make('C','',5000)]},'pbl021-project','pbl021-project.json',null,{remember:false,writePermissionGranted:false});setView('all');setDisplayMode('project-detail');clearUndoHistory('pbl021-project');dirty=false})}
async function projectOrder(page){return page.locator('#ganttView .ganttRow[data-task-id]').evaluateAll(rows=>rows.map(row=>row.dataset.taskId))}

test('PBL021-R01 all four modes place plus between drag and detail with no Child column',async({page})=>{
  await boot(page);for(const mode of ['todo-tree','todo-date','project-detail','project-simple']){await page.evaluate(mode=>setDisplayMode(mode),mode);await expect(page.locator('#head [data-c="child"],.ganttHeader [data-c="child"]')).toHaveCount(0);const controls=await titleControls(page);const drag=controls.findIndex(x=>String(x.cls).includes('siblingDragHandle')),add=controls.findIndex(x=>String(x.cls).includes('taskAddBtn')),detail=controls.findIndex(x=>String(x.cls).includes('taskDetailOpenBtn'));expect(drag).toBeGreaterThanOrEqual(0);expect(add).toBe(drag+1);expect(detail).toBe(add+1);await expect(page.locator('#row_ROOT .taskAddBtn')).toHaveText('＋');await expect(page.locator('#row_ROOT .taskAddBtn')).toHaveAttribute('aria-label','タスクを追加')}
});

test('PBL021-R02 default/hover/selected/focus change emphasis but not geometry',async({page})=>{
  await boot(page);const button=page.locator('#row_ROOT .taskAddBtn'),title=page.locator('#row_ROOT .titleText'),before={button:await rect(button),title:await rect(title),row:await rect(page.locator('#row_ROOT'))};expect(Number(await button.evaluate(el=>getComputedStyle(el).opacity))).toBeLessThan(.5);await button.hover();await page.waitForTimeout(160);expect(Number(await button.evaluate(el=>getComputedStyle(el).opacity))).toBeGreaterThan(.9);expect({button:await rect(button),title:await rect(title),row:await rect(page.locator('#row_ROOT'))}).toEqual(before);await page.evaluate(()=>selectTask('ROOT'));await page.waitForTimeout(160);expect(Number(await button.evaluate(el=>getComputedStyle(el).opacity))).toBeGreaterThan(.9);expect(await rect(title)).toEqual(before.title);await page.evaluate(()=>selectTask('OTHER'));await button.focus();await page.waitForTimeout(160);expect(Number(await button.evaluate(el=>getComputedStyle(el).opacity))).toBeGreaterThan(.9);expect(await button.evaluate(el=>getComputedStyle(el).outlineStyle)).not.toBe('none');expect(await rect(title)).toEqual(before.title)
});

test('PBL021-R03 tooltip uses revised wording and delay',async({page})=>{
  await boot(page);const button=page.locator('#row_ROOT .taskAddBtn');await button.hover();await page.waitForTimeout(350);await expect(page.locator('#tip')).toBeHidden();await page.waitForTimeout(450);await expect(page.locator('#tip')).toHaveText('タスクを追加');await expect(page.locator('#tip')).toBeVisible();await page.mouse.move(1200,700);await expect(page.locator('#tip')).toBeHidden()
});

test('PBL021-R04 menu toggles, closes outside/Escape, and moves between rows',async({page})=>{
  await boot(page);const root=page.locator('#row_ROOT .taskAddBtn'),other=page.locator('#row_OTHER .taskAddBtn');await root.click();await expect(page.locator('.taskAddMenu')).toBeVisible();await expect(page.locator('.taskAddMenu button')).toHaveText(['同じ階層に追加','1つ下の階層に追加']);expect(await page.locator('.taskAddMenu').evaluate(el=>getComputedStyle(el).flexDirection)).toBe('column');await root.click();await expect(page.locator('.taskAddMenu')).toHaveCount(0);await root.click();await page.mouse.click(1200,700);await expect(page.locator('.taskAddMenu')).toHaveCount(0);await root.click();await page.keyboard.press('Escape');await expect(page.locator('.taskAddMenu')).toHaveCount(0);await expect(root).toBeFocused();await root.click();await other.click();await expect(page.locator('.taskAddMenu')).toHaveCount(1);expect(await page.locator('.taskAddMenu').evaluate(el=>Math.abs(el.getBoundingClientRect().left-document.querySelector('#row_OTHER .taskAddBtn').getBoundingClientRect().left))).toBeLessThan(2)
});

test('PBL021-R05 same-level menu action creates immediate sibling draft and focuses title',async({page})=>{
  await boot(page);await page.evaluate(()=>selectTask('OTHER'));await page.locator('#row_CHILD .taskAddBtn').click();await page.getByRole('menuitem',{name:'同じ階層に追加'}).click();const result=await page.evaluate(()=>({draft:draftTaskId,parent:itemById(draftTaskId)?.parentId,selected:selectedTaskId,origin:draftOriginId,order:visible().map(x=>x.x.id)}));expect(result).toMatchObject({parent:'ROOT',selected:result.draft,origin:'CHILD'});expect(result.order.indexOf(result.draft)).toBe(result.order.indexOf('CHILD')+1);await expect(page.locator(`#row_${result.draft} .titleText`)).toBeFocused();await expect(page.locator('.taskAddMenu')).toHaveCount(0)
});

test('PBL021-R06 child menu action creates child draft and focuses title',async({page})=>{
  await boot(page);await page.locator('#row_OTHER .taskAddBtn').click();await page.getByRole('menuitem',{name:'1つ下の階層に追加'}).click();const result=await page.evaluate(()=>({draft:draftTaskId,parent:itemById(draftTaskId)?.parentId,selected:selectedTaskId,origin:draftOriginId}));expect(result).toMatchObject({parent:'OTHER',selected:result.draft,origin:'OTHER'});await expect(page.locator(`#row_${result.draft} .titleText`)).toBeFocused()
});

test('PBL021-R07 Insert/Enter/Escape/Undo boundaries remain unchanged',async({page})=>{
  await boot(page);await page.evaluate(()=>selectTask('ROOT'));await page.locator('#displayModeControls').focus();await page.keyboard.press('Insert');let id=await page.evaluate(()=>draftTaskId);expect(await page.evaluate(id=>itemById(id).parentId,id)).toBe('ROOT');await page.keyboard.press('Escape');await page.evaluate(()=>selectTask('CHILD'));await page.locator('#displayModeControls').focus();await page.keyboard.press('Enter');id=await page.evaluate(()=>draftTaskId);expect(await page.evaluate(id=>itemById(id).parentId,id)).toBe('ROOT');await page.locator(`#row_${id} .titleText`).press('Enter');expect(await page.evaluate(()=>draftTaskId)).toBe('');expect(await page.evaluate(()=>undoStack.length)).toBe(0)
});

test('PBL021-R08 normal/draft have no old blank column and PBL026 coordinates align',async({page})=>{
  await boot(page);const normal=await page.locator('#row_CHILD .titleText').evaluate(el=>el.getBoundingClientRect().left);await page.evaluate(()=>selectTask('ROOT'));await page.locator('#displayModeControls').focus();await page.keyboard.press('Insert');const id=await page.evaluate(()=>draftTaskId),draft=await page.locator(`#row_${id} .titleText`).evaluate(el=>el.getBoundingClientRect().left);expect(Math.abs(draft-normal)).toBeLessThanOrEqual(1);await expect(page.locator(`#row_${id} td`)).toHaveCount(await page.locator('#head th').count());await expect(page.locator(`#row_${id} .taskAddBtn`)).toBeHidden();await expect(page.locator(`#row_${id} td.miniCell`)).toHaveCount(0)
});

test('PBL021-R09 Project detail/simple keep normal/draft boundaries and horizontal scroll',async({page})=>{
  await boot(page,'project-detail');for(const mode of ['project-detail','project-simple']){await page.evaluate(mode=>setDisplayMode(mode),mode);const before=await page.evaluate(()=>({info:projectInfoWidth(),clip:document.querySelector('.ganttHeader .ganttTimelineClip').getBoundingClientRect().left,outer:ganttView.scrollLeft,cols:cols()}));expect(before.cols).not.toContain('child');await page.locator('#row_ROOT .taskAddBtn').hover();await page.evaluate(()=>selectTask('ROOT'));await page.locator('#row_ROOT .taskAddBtn').focus();const after=await page.evaluate(()=>({info:projectInfoWidth(),clip:document.querySelector('.ganttHeader .ganttTimelineClip').getBoundingClientRect().left,outer:ganttView.scrollLeft}));expect(after).toEqual({info:before.info,clip:before.clip,outer:before.outer});await page.keyboard.press('Insert');const id=await page.evaluate(()=>draftTaskId);expect(Math.abs(await page.locator(`#row_${id} .titleText`).evaluate(el=>el.getBoundingClientRect().left)-await page.locator('#row_CHILD .titleText').evaluate(el=>el.getBoundingClientRect().left))).toBeLessThanOrEqual(1);expect(await page.evaluate(()=>document.querySelector('.ganttHeader .ganttTimelineClip').getBoundingClientRect().left)).toBe(before.clip);await page.keyboard.press('Escape')}
});

test('PBL021-R10 menu opening is runtime-only',async({page})=>{
  await boot(page);const before=await page.evaluate(()=>({json:JSON.stringify(persistableData()),dirty,undo:undoStack.length,selected:selectedTaskId}));await page.locator('#row_ROOT .taskAddBtn').click();expect(await page.evaluate(()=>({json:JSON.stringify(persistableData()),dirty,undo:undoStack.length,selected:selectedTaskId}))).toEqual(before);await page.keyboard.press('Escape');expect(await page.evaluate(()=>CURRENT_SCHEMA_VERSION)).toBe(APP.includes('pbl022')?'3.0':'2.5')
});

test('PBL021-F01 Project Enter inserts a sibling after a leaf and before the next sibling',async({page})=>{
  await projectFixture(page);await page.evaluate(()=>selectTask('B'));await page.locator('#displayModeControls').focus();await page.keyboard.press('Enter');const result=await page.evaluate(()=>({id:draftTaskId,parent:itemById(draftTaskId)?.parentId,selected:selectedTaskId}));expect(result).toMatchObject({parent:'',selected:result.id});const order=await projectOrder(page);expect(order.indexOf(result.id)).toBe(order.indexOf('B')+1);expect(order.indexOf(result.id)).toBeLessThan(order.indexOf('C'));await expect(page.locator(`#row_${result.id} .titleText`)).toBeFocused()
});

test('PBL021-F02 Project Enter inserts a sibling after the complete reference subtree',async({page})=>{
  await projectFixture(page);await page.evaluate(()=>selectTask('A'));await page.locator('#displayModeControls').focus();await page.keyboard.press('Enter');const id=await page.evaluate(()=>draftTaskId),order=await projectOrder(page);expect(await page.evaluate(id=>itemById(id)?.parentId,id)).toBe('');expect(order.indexOf(id)).toBe(order.indexOf('A1a')+1);expect(order.indexOf(id)).toBeLessThan(order.indexOf('B'));await expect(page.locator(`#row_${id} .titleText`)).toBeFocused()
});

test('PBL021-F03 Project same-level menu exactly matches Enter placement for leaf and subtree',async({page})=>{
  for(const origin of ['B','A']){await projectFixture(page);await page.locator(`#row_${origin} .taskAddBtn`).click();await page.getByRole('menuitem',{name:'同じ階層に追加'}).click();const id=await page.evaluate(()=>draftTaskId),order=await projectOrder(page),anchor=origin==='A'?'A1a':'B',next=origin==='A'?'B':'C';expect(await page.evaluate(id=>({parent:itemById(id)?.parentId,selected:selectedTaskId}),id)).toEqual({parent:'',selected:id});expect(order.indexOf(id)).toBe(order.indexOf(anchor)+1);expect(order.indexOf(id)).toBeLessThan(order.indexOf(next));await expect(page.locator(`#row_${id} .titleText`)).toBeFocused()}
});

test('PBL021-F04 Project Insert and child menu retain child semantics',async({page})=>{
  await projectFixture(page);await page.evaluate(()=>selectTask('B'));await page.locator('#displayModeControls').focus();await page.keyboard.press('Insert');let id=await page.evaluate(()=>draftTaskId);expect(await page.evaluate(id=>itemById(id)?.parentId,id)).toBe('B');await page.keyboard.press('Escape');await page.locator('#row_B .taskAddBtn').click();await page.getByRole('menuitem',{name:'1つ下の階層に追加'}).click();id=await page.evaluate(()=>draftTaskId);expect(await page.evaluate(id=>itemById(id)?.parentId,id)).toBe('B');await expect(page.locator(`#row_${id} .titleText`)).toBeFocused()
});

test('PBL021-F05 ToDo Enter and same-level menu remain after the complete subtree',async({page})=>{
  for(const viaMenu of [false,true]){await boot(page);await page.evaluate(()=>{const make=(id,parentId='',sortOrder=1000)=>({id,parentId,title:id,state:'未着手',owner:'',due:'',planned_duration_days:null,summary:'',repeat:'',completed:false,dependencies:[],sortOrder,impact_level:1});applyJsonObject({schema_version:'2.5',items:[make('A'),make('A1','A',2000),make('A1a','A1',3000),make('B','',4000)]},'pbl021-todo','pbl021-todo.json',null,{remember:false,writePermissionGranted:false});setView('all');setDisplayMode('todo-tree');selectTask('A')});if(viaMenu){await page.locator('#row_A .taskAddBtn').click();await page.getByRole('menuitem',{name:'同じ階層に追加'}).click()}else{await page.locator('#displayModeControls').focus();await page.keyboard.press('Enter')}const id=await page.evaluate(()=>draftTaskId),order=await page.locator('#body tr[id^="row_"]').evaluateAll(rows=>rows.map(row=>row.id.slice(4)));expect(order.indexOf(id)).toBe(order.indexOf('A1a')+1);expect(order.indexOf(id)).toBeLessThan(order.indexOf('B'))}
});

test('PBL021-F06 compact controls keep order, stable geometry, and usable targets in all views',async({page})=>{
  await boot(page);for(const mode of ['todo-tree','todo-date','project-detail','project-simple']){await page.evaluate(mode=>setDisplayMode(mode),mode);const row=page.locator('#row_ROOT'),drag=row.locator('.siblingDragHandle'),add=row.locator('.taskAddBtn'),detail=row.locator('.taskDetailOpenBtn'),before={drag:await rect(drag),add:await rect(add),detail:await rect(detail),title:await rect(row.locator('.titleText'))};expect(before).toMatchObject({drag:{width:16,height:22},add:{width:20,height:22},detail:{width:18,height:22}});expect(before.add.x).toBe(before.drag.x+before.drag.width+3);expect(before.detail.x).toBe(before.add.x+before.add.width+3);await add.hover();await page.evaluate(()=>selectTask('ROOT'));await add.focus();await page.waitForTimeout(150);expect({drag:await rect(drag),add:await rect(add),detail:await rect(detail),title:await rect(row.locator('.titleText'))}).toEqual(before)}
});
