const {test,expect}=require('playwright/test');
const {APP}=require('./helpers/app-target');
function task(id,extra={}){return{id,parentId:'',title:id,state:'',owner:'',due:'2026-08-28',planned_duration_days:5,summary:'',repeat:'',completed:false,dependencies:[],sortOrder:1000,...extra}}
async function boot(page,items,mode='personal'){await page.goto(APP);await page.evaluate(()=>localStorage.clear());await page.reload();await page.evaluate(({items,mode})=>{applyJsonObject({schema_version:'2.2',items},'Follow-up 2','followup2.json',null,{remember:false,writePermissionGranted:false});setView('all');setMode(mode);clearUndoHistory('followup2');dirty=false},{items,mode})}
function row(page,id){return page.locator(`#ganttView .ganttRow[data-task-id="${id}"],#row_${id}`).first()}
function pane(page){return page.locator('#taskDetailPane')}
async function open(page,id){await row(page,id).locator('.taskDetailOpenBtn').click();await expect(pane(page)).toBeVisible()}
async function settle(page){await page.evaluate(()=>new Promise(r=>queueMicrotask(r)))}

for(const width of [1920,1600,1366,1200,1100,1000,900])test(`DETAIL-BF2-WIDTH-${width} right-only pane preserves main-list visibility`,async({page})=>{
  await page.setViewportSize({width,height:760});await boot(page,[task('A'),task('B',{sortOrder:2000})]);await open(page,'A');const g=await pane(page).evaluate(el=>{const r=el.getBoundingClientRect(),schedule=getComputedStyle(el.querySelector('.taskDetailSchedule')),relation=getComputedStyle(el.querySelector('.taskDetailRelationRow'));return{width:r.width,left:r.left,right:r.right,position:getComputedStyle(el).position,scheduleCols:schedule.gridTemplateColumns,relationCols:relation.gridTemplateColumns,overflow:getComputedStyle(el.querySelector('.taskDetailPaneBody')).overflowY}});
  expect(g.position).toBe('fixed');expect(g.right).toBeGreaterThan(width-20);expect(g.left).toBeGreaterThanOrEqual(width*.5);expect(g.width).toBeLessThan(width*.65);expect(g.overflow).toMatch(/auto|scroll/);if(width<=1100){expect(g.scheduleCols.split(' ').length).toBe(3);expect(g.relationCols.split(' ').length).toBe(2)}else{expect(g.scheduleCols.split(' ').length).toBe(4);expect(g.relationCols.split(' ').length).toBe(3)}
  expect(await page.evaluate(()=>({undo:undoStack.length,dirty,id:selectedTaskId,top:backToTopBtn.classList.contains('taskDetailSuppressed')}))).toEqual({undo:0,dirty:false,id:'A',top:true});await expect(pane(page).locator('.taskDetailPlacement,[data-place="bottom"]')).toHaveCount(0);
});

test('DETAIL-BF2-WIDTH-RESIZE resize is presentation-only and preserves Gantt scroll',async({page})=>{
  await page.setViewportSize({width:1366,height:760});await boot(page,[task('A'),task('B',{due:'2027-08-28',sortOrder:2000})],'team');await page.evaluate(()=>{setProjectView('gantt');setGanttTimelineScroll(320)});await open(page,'A');const before=await page.evaluate(()=>({data:JSON.stringify(data),undo:undoStack.length,dirty,id:selectedTaskId,x:ganttTimelineScrollLeft}));await page.setViewportSize({width:1000,height:760});await page.waitForTimeout(80);expect(await page.evaluate(()=>({data:JSON.stringify(data),undo:undoStack.length,dirty,id:selectedTaskId,x:ganttTimelineScrollLeft}))).toEqual(before)
});

test('DETAIL-BF2-UNDO-01 no-change and single-change sessions create zero/one entries',async({page})=>{
  await boot(page,[task('A')]);await open(page,'A');await pane(page).locator('.taskDetailPaneClose').click();expect(await page.evaluate(()=>({undo:undoStack.length,dirty}))).toEqual({undo:0,dirty:false});await open(page,'A');await pane(page).getByLabel('タイトル').fill('A1');await pane(page).getByLabel('タイトル').blur();await settle(page);await pane(page).locator('.taskDetailPaneClose').click();expect(await page.evaluate(()=>({undo:undoStack.length,action:undoStack[0]?.actionType,count:undoStack[0]?.detailActionCount}))).toEqual({undo:1,action:'task_detail_session',count:1})
});

test('DETAIL-BF2-UNDO-02 Title + Due + Owner coalesce; one Undo/Redo restores all',async({page})=>{
  await boot(page,[task('A',{owner:'田中'})]);await open(page,'A');await pane(page).getByLabel('タイトル').fill('役員会資料作成');await pane(page).getByLabel('タイトル').blur();await pane(page).getByRole('textbox',{name:'計画完了',exact:true}).fill('2026/08/30');await pane(page).getByRole('textbox',{name:'計画完了',exact:true}).press('Enter');await pane(page).getByLabel('担当').fill('佐藤');await pane(page).getByLabel('担当').blur();await settle(page);await pane(page).locator('.taskDetailPaneClose').click();expect(await page.evaluate(()=>({length:undoStack.length,count:undoStack[0].detailActionCount,action:undoStack[0].actionType}))).toEqual({length:1,count:3,action:'task_detail_session'});await page.evaluate(()=>performUndo());expect(await page.evaluate(()=>{const x=itemById('A');return{x:{title:x.title,due:x.due,owner:x.owner},redo:redoStack.length}})).toEqual({x:{title:'A',due:'2026-08-28',owner:'田中'},redo:1});await page.evaluate(()=>performRedo());expect(await page.evaluate(()=>{const x=itemById('A');return{x:{title:x.title,due:x.due,owner:x.owner},undo:undoStack.length}})).toEqual({x:{title:'役員会資料作成',due:'2026-08-30',owner:'佐藤'},undo:1})
});

test('DETAIL-BF2-UNDO-03 schedule, actual, status, summary and repeat share one group',async({page})=>{
  await boot(page,[task('A')]);await open(page,'A');await pane(page).getByRole('textbox',{name:'計画開始',exact:true}).fill('2026/08/26');await pane(page).getByRole('textbox',{name:'計画開始',exact:true}).press('Enter');await pane(page).getByRole('textbox',{name:'実績開始',exact:true}).fill('2026/08/25');await pane(page).getByRole('textbox',{name:'実績開始',exact:true}).press('Enter');await pane(page).getByLabel('ステータス').selectOption('進行中');await pane(page).getByLabel('概要').fill('詳細概要');await pane(page).getByLabel('概要').blur();await pane(page).getByLabel('繰返し').selectOption('毎日');await settle(page);expect(await page.evaluate(()=>({length:undoStack.length,count:undoStack[0].detailActionCount}))).toEqual({length:1,count:5});await page.keyboard.press('Control+z');expect(await page.evaluate(()=>{const x=itemById('A');return{days:x.planned_duration_days,start:x.actual_start,state:x.state,summary:x.summary,repeat:x.repeat,redo:redoStack.length}})).toEqual({days:5,start:undefined,state:'',summary:'',repeat:'',redo:1});await page.keyboard.press('Control+y');expect(await page.evaluate(()=>{const x=itemById('A');return{days:x.planned_duration_days,start:x.actual_start,state:x.state,summary:x.summary,repeat:x.repeat}})).toEqual({days:3,start:'2026-08-25',state:'進行中',summary:'詳細概要',repeat:'毎日'})
});

test('DETAIL-BF2-UNDO-04 mixed Due + Parent + dependency + Summary is one operation',async({page})=>{
  await boot(page,[task('P'),task('Q',{sortOrder:2000}),task('D',{sortOrder:3000}),task('A',{parentId:'P',sortOrder:4000})]);await open(page,'A');await pane(page).getByRole('textbox',{name:'計画完了',exact:true}).fill('2026/08/30');await pane(page).getByRole('textbox',{name:'計画完了',exact:true}).press('Enter');await pane(page).getByRole('button',{name:'親を変更'}).click();await page.evaluate(()=>selectParentCandidate('Q'));await pane(page).getByRole('button',{name:'変更'}).click();await pane(page).getByRole('button',{name:'＋ 前工程'}).click();await page.evaluate(()=>selectDependencyCandidate('D'));await pane(page).getByRole('button',{name:'追加'}).click();await pane(page).getByLabel('概要').fill('mixed');await pane(page).getByLabel('概要').blur();await settle(page);expect(await page.evaluate(()=>({length:undoStack.length,count:undoStack[0].detailActionCount}))).toEqual({length:1,count:4});await pane(page).locator('.taskDetailPaneClose').click();await page.evaluate(()=>performUndo());expect(await page.evaluate(()=>{const x=itemById('A');return{due:x.due,parent:x.parentId,deps:x.dependencies,summary:x.summary}})).toEqual({due:'2026-08-28',parent:'P',deps:[],summary:''});await page.evaluate(()=>performRedo());expect(await page.evaluate(()=>{const x=itemById('A');return{due:x.due,parent:x.parentId,deps:x.dependencies,summary:x.summary}})).toEqual({due:'2026-08-30',parent:'Q',deps:[{task_id:'D',type:'finish_to_start'}],summary:'mixed'})
});

test('DETAIL-BF2-UNDO-05 dependency add/type/delete coalesce and candidate navigation does not',async({page})=>{
  await boot(page,[task('A'),task('D',{sortOrder:2000})]);await open(page,'A');await pane(page).getByRole('button',{name:'＋ 前工程'}).click();await page.keyboard.press('Alt+s');await page.locator('#taskSearchInput').fill('D');await page.locator('.taskSearchResult').filter({hasText:'D'}).click();expect(await page.evaluate(()=>undoStack.length)).toBe(0);await row(page,'D').locator('.titleText').click();expect(await page.evaluate(()=>undoStack.length)).toBe(0);await pane(page).getByRole('button',{name:'追加'}).click();await pane(page).locator('.taskDetailRelationControls').getByRole('button',{name:'変更'}).click();await pane(page).locator('.taskDetailDepSelect').selectOption('finish_to_finish');await pane(page).getByRole('button',{name:'変更',exact:true}).click();await pane(page).locator('.taskDetailRelationControls').getByRole('button',{name:'削除'}).click();await settle(page);expect(await page.evaluate(()=>({length:undoStack.length,count:undoStack[0].detailActionCount,deps:itemById('A').dependencies}))).toEqual({length:1,count:3,deps:[]});await page.evaluate(()=>performUndo());expect(await page.evaluate(()=>itemById('A').dependencies)).toEqual([])
});

test('DETAIL-BF2-UNDO-06 A to B switch finalizes separate chronological groups',async({page})=>{
  await boot(page,[task('A'),task('B',{sortOrder:2000})]);await open(page,'A');await pane(page).getByLabel('タイトル').fill('A1');await pane(page).getByLabel('タイトル').blur();await settle(page);await page.evaluate(()=>{document.activeElement?.blur();hqa21SelectWithoutRender('B')});await pane(page).getByLabel('担当').fill('B-owner');await pane(page).getByLabel('担当').blur();await settle(page);expect(await page.evaluate(()=>undoStack.map(x=>({id:x.taskId,count:x.detailActionCount})))).toEqual([{id:'A',count:1},{id:'B',count:1}]);await pane(page).locator('.taskDetailPaneClose').click();await page.evaluate(()=>performUndo());expect(await page.evaluate(()=>({a:itemById('A').title,b:itemById('B').owner}))).toEqual({a:'A1',b:''});await page.evaluate(()=>performUndo());expect(await page.evaluate(()=>itemById('A').title)).toBe('A')
});

test('DETAIL-BF2-UNDO-07 external main-list edits split groups and are never absorbed',async({page})=>{
  await boot(page,[task('A'),task('B',{sortOrder:2000})]);await open(page,'A');await pane(page).getByLabel('タイトル').fill('A1');await pane(page).getByLabel('タイトル').blur();await settle(page);const bTitle=row(page,'B').locator('.titleText');await bTitle.fill('B-outside');await bTitle.blur();await settle(page);await pane(page).getByRole('textbox',{name:'計画完了',exact:true}).fill('2026/08/30');await pane(page).getByRole('textbox',{name:'計画完了',exact:true}).press('Enter');await settle(page);expect(await page.evaluate(()=>undoStack.map(x=>({origin:x.origin||'',task:x.taskId,action:x.actionType})))).toEqual([{origin:'task_detail',task:'A',action:'task_detail_session'},{origin:'',task:'B',action:'edit_title'},{origin:'task_detail',task:'A',action:'task_detail_session'}]);await page.evaluate(()=>performUndo());expect(await page.evaluate(()=>({a:itemById('A').title,due:itemById('A').due,b:itemById('B').title}))).toEqual({a:'A1',due:'2026-08-28',b:'B-outside'});await page.evaluate(()=>performUndo());expect(await page.evaluate(()=>({a:itemById('A').title,b:itemById('B').title}))).toEqual({a:'A1',b:'B'});await page.evaluate(()=>performUndo());expect(await page.evaluate(()=>itemById('A').title)).toBe('A')
});

test('DETAIL-BF2-UNDO-08 mode switch same base does not end active group',async({page})=>{
  await boot(page,[task('A')]);await open(page,'A');await pane(page).getByLabel('タイトル').fill('A1');await pane(page).getByLabel('タイトル').blur();await settle(page);await page.evaluate(()=>setMode('team'));await pane(page).getByLabel('担当').fill('Owner');await pane(page).getByLabel('担当').blur();await settle(page);expect(await page.evaluate(()=>({length:undoStack.length,count:undoStack[0].detailActionCount,id:taskDetailPaneTaskId}))).toEqual({length:1,count:2,id:'A'})
});
