const {test,expect}=require('playwright/test');
const {APP}=require('./helpers/app-target');
const task=(id,extra={})=>({id,parentId:'',state:'未着手',impact:'',title:id,owner:'担当',due:'2026-08-20',planned_duration_days:3,summary:'',repeat:'',completed:false,source:'',asana_task_id:'',history:[],dependencies:[],sortOrder:1000,...extra});
async function fresh(page,items,modeName='team'){await page.setViewportSize({width:1000,height:560});await page.goto(APP);await page.evaluate(()=>localStorage.clear());await page.reload();await expect(page.locator('body')).not.toHaveClass(/dbBooting/);await page.evaluate(xs=>applyJsonObject({schema_version:'1.8',items:xs},'hqa21','hqa21.json',null,{remember:false,writePermissionGranted:false}),items);await page.evaluate(m=>setMode(m),modeName);if(modeName==='team')await expect(page.locator('#ganttView')).toBeVisible();await page.waitForTimeout(80)}

test('HQA2.1 timeline waits for usable geometry, reaches actual today-7, and preserves same-DB scroll',async({page})=>{await fresh(page,[task('old',{due:'2016-01-01'}),task('future',{due:'2030-01-01'})]);await expect.poll(()=>page.evaluate(()=>hqa2TimelineInitialized)).toBe(true);const initial=await page.evaluate(()=>{const g=hqa21TimelineGeometry(),first=(calendarDateToDay(ymd())-7-g.renderedMin)*GANTT_DAY_WIDTH;return{actual:ganttTimelineScrollLeft,target:first,min:g.renderedMin,old:calendarDateToDay('2016-01-01'),visibleDate:calendarDayToDate(g.renderedMin+Math.round(ganttTimelineScrollLeft/GANTT_DAY_WIDTH))}});expect(Math.abs(initial.actual-initial.target)).toBeLessThanOrEqual(2);expect(initial.visibleDate).toBe(await page.evaluate(()=>calendarDayToDate(calendarDateToDay(ymd())-7)));expect(initial.min).toBeLessThan(initial.old);await page.evaluate(()=>setGanttTimelineScroll(ganttTimelineScrollLeft+137));const user=await page.evaluate(()=>ganttTimelineScrollLeft);await page.evaluate(()=>render());await page.evaluate(()=>setMode('personal'));await page.evaluate(()=>setMode('team'));await expect.poll(()=>page.evaluate(()=>ganttTimelineScrollLeft)).toBe(user)});

test('HQA2.1 geometry-not-ready does not complete and retry later succeeds',async({page})=>{await fresh(page,[task('old',{due:'2016-01-01'}),task('future',{due:'2030-01-01'})]);await page.evaluate(()=>{hqa21CancelTimelineInitialization();hqa2TimelineInitialized=false;const clip=document.querySelector('.ganttHeader .ganttTimelineClip');window.__oldClipWidth=Object.getOwnPropertyDescriptor(HTMLElement.prototype,'clientWidth');Object.defineProperty(clip,'clientWidth',{configurable:true,value:0});hqa2InitializeTimeline()});await page.waitForTimeout(35);expect(await page.evaluate(()=>hqa2TimelineInitialized)).toBe(false);await page.evaluate(()=>{const clip=document.querySelector('.ganttHeader .ganttTimelineClip');delete clip.clientWidth});await expect.poll(()=>page.evaluate(()=>hqa2TimelineInitialized)).toBe(true)});

test('HQA2.1 different DB identity resets timeline initialization',async({page})=>{await fresh(page,[task('a',{due:'2016-01-01'}),task('b',{due:'2030-01-01'})]);await page.evaluate(()=>setGanttTimelineScroll(ganttTimelineScrollLeft+181));const old=await page.evaluate(()=>ganttTimelineScrollLeft);await page.evaluate(xs=>applyJsonObject({schema_version:'1.8',items:xs},'other','other.json',{name:'other.json'},{remember:false,writePermissionGranted:false}),[task('c',{due:'2015-01-01'}),task('d',{due:'2031-01-01'})]);await expect.poll(()=>page.evaluate(()=>hqa2TimelineInitialized)).toBe(true);const next=await page.evaluate(()=>({scroll:ganttTimelineScrollLeft,target:hqa21TimelineGeometry().target}));expect(Math.abs(next.scroll-next.target)).toBeLessThanOrEqual(2);expect(next.scroll).not.toBe(old)});

test('HQA2.1 Arrow navigation follows rendered ToDo hierarchy order without wrap or mutation',async({page})=>{await fresh(page,[task('p',{due:'2026-08-01',sortOrder:1000}),task('c',{parentId:'p',due:'2026-08-02',sortOrder:1000}),task('z',{due:'2026-08-03',sortOrder:2000})],'personal');await page.evaluate(()=>selectTask('p'));const before=await page.evaluate(()=>({dirty,undo:undoStack.length}));await page.keyboard.press('ArrowDown');expect(await page.evaluate(()=>selectedTaskId)).toBe('c');await page.keyboard.press('ArrowDown');expect(await page.evaluate(()=>selectedTaskId)).toBe('z');await page.keyboard.press('ArrowDown');expect(await page.evaluate(()=>selectedTaskId)).toBe('z');await page.keyboard.press('ArrowUp');expect(await page.evaluate(()=>selectedTaskId)).toBe('c');expect(await page.evaluate(()=>({dirty,undo:undoStack.length}))).toEqual(before)});

test('HQA2.1 Arrow navigation in Project is vertical-only and reveals offscreen rows',async({page})=>{const items=Array.from({length:70},(_,i)=>task(String(i),{due:`2026-08-${String(1+i%28).padStart(2,'0')}`,sortOrder:i*1000}));await fresh(page,items);await page.evaluate(()=>{selectedTaskId='0';selectGanttTaskWithoutRender('0');document.getElementById('ganttView').scrollLeft=120;projectOuterScrollLeft=120;setGanttTimelineScroll(250)});const before=await page.evaluate(()=>({outer:document.getElementById('ganttView').scrollLeft,timeline:ganttTimelineScrollLeft,dirty,undo:undoStack.length}));for(let i=0;i<35;i++)await page.keyboard.press('ArrowDown');const after=await page.evaluate(()=>{const row=renderedTaskRow(selectedTaskId),r=row.getBoundingClientRect();return{outer:document.getElementById('ganttView').scrollLeft,timeline:ganttTimelineScrollLeft,dirty,undo:undoStack.length,visible:r.bottom>0&&r.top<innerHeight,selected:selectedTaskId}});expect(after).toMatchObject({...before,visible:true});expect(after.selected).not.toBe('0')});

test('HQA2.1 Arrow navigation honors editor, modal, search, and IME guards',async({page})=>{await fresh(page,[task('a',{sortOrder:1000}),task('b',{sortOrder:2000})],'personal');await page.evaluate(()=>selectTask('a'));for(const tag of ['input','textarea','select','button']){await page.evaluate(t=>{const el=document.createElement(t);el.id='guardTarget';document.body.appendChild(el);el.focus()},tag);await page.keyboard.press('ArrowDown');expect(await page.evaluate(()=>selectedTaskId)).toBe('a');await page.evaluate(()=>document.getElementById('guardTarget').remove())}await page.locator('#b_title').focus();await page.locator('#b_title').dispatchEvent('compositionstart');await page.locator('#b_title').dispatchEvent('keydown',{key:'ArrowDown',isComposing:true,keyCode:229});expect(await page.evaluate(()=>selectedTaskId)).toBe('a');await page.locator('#b_title').dispatchEvent('compositionend');await page.evaluate(()=>{taskSearchPopup.style.display='block';document.body.tabIndex=-1;document.body.focus()});await page.keyboard.press('ArrowDown');expect(await page.evaluate(()=>selectedTaskId)).toBe('a');await page.evaluate(()=>{taskSearchPopup.style.display='none';const back=document.createElement('div');back.className='askBack';document.body.appendChild(back);document.body.focus()});await page.keyboard.press('ArrowDown');expect(await page.evaluate(()=>selectedTaskId)).toBe('a')});

test('HQA2.1 FS and FF conflict clicks navigate successor, highlight, message, and preserve outer scroll',async({page})=>{const items=[task('A',{due:'2026-08-20',planned_duration_days:5,sortOrder:1000}),task('B',{due:'2026-08-18',planned_duration_days:2,dependencies:[{task_id:'A',type:'finish_to_start'}],sortOrder:2000}),task('C',{due:'2026-08-19',planned_duration_days:2,dependencies:[{task_id:'A',type:'finish_to_finish'}],sortOrder:3000})];await fresh(page,items);expect(await page.locator('.ganttConflictItem')).toHaveCount(2);const outerBefore=await page.evaluate(()=>{projectWidths.title=1400;applyUnifiedProjectWidths();const host=document.getElementById('ganttView');host.scrollLeft=90;projectOuterScrollLeft=host.scrollLeft;window.__alerts=0;window.alert=()=>window.__alerts++;return host.scrollLeft});await page.evaluate(()=>document.querySelectorAll('.ganttConflictItem')[0].click());await expect(page.locator('.ganttRow[data-task-id="B"]')).toHaveClass(/ganttSelected/);await expect(page.locator('.ganttRow[data-task-id="B"]')).toHaveClass(/conflictAttention/);await expect(page.locator('#toast')).toContainText('翌日以降に開始');expect(await page.evaluate(()=>({outer:document.getElementById('ganttView').scrollLeft,alerts:window.__alerts}))).toEqual({outer:outerBefore,alerts:0});const stable=await page.evaluate(()=>ganttTimelineScrollLeft);await page.evaluate(()=>document.querySelectorAll('.ganttConflictItem')[1].click());await expect(page.locator('.ganttRow[data-task-id="C"]')).toHaveClass(/ganttSelected/);await expect(page.locator('#toast')).toContainText('完了日以降');expect(await page.evaluate(()=>window.__alerts)).toBe(0);expect(await page.evaluate(()=>ganttTimelineScrollLeft)).toBe(stable);await page.evaluate(()=>document.querySelector('.ganttRow[data-task-id="B"] .ganttWarn').click());await expect(page.locator('.ganttRow[data-task-id="B"]')).toHaveClass(/ganttSelected/)});

test('HQA2.1 parent conflict navigates parent; hidden target keeps filters and explains non-modally',async({page})=>{const items=[task('P',{due:'2026-08-20',planned_duration_days:10,state:'未着手'}),task('C',{parentId:'P',due:'2026-08-25',planned_duration_days:20,state:'進行中'})];await fresh(page,items);const parentIndex=await page.evaluate(()=>allGanttConflicts().findIndex(c=>c.kind==='parent'));expect(parentIndex).toBeGreaterThanOrEqual(0);await page.evaluate(i=>showGanttConflict(i),parentIndex);await expect(page.locator('.ganttRow[data-task-id="P"]')).toHaveClass(/ganttSelected/);await expect(page.locator('#toast')).toContainText('子孫の日程が親計画の範囲外');await page.evaluate(()=>{view='done';filterStates=new Set(['進行中']);render()});const before=await page.evaluate(()=>({view,filters:Array.from(filterStates)}));await page.evaluate(i=>showGanttConflict(i),parentIndex);expect(await page.evaluate(()=>({view,filters:Array.from(filterStates)}))).toEqual(before);await expect(page.locator('#toast')).toContainText('現在の表示条件では非表示')});

test('HQA2.1 visual states at 1680x900',async({page})=>{await page.setViewportSize({width:1680,height:900});const items=[task('old',{title:'10年前の履歴',due:'2016-01-01',sortOrder:100}),task('A',{title:'先行タスク A',due:'2026-08-20',planned_duration_days:5,sortOrder:200}),task('B',{title:'後続タスク B',due:'2026-08-18',planned_duration_days:2,dependencies:[{task_id:'A',type:'finish_to_start'}],sortOrder:300}),task('P',{title:'親計画',due:'2026-08-25',planned_duration_days:10,sortOrder:400}),task('C',{title:'範囲外の子',parentId:'P',due:'2026-08-30',planned_duration_days:25,sortOrder:100})];await fresh(page,items);await page.setViewportSize({width:1680,height:900});await expect.poll(()=>page.evaluate(()=>hqa2TimelineInitialized)).toBe(true);await page.screenshot({path:'test-results/hqa21-first-project-today-minus-7.png'});await page.evaluate(()=>{selectedTaskId='A';selectGanttTaskWithoutRender('A')});await page.keyboard.press('ArrowDown');await page.screenshot({path:'test-results/hqa21-arrow-down.png'});await page.keyboard.press('ArrowUp');await page.screenshot({path:'test-results/hqa21-arrow-up.png'});const indexes=await page.evaluate(()=>allGanttConflicts().map((c,i)=>({i,kind:c.kind,type:c.type})));await page.evaluate(i=>showGanttConflict(i),indexes.find(x=>x.type==='finish_to_start').i);await page.screenshot({path:'test-results/hqa21-fs-conflict.png'});await page.evaluate(i=>showGanttConflict(i),indexes.find(x=>x.kind==='parent').i);await page.screenshot({path:'test-results/hqa21-parent-conflict.png'})});
