const {test,expect}=require('playwright/test');
const {APP}=require('./helpers/app-target');
const task=(id,title=id,extra={})=>({id,parentId:'',state:'',impact:'',title,owner:'',due:'',summary:'',repeat:'',completed:false,source:'',asana_task_id:'',history:[],dependencies:[],sortOrder:1000,...extra});
async function boot(page){await page.goto(APP);await page.evaluate(()=>localStorage.clear());await page.reload()}
async function setData(page,items){await page.evaluate(items=>applyJsonObject({schema_version:'1.8',items},'test','ux3.json',null,{remember:false,writePermissionGranted:false}),items)}
async function show(page,items){await setData(page,items);await page.evaluate(()=>setMode('team'));await expect(page.locator('#ganttView')).toBeVisible()}
async function drag(page,locator,days){await locator.scrollIntoViewIfNeeded();const b=await locator.boundingBox();if(!b)throw new Error('drag target missing');await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.down();await page.mouse.move(b.x+b.width/2+days*28,b.y+b.height/2,{steps:6});await page.mouse.up()}
test.beforeEach(async({page})=>boot(page));

test('UX4-ACTUAL-STATE-01: ガント状態変更でsystem実績点と進行線を即時描画',async({page})=>{
  await page.evaluate(()=>setView('all'));
  await show(page,[task('route','状態変更',{state:'未着手',due:'2026-08-20',planned_duration_days:5})]);const today=await page.evaluate(()=>ymd()),row=page.locator('.ganttRow[data-task-id="route"]');await row.locator('.ganttState select').selectOption('進行中');expect(await page.evaluate(()=>itemById('route'))).toMatchObject({actual_start:today,actual_start_source:'system'});await expect(row.locator('.actualLine.running')).toBeVisible();await expect(row.locator('.actualDot.start')).toHaveClass(/system/);await expect(row.locator('.actualDot.start')).toHaveCSS('background-color','rgb(255, 255, 255)');await row.locator('.ganttState select').selectOption('完了');expect(await page.evaluate(()=>itemById('route'))).toMatchObject({actual_end:today,actual_end_source:'system'});await expect(row.locator('.actualSameDay .actualDot.start')).toHaveClass(/system/);await expect(row.locator('.actualSameDay .actualDot.end')).toHaveClass(/system/);await expect(row.locator('.actualSameDay .actualDot.end')).toHaveCSS('background-color','rgb(255, 255, 255)');
});

test('UX3-SOURCE-01: start/endのsystem/userを独立表示し保留は紫・中止は灰色',async({page})=>{
  const a={actual_start:'2026-08-10',actual_start_source:'system',actual_end:'2026-08-12',actual_end_source:'user'};await show(page,[task('normal','通常',{state:'完了',...a}),task('hold','保留',{state:'保留',...a}),task('cancel','中止',{state:'中止',...a}),task('same','同日',{state:'完了',actual_start:'2026-08-10',actual_start_source:'system',actual_end:'2026-08-10',actual_end_source:'user'})]);
  for(const id of ['normal','hold','cancel','same']){await expect(page.locator(`.ganttRow[data-task-id="${id}"] .actualDot.start`)).toHaveClass(/system/);await expect(page.locator(`.ganttRow[data-task-id="${id}"] .actualDot.end`)).toHaveClass(/user/)}await expect(page.locator('.ganttRow[data-task-id="normal"] .actualLine')).toHaveAttribute('data-gantt-tip',/自動設定[\s\S]*手動設定/);const colors=await page.evaluate(()=>({hold:getComputedStyle(document.querySelector('.ganttRow[data-task-id="hold"] .actualLine')).backgroundColor,cancel:getComputedStyle(document.querySelector('.ganttRow[data-task-id="cancel"] .actualLine')).backgroundColor,holdSystem:getComputedStyle(document.querySelector('.ganttRow[data-task-id="hold"] .actualDot.start')).backgroundColor,holdUser:getComputedStyle(document.querySelector('.ganttRow[data-task-id="hold"] .actualDot.end')).backgroundColor}));expect(colors.hold).not.toBe(colors.cancel);expect(colors.holdSystem).toBe('rgb(255, 255, 255)');expect(colors.holdUser).not.toBe('rgb(255, 255, 255)');
});

test('UX3-SAME-DAY-01: 同日実績の開始・終了handleを独立dragして期間を伸長',async({page})=>{
  await show(page,[task('left','左',{state:'完了',actual_start:'2026-09-10',actual_start_source:'system',actual_end:'2026-09-10',actual_end_source:'system'}),task('right','右',{state:'完了',actual_start:'2026-09-10',actual_start_source:'system',actual_end:'2026-09-10',actual_end_source:'system'})]);for(const id of ['left','right']){const dots=page.locator(`.ganttRow[data-task-id="${id}"] .actualSameDay .actualDot`);await expect(dots).toHaveCount(2);const boxes=await dots.evaluateAll(es=>es.map(e=>e.getBoundingClientRect().x));expect(boxes[1]-boxes[0]).toBeGreaterThan(5)}await drag(page,page.locator('.ganttRow[data-task-id="left"] .actualDot.start'),-1);expect(await page.evaluate(()=>itemById('left'))).toMatchObject({actual_start:'2026-09-09',actual_end:'2026-09-10',actual_start_source:'user',actual_end_source:'system'});await drag(page,page.locator('.ganttRow[data-task-id="right"] .actualDot.end'),2);expect(await page.evaluate(()=>itemById('right'))).toMatchObject({actual_start:'2026-09-10',actual_end:'2026-09-12',actual_start_source:'system',actual_end_source:'user'});
});

test('UX3-DUE-01: ガント期限は共通validation・d0・calendar経路で安全に更新',async({page})=>{
  await show(page,[task('due','期限',{due:'2026-08-20',planned_duration_days:2})]);await page.locator('.ganttRow[data-task-id="due"] .ganttDue').click();let input=page.locator('.ganttRow[data-task-id="due"] .ganttDueText');await expect(input).toBeFocused();await expect(page.locator('.ganttRow[data-task-id="due"] .calBtn')).toBeVisible();await expect(page.locator('.ganttRow[data-task-id="due"] .calBtn')).toHaveCSS('pointer-events','auto');await input.fill('804/1/1');let action=input.press('Enter'),dialog=await page.waitForEvent('dialog');expect(dialog.message()).toContain('日付は');await dialog.accept();await action;expect(await page.evaluate(()=>itemById('due').due)).toBe('2026-08-20');
  await input.fill('途中');action=input.press('Enter');dialog=await page.waitForEvent('dialog');await dialog.accept();await action;expect(await page.evaluate(()=>itemById('due').due)).toBe('2026-08-20');await input.fill('');await input.press('d');await input.press('0');expect(await page.evaluate(()=>itemById('due').due)).toBe(await page.evaluate(()=>ymd()));await expect(page.locator('.ganttRow[data-task-id="due"] .ganttDueText')).toBeHidden();
  await page.locator('.ganttRow[data-task-id="due"] .ganttDue').click();await page.locator('.ganttRow[data-task-id="due"] .ganttDueCalendar').evaluate(el=>{el.value='2026-08-25';el.dispatchEvent(new Event('change',{bubbles:true}))});expect(await page.evaluate(()=>itemById('due').due)).toBe('2026-08-25');
});

test('UX3-SPINNER-01: 計画日数spinner操作中は編集を維持しEnterで確定',async({page})=>{
  await show(page,[task('plan','計画',{due:'2026-08-20',planned_duration_days:365})]);const cell=page.locator('.ganttRow[data-task-id="plan"] .ganttPlanned');await cell.click();const input=cell.locator('input');expect((await input.boundingBox()).width).toBeGreaterThanOrEqual(40);await expect(input).toHaveValue('365');await input.press('ArrowUp');await expect(input).toBeFocused();await expect(input).toHaveValue('366');await input.dispatchEvent('click');await expect(input).toBeFocused();await input.press('ArrowUp');await expect(input).toHaveValue('367');await expect(input).toBeFocused();expect(await page.evaluate(()=>itemById('plan').planned_duration_days)).toBe(365);expect(await cell.evaluate(el=>getComputedStyle(el).textAlign)).toBe('right');expect(await input.evaluate(el=>getComputedStyle(el).textAlign)).toBe('right');await input.press('Enter');expect(await page.evaluate(()=>itemById('plan').planned_duration_days)).toBe(367);await expect(input).not.toBeFocused();
});

test('UX3-COL-RESIZE-01: 統合Project情報列をpointer resizeし行と同期、日幅は不変',async({page})=>{
  await show(page,[task('row','担当者名が長い',{state:'進行中',owner:'非常に長い担当者名',due:'2026-08-20',planned_duration_days:5}),task('wide','長期幅',{due:'2028-12-31',planned_duration_days:900,sortOrder:2000})]);
  const dayWidth=await page.evaluate(()=>GANTT_DAY_WIDTH),before=await page.locator('.ganttHeader th[data-c="title"]').boundingBox();
  await page.evaluate(()=>{projectWidths.title+=28;applyUnifiedProjectWidths()});
  const after=await page.locator('.ganttHeader th[data-c="title"]').boundingBox();expect(after.width).toBeGreaterThan(before.width);expect(await page.evaluate(()=>GANTT_DAY_WIDTH)).toBe(dayWidth);
  const aligned=await page.evaluate(()=>document.querySelector('.ganttHeader .projectInfoTable').getBoundingClientRect().width===document.querySelector('.ganttRow[data-task-id="row"] .projectInfoTable').getBoundingClientRect().width);expect(aligned).toBe(true);
  await expect(page.locator('.ganttRow[data-task-id="row"] .ganttOwner input')).toHaveValue('非常に長い担当者名');await page.evaluate(()=>setGanttTimelineScroll(500));await drag(page,page.locator('.ganttBar[data-task-id="row"]'),1);expect(await page.evaluate(()=>itemById('row').due)).toBe('2026-08-21');
});

test('UX3-SCROLL-01: ガント中段でも固定横スクロールを利用でき双方向同期',async({page})=>{
  const items=Array.from({length:100},(_,i)=>task('long'+i,'長期'+i,{due:'2028-12-31',planned_duration_days:900,sortOrder:(i+1)*1000}));await show(page,items);await page.locator('.ganttRow[data-task-id="long50"]').scrollIntoViewIfNeeded();const dock=page.locator('.ganttScrollDock');await expect(dock).toHaveCount(1);expect(await dock.evaluate(el=>getComputedStyle(el).position)).toBe('fixed');const fixed=await Promise.all(['.ganttTaskName','.ganttState','.ganttOwner','.ganttPlanned','.ganttDue'].map(s=>page.locator('.ganttRow[data-task-id="long50"] '+s).boundingBox()));const scrollBefore=await page.evaluate(()=>ganttTimelineScrollLeft),target=scrollBefore>250?scrollBefore-200:scrollBefore+200,dateBefore=await page.locator('.ganttHeader .ganttDate').first().boundingBox(),barBefore=await page.locator('.ganttBar[data-task-id="long50"]').boundingBox();await page.evaluate(value=>setGanttTimelineScroll(value),target);const scrollAfter=await page.evaluate(()=>ganttTimelineScrollLeft),screenDelta=scrollBefore-scrollAfter;expect(Math.abs(scrollAfter-target)).toBeLessThan(2);const afterFixed=await Promise.all(['.ganttTaskName','.ganttState','.ganttOwner','.ganttPlanned','.ganttDue'].map(s=>page.locator('.ganttRow[data-task-id="long50"] '+s).boundingBox()));afterFixed.forEach((b,i)=>expect(Math.abs(b.x-fixed[i].x)).toBeLessThan(1));const dateAfter=await page.locator('.ganttHeader .ganttDate').first().boundingBox(),barAfter=await page.locator('.ganttBar[data-task-id="long50"]').boundingBox();expect(Math.abs((dateAfter.x-dateBefore.x)-screenDelta)).toBeLessThan(2);expect(Math.abs((barAfter.x-barBefore.x)-screenDelta)).toBeLessThan(2);expect(Math.abs((dateAfter.x-dateBefore.x)-(barAfter.x-barBefore.x))).toBeLessThan(1);const rowBox=await page.locator('.ganttRow[data-task-id="long50"]').boundingBox(),leftBox=await page.locator('.ganttRow[data-task-id="long50"] .ganttTaskName').boundingBox(),timelineBox=await page.locator('.ganttRow[data-task-id="long50"] .ganttTimelineClip').boundingBox();expect(Math.abs(leftBox.y-rowBox.y)).toBeLessThan(1);expect(Math.abs(timelineBox.y-rowBox.y)).toBeLessThan(1);await page.locator('.ganttRow[data-task-id="long75"]').scrollIntoViewIfNeeded();await expect(dock).toHaveCount(1);
});

test('UX4-ROW-SYNC-01: 親子孫の固定情報とtimelineを共通行高で縦同期',async({page})=>{
  await show(page,[task('p','親',{due:'2028-12-31',planned_duration_days:900}),task('c','子',{parentId:'p',due:'2028-12-30',planned_duration_days:800,sortOrder:2000}),task('g','孫',{parentId:'c',state:'完了',due:'2028-12-29',planned_duration_days:700,sortOrder:3000,actual_start:'2026-08-01',actual_end:'2026-08-02'})]);for(const id of ['p','c','g']){const pos=await page.locator(`.ganttRow[data-task-id="${id}"]`).evaluate(row=>{const l=row.querySelector('.ganttLeftPane').getBoundingClientRect(),r=row.querySelector('.ganttTimelineClip').getBoundingClientRect();return{ly:l.y,ry:r.y,lh:l.height,rh:r.height}});expect(Math.abs(pos.ly-pos.ry)).toBeLessThan(1);expect(Math.abs(pos.lh-pos.rh)).toBeLessThan(1)}
});

test('UX4-TODAY-LINE-01: 今日線がtimeline全高を貫き横scroll・列幅変更へ追従',async({page})=>{
  const today=await page.evaluate(()=>ymd()),items=Array.from({length:12},(_,i)=>task('today'+i,'今日'+i,{due:i===11?'2028-12-31':today,planned_duration_days:i===11?900:1,sortOrder:(i+1)*1000}));await show(page,items);await expect(page.locator('.ganttHeader .ganttToday')).toBeVisible();await expect(page.locator('.ganttRow .ganttToday')).toHaveCount(12);const overlay=page.locator('.ganttTodayOverlayClip'),line=page.locator('.ganttTodayColumn');await expect(line).toBeVisible();const canvasBox=await page.locator('.ganttCanvas').boundingBox(),overlayBox=await overlay.boundingBox(),lineBefore=await line.boundingBox(),dateBefore=await page.locator('.ganttHeader .ganttToday').boundingBox(),leftBefore=await page.locator('.ganttRow[data-task-id="today0"] .ganttTaskName').boundingBox(),scrollBefore=await page.evaluate(()=>ganttTimelineScrollLeft),target=scrollBefore>250?scrollBefore-200:scrollBefore+200;expect(overlayBox.height).toBeGreaterThan(12*28);expect(Math.abs((overlayBox.y+overlayBox.height)-(canvasBox.y+canvasBox.height))).toBeLessThan(2);const dock=page.locator('.ganttScrollDock');await expect(dock).toHaveCount(1);await page.evaluate(value=>setGanttTimelineScroll(value),target);const scrollAfter=await page.evaluate(()=>ganttTimelineScrollLeft),screenDelta=scrollBefore-scrollAfter,lineAfter=await line.boundingBox(),dateAfter=await page.locator('.ganttHeader .ganttToday').boundingBox(),leftAfter=await page.locator('.ganttRow[data-task-id="today0"] .ganttTaskName').boundingBox();expect(Math.abs(scrollAfter-target)).toBeLessThan(2);expect(Math.abs((lineAfter.x-lineBefore.x)-screenDelta)).toBeLessThan(2);expect(Math.abs((dateAfter.x-dateBefore.x)-screenDelta)).toBeLessThan(2);expect(Math.abs((lineAfter.x-lineBefore.x)-(dateAfter.x-dateBefore.x))).toBeLessThan(1);expect(Math.abs(leftAfter.x-leftBefore.x)).toBeLessThan(1);const relativeBefore=lineAfter.x-(await page.locator('.ganttHeader .ganttTimelineClip').boundingBox()).x;await page.evaluate(()=>{projectWidths.title+=28;applyUnifiedProjectWidths()});const relativeAfter=(await line.boundingBox()).x-(await page.locator('.ganttHeader .ganttTimelineClip').boundingBox()).x;expect(Math.abs(relativeAfter-relativeBefore)).toBeLessThan(2);
});

test('UX3-LIST-DUE-01: ガント専用期限超過表示を重複せず期限列を縮小',async({page})=>{
  await show(page,[task('l1','遅延1',{due:'2000-01-01'})]);await expect(page.locator('.ganttOverdueSummary')).toHaveCount(0);await page.evaluate(()=>setMode('team'));expect(await page.evaluate(()=>DEF.due)).toBe(88);await page.locator('#row_l1 .dueTxt').click();const layout=await page.locator('#row_l1 td').filter({has:page.locator('.dateEdit')}).evaluate(td=>{const input=td.querySelector('input[type=text]').getBoundingClientRect(),button=td.querySelector('.calBtn').getBoundingClientRect(),cell=td.getBoundingClientRect();return{inputWidth:input.width,inside:input.left>=cell.left&&button.right<=cell.right+1,buttonVisible:button.width>0&&button.height>0}});expect(layout.inputWidth).toBeLessThan(90);expect(layout.buttonVisible).toBe(true);expect(layout.inside).toBe(true);await page.locator('#row_l1 .calBtn').click();
});
