const {test,expect}=require('playwright/test');
const {installFsAccessMock}=require('./helpers/fs-access-mock');
const {APP}=require('./helpers/app-target');
const EMPTY_DB=APP.includes('v220_dev')||APP.includes('pbl002_')||APP.includes('v230')||APP.includes('v240')||APP.includes('task_detail_phase')?{schema_version:'2.2',workspace_info_markdown:'',items:[]}:{schema_version:'2.0',items:[]};
const task=(id,title=id,extra={})=>({id,parentId:'',state:'',impact:'',title,owner:'',due:'',summary:'',repeat:'',completed:false,source:'',asana_task_id:'',history:[],dependencies:[],sortOrder:1000,...extra});
const json=items=>JSON.stringify({schema_version:'1.8',items});
async function boot(page){await installFsAccessMock(page);await page.goto(APP);await page.evaluate(async()=>{localStorage.clear();if(indexedDB.databases)for(const db of await indexedDB.databases())indexedDB.deleteDatabase(db.name)});await page.reload();await expect(page.locator('#dbStartScreen')).toBeVisible()}
async function file(page,id,options={}){await page.evaluate(({id,options})=>__fsMock.create(id,options),{id,options})}
async function directory(page,id,options={}){await page.evaluate(({id,options})=>{__fsMock.createDirectory(id,options);__fsMock.queueDirectory(id)},{id,options})}
async function createdFileId(page,id){return page.evaluate(id=>__fsMock.directoryEntries(id)[0]?.[1],id)}
async function startNew(page,name,dirId,button='#startNewDbBtn'){await page.locator(button).click();await expect(page.locator('#newDbNameInput')).toBeFocused();await page.locator('#newDbNameInput').fill(name);await page.locator('#newDbNameNext').click();await expect(page.locator('.askMsg')).toContainText('次に、このDBを保存するフォルダを選択します');if(dirId)await page.locator('#newDbFolderNext').click();else await page.locator('#newDbFolderCancel').click()}
async function open(page,id){await page.evaluate(id=>__fsMock.queueOpen(id),id);const button=await page.locator('#dbStartScreen').isVisible()?page.locator('#startDbReadBtn'):page.locator('#dbReadBtn');await button.click();await expect(page.locator('#dbLoadingBack')).toBeHidden()}
async function state(page){return page.evaluate(()=>({loaded:dbDataLoaded,name:currentDbName,handle:currentDbHandle&&currentDbHandle.__mockId,items:data.items.map(x=>x.id),dirty,saveState,selected:selectedTaskId,undo:undoStack.length,redo:redoStack.length,recent:recentDbs.map(x=>x.name),timer:!!autoSaveTimer}))}

test.beforeEach(async({page})=>boot(page));

test('DBL-A: unloadedはstart screenだけで空・clean・編集不能',async({page})=>{
  await expect(page.locator('#dbStartScreen button:visible')).toHaveCount(2);await expect(page.locator('#startNewDbBtn')).toHaveText('新しいDBを始める');await expect(page.locator('#startDbReadBtn')).toHaveText('既存DB読込');
  const styles=await page.locator('#dbStartScreen button:visible').evaluateAll(buttons=>buttons.map(b=>{const s=getComputedStyle(b);return[s.backgroundColor,s.borderColor,s.color,s.fontWeight,s.boxShadow]}));expect(styles[0]).toEqual(styles[1]);expect(styles[0].slice(0,3)).toEqual(['rgb(255, 255, 255)','rgb(158, 182, 220)','rgb(36, 86, 166)']);
  for(const selector of ['.bar','#dbSaveBtn','#kpis','#listView','#ganttView','#projectViewControls','#copilotTab','.shortcutHelp'])await expect(page.locator(selector)).toBeHidden();
  expect(await state(page)).toEqual({loaded:false,name:'未読込',handle:null,items:[],dirty:false,saveState:'unloaded',selected:'',undo:0,redo:0,recent:[],timer:false});await page.keyboard.press('Control+z');await page.keyboard.press('Control+y');expect(await state(page)).toMatchObject({items:[],dirty:false,undo:0,redo:0});
});

test('DBL-B/C: unloaded New DBのCancelはno-op、成功後だけ空DBをadopt',async({page})=>{
  await page.evaluate(()=>{undoStack.push({sentinel:true});redoStack.push({sentinel:true})});await page.locator('#startNewDbBtn').click();await page.locator('#newDbNameCancel').click();expect(await state(page)).toMatchObject({loaded:false,items:[],dirty:false,undo:1,redo:1});
  await page.evaluate(()=>{mode='team';sortMode='date';view='done';projectView='gantt';filterStates.add('進行中')});await directory(page,'newdir');await startNew(page,'My Tasks','newdir');const newId=await createdFileId(page,'newdir'),newName=(await page.evaluate(id=>__fsMock.snapshot(id).name,newId));
expect(newName).toBe('My Tasks.json');expect(JSON.parse(await page.evaluate(id=>__fsMock.snapshot(id).text,newId))).toEqual(EMPTY_DB);expect(await state(page)).toEqual({loaded:true,name:newName,handle:newId,items:[],dirty:false,saveState:'saved',selected:'',undo:0,redo:0,recent:[newName],timer:false});await expect(page.locator('#dbSaveBtn')).toHaveText('現在DBのコピーを保存');expect(await page.evaluate(()=>({mode,sortMode,view,projectView,filters:[...filterStates],focused:document.activeElement?.id}))).toEqual({mode:'personal',sortMode:'tree',view:'open',projectView:'list',filters:[],focused:'b_title'});
});

test('DBL-D/E: loaded AからCancelは全状態維持、成功時だけ空Bへ切替',async({page})=>{
  await file(page,'a',{name:'a.json',text:json([task('A')])});await open(page,'a');await page.locator('#row_A').click();await page.evaluate(()=>chg(0,'owner','edited'));await page.waitForTimeout(0);const before=await state(page),diskA=await page.evaluate(()=>__fsMock.snapshot('a').text);await page.locator('#newDbBtn').click();await page.locator('#newDbNameCancel').click();expect(await state(page)).toEqual({...before,dirty:false,saveState:'saved',timer:false});expect(await page.evaluate(()=>__fsMock.snapshot('a').text)).not.toBe(diskA);
  await directory(page,'bdir');await startNew(page,'b','bdir','#newDbBtn');const b=await createdFileId(page,'bdir');await expect.poll(()=>page.evaluate(()=>currentDbName)).toBe('b.json');expect(JSON.parse(await page.evaluate(id=>__fsMock.snapshot(id).text,b))).toEqual(EMPTY_DB);expect(await state(page)).toMatchObject({loaded:true,handle:b,items:[],dirty:false,saveState:'saved',selected:'',undo:0,redo:0});
});

test('DBL-F: new DBはdirectory pickerだけを使いcurrent DBをstartInにする',async({page})=>{
  await file(page,'a',{name:'a.json',text:json([task('A')])});await open(page,'a');const before=await page.evaluate(()=>__fsMock.snapshot('a'));await page.locator('#newDbBtn').click();await page.locator('#newDbNameInput').fill('a');await page.locator('#newDbNameNext').click();await expect(page.locator('#newDbNameError')).toContainText('現在開いているDBと同じ名前');await expect(page.locator('#newDbNameInput')).toHaveValue('a');await page.locator('#newDbNameInput').fill('a.json');await page.locator('#newDbNameNext').click();await expect(page.locator('#newDbNameInput')).toHaveValue('a.json');expect((await page.evaluate(()=>__fsMock.calls())).some(c=>c.op==='showDirectoryPicker')).toBe(false);await page.locator('#newDbNameInput').fill('other');await page.locator('#newDbNameNext').click();await directory(page,'dest');await page.locator('#newDbFolderNext').click();const after=await page.evaluate(()=>__fsMock.snapshot('a')),calls=await page.evaluate(()=>__fsMock.calls());expect(after.text).toBe(before.text);expect(after.writeCount).toBe(before.writeCount);expect(calls.some(c=>c.op==='showSaveFilePicker')).toBe(false);expect(calls.find(c=>c.op==='showDirectoryPicker')).toMatchObject({startIn:'a'});expect(await page.evaluate(()=>typeof saveNewDbJson)).toBe('undefined');
});

test('DBL-F2: folder説明Cancelとfolder内同名は無変更、同じfolderで名前再入力',async({page})=>{
  await page.evaluate(()=>{undoStack.push({sentinel:true})});await startNew(page,'cancelled',null);expect(await state(page)).toMatchObject({loaded:false,items:[],undo:1});expect((await page.evaluate(()=>__fsMock.calls())).some(c=>c.op==='showDirectoryPicker')).toBe(false);
  await directory(page,'same');await page.evaluate(()=>__fsMock.addDirectoryFile('same','existing','Taken.json',{text:'DO NOT CHANGE'}));await page.locator('#startNewDbBtn').click();await page.locator('#newDbNameInput').fill('Taken');await page.locator('#newDbNameNext').click();await page.locator('#newDbFolderNext').click();await expect(page.locator('#newDbNameError')).toContainText('同じ名前のDB');await expect(page.locator('#newDbNameInput')).toHaveValue('Taken');expect(await page.evaluate(()=>__fsMock.snapshot('existing').text)).toBe('DO NOT CHANGE');expect(await page.evaluate(()=>__fsMock.directoryEntries('same').map(x=>x[0]))).toEqual(['Taken.json']);
  await page.locator('#newDbNameInput').fill('Fresh');await page.locator('#newDbNameNext').click();await expect(page.locator('#dbStartScreen')).toBeHidden();expect((await page.evaluate(()=>__fsMock.calls())).filter(c=>c.op==='showDirectoryPicker')).toHaveLength(1);expect(await page.evaluate(()=>__fsMock.directoryEntries('same').map(x=>x[0]))).toEqual(['Taken.json','Fresh.json']);expect(JSON.parse(await page.evaluate(()=>__fsMock.snapshot('same/Fresh.json').text))).toEqual(EMPTY_DB);
});

for(const loaded of [false,true])test(`DBL-G: New DB write failureは${loaded?'loaded A':'unloaded'}を維持`,async({page})=>{
  if(loaded){await file(page,'a',{name:'a.json',text:json([task('A')])});await open(page,'a');await page.locator('#row_A').click();await page.evaluate(()=>{chg(0,'owner','x')});await page.waitForTimeout(0)}else await page.evaluate(()=>{undoStack.push({sentinel:true});redoStack.push({sentinel:true})});const before=await state(page);await directory(page,'bad',{newFileOptions:{failWrite:true}});await startNew(page,'failure','bad',loaded?'#newDbBtn':'#startNewDbBtn');expect(await state(page)).toEqual(loaded?{...before,dirty:false,saveState:'saved',timer:false}:before);expect(await page.evaluate(()=>__fsMock.directoryEntries('bad'))).toEqual([]);
});

test('DBL-H/I/J: load Cancel、dirty direct-save、handleなしdirtyのswitch中止',async({page})=>{
  await page.locator('#startDbReadBtn').click();expect(await state(page)).toMatchObject({loaded:false,items:[],dirty:false,undo:0});
  await file(page,'a',{name:'a.json',text:json([task('A')])});await file(page,'b',{name:'b.json',text:json([task('B')])});await open(page,'a');await page.evaluate(()=>{chg(0,'title','A edited');__fsMock.queueOpen('b')});await page.locator('#dbReadBtn').click();await expect.poll(()=>state(page)).toMatchObject({loaded:true,name:'b.json',handle:'b',items:['B'],dirty:false,undo:0});const calls=await page.evaluate(()=>__fsMock.calls());expect(calls.some(x=>x.op==='write'&&x.id==='a')).toBe(true);expect(calls.some(x=>x.op==='showSaveFilePicker')).toBe(false);
  await page.evaluate(items=>applyJsonObject({schema_version:'1.8',items},'fallback','fallback.json',null,{remember:false,writePermissionGranted:false}),[task('F')]);await page.evaluate(()=>chg(0,'title','dirty fallback'));const openCallsBefore=(await page.evaluate(()=>__fsMock.calls())).filter(x=>x.op==='showOpenFilePicker').length;await page.locator('#dbReadBtn').click();expect(await state(page)).toMatchObject({loaded:true,name:'fallback.json',handle:null,items:['F'],dirty:true});expect((await page.evaluate(()=>__fsMock.calls())).filter(x=>x.op==='showOpenFilePicker')).toHaveLength(openCallsBefore);expect((await page.evaluate(()=>__fsMock.calls())).some(x=>x.op==='showSaveFilePicker')).toBe(false);
});

test('DBL-K/L: 新DBのtask追加は選択されBへautosave、copyはhistory維持',async({page})=>{
  await directory(page,'bdir');await startNew(page,'b','bdir');const b=await createdFileId(page,'bdir');await page.locator('#mTeam').click();await page.locator('#b_title').fill('Created');await page.locator('#b_title').press('Enter');await page.locator('#b_due').press('Enter');await page.locator('#b_planned').press('Enter');const id=await page.evaluate(()=>selectedTaskId);expect(id).toBeTruthy();await expect(page.locator(`#row_${id}`)).toHaveClass(/selectedRow/);await expect.poll(()=>page.evaluate(id=>JSON.parse(__fsMock.snapshot(id).text).items.length,b),{timeout:5000}).toBe(1);const history=await page.evaluate(()=>undoStack.length);await file(page,'copy',{name:'copy.json',text:''});await page.evaluate(()=>__fsMock.queueSave('copy'));await page.locator('#dbSaveBtn').click();expect(await page.evaluate(()=>undoStack.length)).toBe(history);expect(await state(page)).toMatchObject({handle:b});
});

test('DBL-M/N: startup restore成功は通常UI、失敗・permission promptはstart screen',async({page})=>{
  await file(page,'last',{name:'last.json',text:json([task('L')]),readPermission:'granted',writePermission:'granted'});await page.evaluate(()=>{const h=__fsMock.handle('last');getLastDbRecord=async()=>({name:'last.json',handle:h});window.__restore=restoreLastDbOnStartup()});await page.evaluate(()=>window.__restore);await expect(page.locator('#dbStartScreen')).toBeHidden();expect(await state(page)).toMatchObject({loaded:true,name:'last.json',items:['L']});
  await file(page,'bad',{name:'bad.json',text:'broken',readPermission:'granted'});await page.evaluate(()=>{const h=__fsMock.handle('bad');getLastDbRecord=async()=>({name:'bad.json',handle:h});window.__restore=restoreLastDbOnStartup()});await page.evaluate(()=>window.__restore);await expect(page.locator('#dbStartScreen')).toBeVisible();expect(await state(page)).toMatchObject({loaded:false,name:'bad.json',items:[],dirty:false,saveState:'resume'});
  await file(page,'prompt',{name:'prompt.json',text:json([task('P')]),readPermission:'prompt',writePermission:'prompt'});await page.evaluate(()=>{const h=__fsMock.handle('prompt');getLastDbRecord=async()=>({name:'prompt.json',handle:h});window.__restore=restoreLastDbOnStartup()});await page.evaluate(()=>window.__restore);await expect(page.locator('#dbStartScreen')).toBeVisible();await expect(page.getByRole('button',{name:'前回DBを再開'})).toHaveCount(1);expect(await state(page)).toMatchObject({loaded:false,name:'prompt.json',items:[],dirty:false,saveState:'resume'});
});

test('DBL-N2: booting中はstart screenを一度も表示せず復元後に直接loaded',async({page})=>{
  await file(page,'boot',{name:'boot.json',text:json([task('BOOT')]),readPermission:'granted',writePermission:'granted'});await page.evaluate(()=>{document.body.classList.add('dbBooting');window.__startSeen=false;let active=true;const watch=()=>{if(!active)return;const el=document.getElementById('dbStartScreen');if(el&&getComputedStyle(el).display!=='none')window.__startSeen=true;requestAnimationFrame(watch)};watch();const h=__fsMock.handle('boot');getLastDbRecord=async()=>{await new Promise(r=>setTimeout(r,60));return{name:'boot.json',handle:h}};window.__bootRestore=restoreLastDbOnStartup().finally(()=>active=false)});await page.evaluate(()=>window.__bootRestore);expect(await page.evaluate(()=>({seen:window.__startSeen,booting:document.body.classList.contains('dbBooting'),loaded:dbDataLoaded,ids:data.items.map(x=>x.id)}))).toEqual({seen:false,booting:false,loaded:true,ids:['BOOT']});
  await page.evaluate(()=>{document.body.classList.add('dbBooting');getLastDbRecord=async()=>null;window.__bootEmpty=restoreLastDbOnStartup()});await page.evaluate(()=>window.__bootEmpty);await expect(page.locator('#dbStartScreen')).toBeVisible();expect(await page.evaluate(()=>document.body.classList.contains('dbBooting'))).toBe(false);
});

test('DBL-O: 多数taskの末尾へ追加した期限なしtaskを実viewport内まで追従',async({page})=>{
  const items=Array.from({length:90},(_,i)=>task(`T${i}`,`Task ${i}`,{sortOrder:(i+1)*1000}));await file(page,'many',{name:'many.json',text:json(items)});await open(page,'many');await page.locator('#b_title').fill('No due added');await page.locator('#b_title').press('Enter');await page.locator('#b_due').press('Enter');const id=await page.evaluate(()=>selectedTaskId);await expect.poll(()=>page.evaluate(id=>{const row=document.getElementById('row_'+id);if(!row)return false;const r=row.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight},id),{timeout:3000}).toBe(true);await expect(page.locator(`#row_${id}`)).toContainText('No due added');
});
