const {test,expect}=require('playwright/test');
const {APP_FILE_URL:APP}=require('./helpers/app-target');
const task=(id,extra={})=>({id,parentId:'',state:'未着手',impact:'B-定期',title:`Task ${id}`,owner:'Owner',due:'2026-08-20',planned_duration_days:3,summary:'line 1\nline 2',repeat:'',completed:false,source:'',asana_task_id:'',history:[],dependencies:[],sortOrder:Number(id.replace(/\D/g,''))*1000||1000,...extra});
async function boot(page){await page.setViewportSize({width:1000,height:560});await page.goto(APP);await page.evaluate(()=>localStorage.clear());await page.reload();await page.evaluate(async xs=>applyJsonObject({schema_version:'1.8',items:xs},'unified','unified.json',null,{remember:false,writePermissionGranted:false}),[task('U1'),task('U2',{parentId:'U1',title:'Child',due:'2026-12-31'})]);await page.locator('#mTeam').click()}

test('UNIFIED-01: Projectは単一画面で情報列＋右端timelineを同じ行に持つ',async({page})=>{await boot(page);await expect(page.locator('#projectViewControls')).toBeVisible();await expect(page.getByText('Projectビュー:',{exact:true})).toHaveCount(0);const labels=await page.locator('#ganttView .ganttHeader .projectInfoTable th').allTextContents();expect(labels.map(x=>x.trim())).toEqual(['完了','子','ステータス','タイトル','担当','計画日数','繰返し','期限','影響区分','概要']);const row=page.locator('#ganttView .ganttRow[data-task-id="U1"]');expect(await row.locator(':scope > .ganttLeftPane').count()).toBe(1);expect(await row.locator(':scope > .ganttTimelineClip').count()).toBe(1);expect(await row.locator(':scope > :last-child').getAttribute('class')).toContain('ganttTimelineClip');await expect(row.locator('.actualEditBtn')).toBeVisible();expect(await row.locator('.ganttAddChildBtn').count()).toBe(0)});

test('UNIFIED-02: 詳細列は既定ON・atomic toggle・LocalStorage永続で行高不変',async({page})=>{await boot(page);const row=page.locator('#ganttView .ganttRow[data-task-id="U1"]');const h=await row.evaluate(el=>el.getBoundingClientRect().height);await expect(page.locator('#projectDetailBtn')).toHaveClass(/on/);await page.locator('#projectDetailBtn').click();await expect(row.locator('.sum')).toHaveCount(0);await expect(row.locator('.imp')).toHaveCount(0);expect(await row.evaluate(el=>el.getBoundingClientRect().height)).toBe(h);expect(await page.evaluate(()=>localStorage.getItem('yos_project_detail_visible_v1'))).toBe('0');await page.reload();await expect(page.locator('#projectDetailBtn')).not.toHaveClass(/on/)});

test('UNIFIED-03: 概要は一行表示しmodal Save/Cancel/Escapeと改行・Undoを維持',async({page})=>{await boot(page);const summary=page.locator('#ganttView .ganttRow[data-task-id="U1"] .sum');expect(await summary.evaluate(el=>getComputedStyle(el).whiteSpace)).toBe('nowrap');await summary.click();await expect(page.locator('.summaryModal')).toBeVisible();await page.locator('#summaryModalText').fill('cancelled');await page.locator('#summaryModalCancel').click();expect(await page.evaluate(()=>itemById('U1').summary)).toBe('line 1\nline 2');await summary.click();await page.locator('#summaryModalText').fill('new 1\nnew 2');await page.locator('#summaryModalSave').click();expect(await page.evaluate(()=>itemById('U1').summary)).toBe('new 1\nnew 2');expect(await page.evaluate(()=>undoStack.length)).toBe(1);await page.locator('#ganttView .ganttRow[data-task-id="U1"] .sum').click();await page.keyboard.press('Escape');await expect(page.locator('.summaryModal')).toHaveCount(0)});

test('UNIFIED-04: outer scrollとtimeline内部scrollは独立しrender/detailでouterを維持',async({page})=>{await boot(page);await page.setViewportSize({width:720,height:560});const host=page.locator('#ganttView');expect(await host.evaluate(el=>el.scrollWidth>el.clientWidth)).toBe(true);await host.evaluate(el=>el.scrollLeft=180);await page.waitForTimeout(30);const outer=await host.evaluate(el=>el.scrollLeft);expect(outer,'outer初期scroll').toBeGreaterThan(0);await page.evaluate(()=>setGanttTimelineScroll(100));expect(await host.evaluate(el=>el.scrollLeft),'timeline操作後outer').toBe(outer);expect(await page.evaluate(()=>ganttTimelineScrollLeft),'timeline内部scroll').toBeGreaterThan(0);await page.evaluate(()=>render());await page.waitForTimeout(30);expect(await host.evaluate(el=>el.scrollLeft),'render後outer').toBeGreaterThan(0);await page.locator('#projectDetailBtn').click();await page.waitForTimeout(80);expect(await host.evaluate(el=>el.scrollLeft),'detail後outer').toBeGreaterThan(0);expect(await page.evaluate(()=>ganttTimelineScrollLeft),'detail後timeline').toBeGreaterThan(0)});

test('UNIFIED-05: Alt+M/I、Alt+T/P/G無効、編集guard、表示ラベル',async({page})=>{await boot(page);for(const key of ['t','p','g']){await page.keyboard.press('Alt+'+key);await expect(page.locator('#mTeam')).toHaveClass(/on/)}await page.keyboard.press('Alt+m');await expect(page.locator('#mPersonal')).toHaveClass(/on/);await page.keyboard.press('Alt+m');await expect(page.locator('#mTeam')).toHaveClass(/on/);const before=await page.evaluate(()=>projectDetailVisible);await page.keyboard.press('Alt+i');expect(await page.evaluate(()=>projectDetailVisible)).toBe(!before);await page.locator('#ganttView .titleText').first().click();const guarded=await page.evaluate(()=>projectDetailVisible);await page.keyboard.press('Alt+i');expect(await page.evaluate(()=>projectDetailVisible)).toBe(guarded);await expect(page.getByText('タスク表示:',{exact:true})).toBeVisible();await expect(page.getByText('列表示:',{exact:true})).toBeVisible()});

test('UNIFIED-06: top rowとhierarchy draftは共有rowでtimelineと整列',async({page})=>{await boot(page);const top=page.locator('#ganttView .projectTopDraftRow');await expect(top).toBeVisible();expect(await top.locator(':scope > .ganttLeftPane').count()).toBe(1);expect(await top.locator(':scope > .ganttTimelineClip').count()).toBe(1);await page.evaluate(()=>selectTask('U1'));await page.keyboard.press('Insert');const draft=page.locator('#ganttView .ganttDraftRow');await expect(draft).toBeVisible();expect(await draft.locator('.projectInfoTable .sum').count()).toBe(1);const boxes=await Promise.all([draft.locator('.ganttLeftPane').evaluate(el=>el.getBoundingClientRect().height),draft.locator('.ganttTimelineClip').evaluate(el=>el.getBoundingClientRect().height)]);expect(Math.abs(boxes[0]-boxes[1])).toBeLessThan(1)});

test('UNIFIED-07: canonical Schemaとtask JSON field集合を維持',async({page})=>{await boot(page);const persisted=await page.evaluate(()=>persistableData()),isV220=APP.includes('v220_dev')||APP.includes('pbl002_')||APP.includes('v230');expect(persisted.schema_version).toBe(isV220?'2.2':'2.0');if(isV220)expect(persisted.workspace_info_markdown).toBe('');expect(Object.keys(persisted.items[0])).not.toContain('planned_start');expect(Object.keys(persisted.items[0])).not.toContain('project_detail_visible')});
