const {test,expect}=require('playwright/test');
const APP='/asanya_task_manager_v200.html';
const task=(id,extra={})=>({id,parentId:'',state:'',impact:'',title:id,owner:'',due:'',planned_duration_days:1,summary:'',repeat:'',completed:false,source:'',asana_task_id:'',history:[],dependencies:[],sortOrder:1000,...extra});
async function boot(page,items,mode='personal',view='all'){await page.setViewportSize({width:1200,height:650});await page.goto(APP);await page.evaluate(()=>localStorage.clear());await page.reload();await page.evaluate(({items,mode,view})=>{applyJsonObject({schema_version:'2.0',items},'phase7','phase7.json',null,{remember:false,writePermissionGranted:false});setView(view);setMode(mode);clearUndoHistory('phase7')},{items,mode,view})}
async function snap(page){return page.evaluate(()=>({items:JSON.parse(JSON.stringify(data.items)),undo:undoStack.length,dirty}))}
const row=(page,id)=>page.locator(`.ganttRow[data-task-id="${id}"]`);

test('P7-01/P7-06 container permits independent sibling Due/recurrence',async({page})=>{await boot(page,[task('P'),task('A',{parentId:'P',due:'2026-08-31',repeat:'毎月',recurrence_rule:{type:'monthly',mode:'date',day:31}}),task('B',{parentId:'P',due:'2026-09-02',repeat:'毎週',recurrence_rule:{type:'weekly',weekdays:[3]},sortOrder:2000})]);await page.evaluate(()=>toggle(1));expect(await page.evaluate(()=>({P:itemById('P'),A:itemById('A'),B:itemById('B')}))).toMatchObject({P:{due:'',repeat:''},A:{due:'2026-09-30'},B:{due:'2026-09-02',repeat:'毎週'}})});

test('P7-02/P7-03 recurring root accepts child and deep due-less checklist',async({page})=>{await boot(page,[task('R',{due:'2026-08-31',repeat:'毎月',recurrence_rule:{type:'monthly',mode:'date',day:31}})]);await page.evaluate(()=>{selectedTaskId='R';startDraftTask('child')});const c=await page.evaluate(()=>itemById(draftTaskId));expect(c).toMatchObject({parentId:'R',due:'',repeat:''});const cid=c.id;await page.evaluate(id=>{itemById(id).title='C';completeDraftTask(id);selectedTaskId=id;startDraftTask('child')},cid);expect(await page.evaluate(()=>itemById(draftTaskId))).toMatchObject({parentId:cid,due:'',repeat:''})});

test('P7F-01/P7F-02 ancestor and descendant Due anchors may coexist',async({page})=>{await boot(page,[task('P',{due:'2026-08-31',repeat:'毎月',recurrence_rule:{type:'monthly',mode:'date',day:31}}),task('C',{parentId:'P'}),task('G',{parentId:'C',due:'2026-09-05'})]);await page.evaluate(()=>chg(1,'due','2026-09-02'));expect(await page.evaluate(()=>data.items.map(x=>x.due))).toEqual(['2026-08-31','2026-09-02','2026-09-05']);await boot(page,[task('P',{repeat:'毎月',recurrence_rule:{type:'monthly',mode:'date',day:25}}),task('C',{parentId:'P',due:'2026-08-30'})]);await page.evaluate(()=>chg(0,'due','2026-08-25'));expect(await page.evaluate(()=>data.items.map(x=>x.due))).toEqual(['2026-08-25','2026-08-30'])});

test('P7F-01 calendar and d-digit paths accept descendant Due',async({page})=>{await boot(page,[task('P',{due:'2026-08-31',repeat:'毎月',recurrence_rule:{type:'monthly',mode:'date',day:31}}),task('C',{parentId:'P'})]);await page.evaluate(()=>setDueFromCalendar(1,'2026-09-01'));expect(await page.evaluate(()=>itemById('C').due)).toBe('2026-09-01');await page.evaluate(()=>{chg(1,'due','');selectTask('C')});await page.keyboard.press('d');await page.keyboard.press('1');const input=page.locator('#row_C input[type=text]');await input.press('Enter');expect(await page.evaluate(()=>itemById('C').due===addDays(ymd(),1))).toBe(true)});

test('P7-07/P7-08/P7F-03 recurrence hierarchy eligibility allows dated descendants',async({page})=>{await boot(page,[task('P',{due:'2026-08-31'}),task('A',{parentId:'P'}),task('B',{parentId:'P',sortOrder:2000})]);expect(await page.evaluate(()=>commitRepeatChange(0,'毎月',{type:'monthly',mode:'date',day:31}))).toBe(true);const stable=await snap(page);expect(await page.evaluate(()=>commitRepeatChange(1,'毎日',{type:'daily'}))).toBe(false);expect(await snap(page)).toEqual(stable);await boot(page,[task('P',{due:'2026-08-31'}),task('C',{parentId:'P',due:'2026-09-03'}),task('G',{parentId:'C',due:'2026-09-05'})]);expect(await page.evaluate(()=>commitRepeatChange(0,'毎月',{type:'monthly',mode:'date',day:31}))).toBe(true);expect(await page.evaluate(()=>data.items.map(x=>x.due))).toEqual(['2026-08-31','2026-09-03','2026-09-05'])});

test('P7-10 unfinished descendant blocks button and Project status completion',async({page})=>{for(const mode of ['personal','team']){await boot(page,[task('R',{due:'2026-08-31',repeat:'毎月',recurrence_rule:{type:'monthly',mode:'date',day:31}}),task('C',{parentId:'R'})],mode);const before=await snap(page);page.once('dialog',d=>d.accept());if(mode==='personal')await page.locator('#row_R .doneBtn').click();else await row(page,'R').locator('.ganttState select').selectOption('完了');expect(await snap(page)).toEqual(before)}});

test('P7-11/P7-12 checklist rollover recursively resets and preserves definitions',async({page})=>{const items=[task('R',{due:'2026-08-31',repeat:'毎月',recurrence_rule:{type:'monthly',mode:'date',day:31},actual_start:'2026-08-01'}),task('C',{parentId:'R',completed:true,state:'完了',title:'Child',summary:'sum',owner:'owner',impact:'A-今週誰かが困る',planned_duration_days:5,actual_end:'2026-08-20'}),task('G',{parentId:'C',completed:true,state:'完了',actual_start:'2026-08-02'}),task('GG',{parentId:'G',completed:true,state:'完了',actual_end:'2026-08-03'})];await boot(page,items);await page.evaluate(()=>toggle(0));const out=await page.evaluate(()=>data.items);expect(out.map(x=>x.id)).toEqual(['R','C','G','GG']);expect(out[0]).toMatchObject({due:'2026-09-30',completed:false,state:''});for(const x of out.slice(1)){expect(x).toMatchObject({due:'',completed:false,state:''});for(const k of ['actual_start','actual_end','actual_start_source','actual_end_source'])expect(x[k]).toBeUndefined()}expect(out[1]).toMatchObject({title:'Child',summary:'sum',owner:'owner',impact:'A-今週誰かが困る',parentId:'R',planned_duration_days:5})});

test('P7-13 internal dependencies survive and reactivate after rollover',async({page})=>{await boot(page,[task('R',{due:'2026-08-31',repeat:'毎月',recurrence_rule:{type:'monthly',mode:'date',day:31}}),task('A',{parentId:'R',completed:true,state:'完了'}),task('B',{parentId:'R',completed:true,state:'完了',dependencies:[{task_id:'A',type:'finish_to_start'}],sortOrder:2000})]);await page.evaluate(()=>toggle(0));expect(await page.evaluate(()=>({dep:itemById('B').dependencies,block:startBlockers(itemById('B')).map(x=>x.task.id)}))).toEqual({dep:[{task_id:'A',type:'finish_to_start'}],block:['A']})});

test('P7-14/P7-15/P7-17 external boundary rejects but recurring root uses existing restriction',async({page})=>{for(const [cur,other,direction] of [['C','X','predecessor'],['C','X','successor'],['R','X','predecessor']]){await boot(page,[task('R',{due:'2026-08-31',repeat:'毎月',recurrence_rule:{type:'monthly',mode:'date',day:31}}),task('C',{parentId:'R'}),task('X',{sortOrder:3000})]);const before=await snap(page);await page.evaluate(({cur,other,direction})=>{relationOpenId=cur;relationSelectedTaskId=other;relationFormDirection=direction;addDependencyFromForm()},{cur,other,direction});expect(await snap(page)).toEqual(before)}});

test('P7-16 existing crossing dependency blocks recurrence enable',async({page})=>{await boot(page,[task('P',{due:'2026-08-31'}),task('C',{parentId:'P'}),task('X',{dependencies:[{task_id:'C',type:'finish_to_start'}],sortOrder:3000})]);const before=await snap(page);expect(await page.evaluate(()=>commitRepeatChange(0,'毎月',{type:'monthly',mode:'date',day:31}))).toBe(false);expect(await snap(page)).toEqual(before)});

test('P7-18/P7-19 one Undo/Redo covers complete checklist occurrence',async({page})=>{const items=[task('R',{due:'2026-08-31',repeat:'毎月',recurrence_rule:{type:'monthly',mode:'date',day:31},actual_start:'2026-08-01'}),task('C',{parentId:'R',completed:true,state:'完了',actual_end:'2026-08-20'})];await boot(page,items);const before=(await snap(page)).items;await page.evaluate(()=>toggle(0));const after=(await snap(page)).items;expect(await page.evaluate(()=>undoStack.length)).toBe(1);await page.keyboard.press('Control+z');expect((await snap(page)).items).toEqual(before);await page.keyboard.press('Control+y');expect((await snap(page)).items).toEqual(after)});

test('P7F-07/P7F-08 dated checklist descendant shifts and resets atomically',async({page})=>{await boot(page,[task('R',{due:'2026-08-31',repeat:'毎月',recurrence_rule:{type:'monthly',mode:'date',day:31},actual_start:'2026-08-01'}),task('C',{parentId:'R',due:'2026-09-03',completed:true,state:'完了',actual_end:'2026-08-20'})]);await page.evaluate(()=>toggle(0));expect(await page.evaluate(()=>data.items.map(x=>({due:x.due,completed:x.completed,state:x.state,actual_end:x.actual_end})))).toEqual([{due:'2026-09-30',completed:false,state:'',actual_end:undefined},{due:'2026-10-03',completed:false,state:'',actual_end:undefined}])});

test('P7-21/P7-22 FLIP preserves subtree snapshot and wheel semantics',async({page})=>{await boot(page,[task('R',{due:'2026-08-01',repeat:'毎月',recurrence_rule:{type:'monthly',mode:'date',day:1}}),task('C',{parentId:'R',completed:true,state:'完了',actual_start:'2026-07-01'}),task('A',{due:'2026-08-02',sortOrder:3000}),task('B',{due:'2026-08-03',sortOrder:4000})],'team');await row(page,'R').locator('.ganttState select').selectOption('完了');await expect(row(page,'R')).toHaveClass(/sortMoveAnimating/);await expect(row(page,'C')).toHaveClass(/recurrencePresentationPending/);await row(page,'R').dispatchEvent('wheel',{deltaX:120,deltaY:0});await expect(row(page,'R')).toHaveClass(/sortMoveAnimating/);await page.mouse.wheel(0,120);await expect(row(page,'C')).not.toHaveClass(/recurrencePresentationPending/);await expect(row(page,'C')).not.toHaveClass(/ganttDone/)});

test('P7-23/P7-24 Delete equals normal completion toggle and never deletes record',async({page})=>{const base=[task('A')];const results=[];for(const action of ['click','delete']){await boot(page,base);await page.evaluate(()=>selectTask('A'));if(action==='click')await page.locator('#row_A .doneBtn').click();else await page.keyboard.press('Delete');results.push(await page.evaluate(()=>({items:data.items,undo:undoStack.length})))}expect(results[1]).toEqual(results[0]);await page.keyboard.press('Delete');expect(await page.evaluate(()=>({count:data.items.length,completed:itemById('A').completed,undo:undoStack.length}))).toEqual({count:1,completed:false,undo:2})});

test('P7-25/P7-26 Delete uses recurring leaf/checklist paths and blockers',async({page})=>{await boot(page,[task('R',{due:'2026-08-31',repeat:'毎月',recurrence_rule:{type:'monthly',mode:'date',day:31}})]);await page.evaluate(()=>selectTask('R'));await page.keyboard.press('Delete');expect(await page.evaluate(()=>itemById('R').due)).toBe('2026-09-30');await boot(page,[task('R',{due:'2026-08-31',repeat:'毎月',recurrence_rule:{type:'monthly',mode:'date',day:31}}),task('C',{parentId:'R'})]);const before=await snap(page);page.once('dialog',d=>d.accept());await page.evaluate(()=>selectTask('R'));await page.keyboard.press('Delete');expect(await snap(page)).toEqual(before);await page.evaluate(()=>{itemById('C').completed=true;itemById('C').state='完了';clearUndoHistory('p7')});await page.keyboard.press('Delete');expect(await page.evaluate(()=>itemById('C').completed)).toBe(false)});

test('P7-27 Delete is ignored in title/Due editors',async({page})=>{await boot(page,[task('A',{title:'ABCDE',due:'2026-08-31'})]);await page.evaluate(()=>selectTask('A'));const title=page.locator('#row_A .titleText');await title.focus();await page.keyboard.press('Delete');expect(await page.evaluate(()=>itemById('A').completed)).toBe(false);await page.evaluate(()=>render());await page.locator('#row_A .dueTxt').click();await page.locator('#row_A input[type=text]').focus();await page.keyboard.press('Delete');expect(await page.evaluate(()=>itemById('A').completed)).toBe(false)});

test('P7-28/P7-29 Delete does not bulk-delete and help documents shortcut',async({page})=>{await boot(page,[task('A',{completed:true,state:'完了'}),task('B',{completed:true,state:'完了',sortOrder:2000})],'personal','done');await page.locator('.doneBulkCheck[data-task-id="B"]').check();await page.evaluate(()=>selectTask('A'));await page.keyboard.press('Delete');expect(await page.evaluate(()=>({ids:data.items.map(x=>x.id),A:itemById('A').completed,bulk:Array.from(doneBulkSelection)}))).toEqual({ids:['A','B'],A:false,bulk:['B']});await expect(page.locator('#shortcutHelp')).toContainText('Delete＝完了ボタン')});
