const {test,expect}=require('playwright/test');
const {APP}=require('./helpers/app-target');
const task=(id,extra={})=>({id,parentId:'',state:'未着手',impact:'',title:`Task ${id}`,owner:'担当',due:'2026-08-20',planned_duration_days:3,summary:'',repeat:'',completed:false,source:'',asana_task_id:'',history:[],dependencies:[],sortOrder:(Number(id.replace(/\D/g,''))||1)*1000,...extra});
async function boot(page,items=[task('1')]){await page.setViewportSize({width:1000,height:520});await page.goto(APP);await page.evaluate(()=>localStorage.clear());await page.reload();await page.evaluate(xs=>applyJsonObject({schema_version:'1.8',items:xs},'hqa1','hqa1.json',null,{remember:false,writePermissionGranted:false}),items);await page.evaluate(()=>setMode('team'));await expect(page.locator('#ganttView')).toBeVisible()}
async function dragX(page,locator,dx=40){await locator.evaluate(el=>el.scrollIntoView({block:'center',inline:'nearest',behavior:'auto'}));const box=await locator.boundingBox();expect(box).not.toBeNull();const x=box.x+box.width/2,y=box.y+box.height/2;expect(await page.evaluate(({x,y})=>document.elementFromPoint(x,y)?.dataset?.projectCol,{x,y})).toBe(await locator.getAttribute('data-project-col'));await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x+dx,y,{steps:8});await page.mouse.up()}

test('HQA1-COLS-01: Project columns use the specified order and independent defaults',async({page})=>{await boot(page);expect(await page.evaluate(()=>cols())).toEqual(['done','move','child','state','title','owner','planned','repeat','due','impact','summary']);expect(await page.evaluate(()=>({...projectWidths}))).toMatchObject({done:31,move:39,child:36,state:72,title:450,owner:72,planned:60,repeat:82,due:88,impact:90,summary:300});await expect(page.locator('.ganttHeader th[data-c="done"] .rs,.ganttHeader th[data-c="move"] .rs,.ganttHeader th[data-c="child"] .rs')).toHaveCount(0);const todo=await page.evaluate(()=>({...widths}));await page.evaluate(()=>{projectWidths.title=490;localStorage.setItem(PROJECT_COL_KEY,JSON.stringify(projectWidths))});expect(await page.evaluate(()=>({...widths}))).toEqual(todo)});

test('HQA1-RESIZE-01: each resizable Project column changes alone and persists',async({page})=>{await boot(page);for(const key of ['state','title','owner','planned','repeat','due','impact','summary']){const before=await page.evaluate(()=>({...projectWidths}));await dragX(page,page.locator(`.ganttHeader th[data-c="${key}"] .rs`),40);const after=await page.evaluate(()=>({...projectWidths}));expect(after[key]).toBe(before[key]+40);for(const other of Object.keys(before))if(other!==key)expect(after[other]).toBe(before[other])}expect(await page.evaluate(()=>JSON.parse(localStorage.getItem(PROJECT_COL_KEY)))).toEqual(await page.evaluate(()=>({...projectWidths})));await expect(page.locator('.ganttHeader th').first()).toHaveCSS('background-color','rgb(31, 78, 120)')});

test('HQA1-ALIGN-01: header, top draft, rows, and timeline remain aligned after resize',async({page})=>{await boot(page,[task('1'),task('2')]);const positions=()=>page.evaluate(()=>{const h=document.querySelector('.ganttHeader .projectInfoTable').getBoundingClientRect(),b=document.querySelector('.ganttRow .projectInfoTable').getBoundingClientRect(),t=document.querySelector('.projectTopDraftRow .projectInfoTable').getBoundingClientRect(),c=document.querySelector('.ganttHeader .ganttTimelineClip').getBoundingClientRect();return[h.width,b.width,t.width,c.left-h.right]});for(let i=0;i<2;i++){const p=await positions();expect(Math.max(...p.slice(0,3))-Math.min(...p.slice(0,3))).toBeLessThan(1);expect(Math.abs(p[3])).toBeLessThan(1);if(!i)await dragX(page,page.locator('.ganttHeader th[data-c="owner"] .rs'),40)}});

test('HQA1.1-GEOMETRY-01: header columns are ordered and timeline starts after information region',async({page})=>{await boot(page,[task('1'),task('2')]);const geometry=()=>page.evaluate(()=>{const cells=[...document.querySelectorAll('.ganttHeader th')].map(el=>{const r=el.getBoundingClientRect();return{key:el.dataset.c,left:r.left,right:r.right,bg:getComputedStyle(el).backgroundColor,color:getComputedStyle(el).color}}),info=document.querySelector('.ganttHeader .projectInfoTable').getBoundingClientRect(),clip=document.querySelector('.ganttHeader .ganttTimelineClip').getBoundingClientRect(),body=document.querySelector('.ganttRow .projectInfoTable').getBoundingClientRect();return{cells,info,clip,body}});for(const outer of [0,320]){await page.locator('#ganttView').evaluate((el,x)=>el.scrollLeft=x,outer);const g=await geometry();for(let i=1;i<g.cells.length;i++)expect(Math.abs(g.cells[i].left-g.cells[i-1].right)).toBeLessThan(1);expect(Math.abs(g.info.width-g.body.width)).toBeLessThan(1);expect(Math.abs(g.clip.left-g.info.right)).toBeLessThan(1);for(const c of g.cells){expect(c.bg).toBe('rgb(31, 78, 120)');expect(c.color).toBe('rgb(255, 255, 255)')}}});

test('HQA1.1-STICKY-THRESHOLD-01: sticky activates only at Project top and releases after Project',async({page})=>{await boot(page,Array.from({length:80},(_,i)=>task(String(i+1),{sortOrder:(i+1)*1000})));await page.evaluate(()=>{const spacer=document.createElement('div');spacer.style.height='900px';document.body.appendChild(spacer)});const head=page.locator('#ganttView .ganttHeader'),top=page.locator('#ganttView .projectTopDraftRow'),natural=await head.evaluate(el=>el.getBoundingClientRect().top+scrollY);await page.evaluate(y=>window.scrollTo(0,Math.max(0,y-80)),natural);await page.waitForTimeout(50);await expect(head).not.toHaveClass(/hqaLiveSticky/);expect((await head.boundingBox()).y).toBeGreaterThan(60);await page.evaluate(y=>window.scrollTo(0,y+2),natural);await expect.poll(()=>head.evaluate(el=>el.classList.contains('hqaLiveSticky'))).toBe(true);expect(Math.abs((await head.boundingBox()).y)).toBeLessThan(1);expect(Math.abs((await top.boundingBox()).y-(await head.boundingBox()).height)).toBeLessThan(1);for(const id of ['b_title','b_due','b_summary'])await expect(page.locator('#'+id)).toHaveCount(1);await page.evaluate(()=>window.scrollTo(0,document.documentElement.scrollHeight));await expect.poll(()=>head.evaluate(el=>el.classList.contains('hqaLiveSticky'))).toBe(false)});

test('HQA1.1-VISUAL-01: desktop normal and sticky screenshots',async({page})=>{await page.setViewportSize({width:1680,height:900});await page.goto(APP);await page.evaluate(()=>localStorage.clear());await page.reload();await page.evaluate(xs=>applyJsonObject({schema_version:'1.8',items:xs},'visual','visual.json',null,{remember:false,writePermissionGranted:false}),Array.from({length:36},(_,i)=>task(String(i+1),{title:`Visual Project Task ${i+1} with a realistically long title`,summary:`Summary sample ${i+1} for alignment review`,sortOrder:(i+1)*1000})));await page.evaluate(()=>setMode('team'));await page.screenshot({path:'test-results/hqa1-normal.png'});const natural=await page.locator('.ganttHeader').evaluate(el=>el.getBoundingClientRect().top+scrollY);await page.evaluate(y=>window.scrollTo(0,y+180),natural);await expect.poll(()=>page.locator('.ganttHeader').evaluate(el=>el.classList.contains('hqaLiveSticky'))).toBe(true);await page.screenshot({path:'test-results/hqa1-sticky.png'});const h=await page.locator('.ganttHeader .projectInfoTable').boundingBox(),clip=await page.locator('.ganttHeader .ganttTimelineClip').boundingBox();expect(Math.abs(clip.x-(h.x+h.width))).toBeLessThan(1);await page.locator('#ganttView').evaluate(el=>el.scrollLeft=el.scrollWidth);await page.waitForTimeout(60);await page.screenshot({path:'test-results/hqa1-sticky-timeline.png'});await expect(page.locator('.ganttHeader .ganttTimelineClip')).toBeVisible()});

test('HQA1-STICKY-01: live header and draft stay interactive with one field instance',async({page})=>{await boot(page,Array.from({length:80},(_,i)=>task(String(i+1),{sortOrder:(i+1)*1000})));await page.evaluate(()=>window.scrollTo(0,document.querySelector('#ganttView').getBoundingClientRect().top+scrollY+350));await expect.poll(()=>page.locator('.projectTopDraftRow').evaluate(el=>getComputedStyle(el).position)).toBe('fixed');for(const id of ['b_title','b_due','b_summary'])await expect(page.locator('#'+id)).toHaveCount(1);await page.locator('#b_owner').fill('Owner X');await page.locator('#b_repeat').selectOption({index:1});await page.locator('#b_impact').selectOption({index:1});const extras=await page.evaluate(()=>({owner:b_owner.value,repeat:b_repeat.value,impact:b_impact.value}));await page.locator('#b_summary').fill('line1\nline2\nline3');expect((await page.locator('#b_summary').boundingBox()).height).toBeLessThanOrEqual(96);await page.locator('#b_title').fill('sticky new');await page.locator('#b_title').press('Enter');await expect(page.locator('#b_due')).toBeFocused();await page.locator('#b_due').fill('2026/8/25');await page.locator('#b_due').press('Enter');await expect(page.locator('#b_planned')).toBeFocused();await page.locator('#b_planned').fill('2');await page.locator('#b_planned').press('Enter');expect(await page.evaluate(()=>data.items.find(x=>x.title==='sticky new'))).toMatchObject({...extras,summary:'line1\nline2\nline3',due:'2026-08-25',planned_duration_days:2})});

test('HQA1-SUMMARY-01: committed summary modal is contained and supports cancel/save',async({page})=>{await boot(page,[task('1',{summary:'old\nline'})]);await page.locator('.ganttRow .sum').click();const m=await page.locator('.summaryModal').boundingBox(),a=await page.locator('#summaryModalText').boundingBox();expect(a.x).toBeGreaterThanOrEqual(m.x);expect(a.x+a.width).toBeLessThanOrEqual(m.x+m.width+1);expect(a.height).toBeGreaterThanOrEqual(195);await page.locator('#summaryModalText').fill('cancel');await page.locator('#summaryModalCancel').click();expect(await page.evaluate(()=>itemById('1').summary)).toBe('old\nline');await page.locator('.ganttRow .sum').click();await page.locator('#summaryModalText').fill('new');await page.locator('#summaryModalSave').click();expect(await page.evaluate(()=>itemById('1').summary)).toBe('new')});

for(const [kind,key] of [['same','Enter'],['child','Insert']])test(`HQA1-DRAFT-${kind}: hierarchy draft summary is inline and retained on commit`,async({page})=>{await boot(page);await page.evaluate(()=>{setProjectView('gantt');selectedTaskId='1'});await page.keyboard.press(key);const id=await page.evaluate(()=>draftTaskId),row=page.locator(`.ganttRow[data-task-id="${id}"]`);await expect(row.locator('.ganttDraftTitle')).toBeVisible();await row.locator('.hierarchyDraftSummary').fill('draft line1\ndraft line2');await expect(page.locator('.summaryModal')).toHaveCount(0);await row.locator('.ganttDraftTitle').fill(kind);await row.locator('.ganttDraftTitle').press('Enter');await row.locator('.ganttDue input[type="text"]').press('Enter');await row.locator('.ganttPlanned input').fill('1');await row.locator('.ganttPlanned input').press('Enter');expect(await page.evaluate(id=>itemById(id).summary,id)).toBe('draft line1\ndraft line2');await row.locator('.sum').click();await expect(page.locator('.summaryModal')).toBeVisible()});

test('HQA1-SHORTCUT-TIMELINE-01: shortcuts, impact labels, and independent timeline scrolling',async({page})=>{await boot(page,[task('1',{impact:'B-期限 期限までに誰かが困る'}),task('2',{due:'2028-12-31',planned_duration_days:900})]);await page.keyboard.press('Alt+m');expect(await page.evaluate(()=>mode)).toBe('personal');for(const key of ['t','p','g']){await page.keyboard.press('Alt+'+key);expect(await page.evaluate(()=>mode)).toBe('personal')}await page.keyboard.press('Alt+m');expect(await page.evaluate(()=>mode)).toBe('team');const host=page.locator('#ganttView'),outer=await host.evaluate(el=>el.scrollLeft);await page.evaluate(()=>setGanttTimelineScroll(300));expect(await host.evaluate(el=>el.scrollLeft)).toBe(outer);await expect(page.locator('#shortcutHelp')).not.toContainText(/Alt\+[PG]/)});
