const {test,expect}=require('playwright/test');
const APP='/asanya_task_manager_v200.html';
const task=(id,extra={})=>({id,parentId:'',state:'',impact:'',title:id,owner:'',due:'',planned_duration_days:1,summary:'',repeat:'',completed:false,source:'',asana_task_id:'',history:[],dependencies:[],sortOrder:1000,...extra});
const recurring=(id,due='2026-08-25',extra={})=>task(id,{due,repeat:'毎月',recurrence_rule:{type:'monthly',mode:'date',day:25},...extra});
async function boot(page,items,mode='personal'){await page.setViewportSize({width:1200,height:650});await page.goto(APP);await page.evaluate(()=>localStorage.clear());await page.reload();await page.evaluate(({items,mode})=>{applyJsonObject({schema_version:'2.0',items},'p7f','p7f.json',null,{remember:false,writePermissionGranted:false});setView('all');setMode(mode);clearUndoHistory('p7f')},{items,mode})}
const dues=page=>page.evaluate(()=>Object.fromEntries(data.items.map(x=>[x.id,x.due])));
const snapshot=page=>page.evaluate(()=>JSON.parse(JSON.stringify(data.items)));
async function dragDays(page,locator,days){await locator.scrollIntoViewIfNeeded();const b=await locator.boundingBox();if(!b)throw Error('drag target missing');await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.down();await page.mouse.move(b.x+b.width/2+days*28,b.y+b.height/2,{steps:8});await page.mouse.up()}

test('P7F-02/P7F-03 first parent Due accepts existing dated descendants without moving them',async({page})=>{await boot(page,[recurring('P',''),task('C',{parentId:'P',due:'2026-08-30'}),task('G',{parentId:'C',due:'2026-09-02'})]);await page.evaluate(()=>chg(0,'due','2026-08-25'));expect(await dues(page)).toEqual({P:'2026-08-25',C:'2026-08-30',G:'2026-09-02'})});

test('P7F-G01 non-recurring parent, child and grandchild Due coexist through normal paths',async({page})=>{await boot(page,[task('P',{due:'2026-08-25'}),task('C',{parentId:'P'}),task('G',{parentId:'C'})]);await page.evaluate(()=>setDueFromCalendar(1,'2026-08-30'));await page.evaluate(()=>{selectTask('G')});await page.keyboard.press('d');await page.keyboard.press('1');await page.locator('#row_G input[type=text]').press('Enter');expect(await page.evaluate(()=>({P:itemById('P').due,C:itemById('C').due,G:itemById('G').due,tomorrow:addDays(ymd(),1)}))).toMatchObject({P:'2026-08-25',C:'2026-08-30'});expect(await page.evaluate(()=>itemById('G').due===addDays(ymd(),1))).toBe(true)});

test('P7F-G02/G03 non-recurring parent manual move leaves every descendant Due unchanged',async({page})=>{await boot(page,[task('P',{due:'2026-08-25'}),task('C',{parentId:'P',due:'2026-08-30'}),task('G',{parentId:'C',due:'2026-09-02'}),task('N',{parentId:'P'})]);await page.evaluate(()=>chg(0,'due','2026-08-30'));expect(await dues(page)).toEqual({P:'2026-08-30',C:'2026-08-30',G:'2026-09-02',N:''})});

test('P7F-G04/G05 descendant and parent manual edits are independent',async({page})=>{await boot(page,[task('P',{due:'2026-08-25'}),task('A',{parentId:'P',due:'2026-08-30'}),task('B',{parentId:'P',due:'2026-09-01',sortOrder:2000})]);await page.evaluate(()=>chg(1,'due','2026-09-03'));expect(await dues(page)).toEqual({P:'2026-08-25',A:'2026-09-03',B:'2026-09-01'});await page.evaluate(()=>chg(0,'due','2026-08-27'));expect(await dues(page)).toEqual({P:'2026-08-27',A:'2026-09-03',B:'2026-09-01'});await page.evaluate(()=>{chg(0,'due','');chg(0,'due','2026-10-01');chg(1,'due','')});expect(await dues(page)).toEqual({P:'2026-10-01',A:'',B:'2026-09-01'})});

test('P7F-04/P7F-05 manual recurring-parent move also leaves descendants unchanged',async({page})=>{await boot(page,[recurring('P'),task('C',{parentId:'P',due:'2026-08-30'}),task('G',{parentId:'C',due:'2026-09-02'}),task('GG',{parentId:'G'})]);await page.evaluate(()=>chg(0,'due','2026-08-27'));expect(await dues(page)).toEqual({P:'2026-08-27',C:'2026-08-30',G:'2026-09-02',GG:''})});

test('P7F-06 descendant and recurring-parent manual edits remain independent',async({page})=>{await boot(page,[recurring('P'),task('A',{parentId:'P',due:'2026-08-30'}),task('B',{parentId:'P',due:'2026-09-01',sortOrder:2000})]);await page.evaluate(()=>chg(1,'due','2026-09-03'));expect(await dues(page)).toEqual({P:'2026-08-25',A:'2026-09-03',B:'2026-09-01'});await page.evaluate(()=>chg(0,'due','2026-08-27'));expect(await dues(page)).toEqual({P:'2026-08-27',A:'2026-09-03',B:'2026-09-01'})});

test('P7F-07/P7F-08 rollover shifts dated descendants once and resets execution fields',async({page})=>{await boot(page,[recurring('P','2026-08-25',{completed:false,actual_start:'2026-08-01'}),task('C',{parentId:'P',due:'2026-08-30',completed:true,state:'完了',actual_start:'2026-08-02',actual_end:'2026-08-20',actual_start_source:'user',actual_end_source:'user',summary:'keep'}),task('G',{parentId:'C',due:'2026-09-02',completed:true,state:'完了',actual_end:'2026-08-21'}),task('N',{parentId:'P',completed:true,state:'完了',sortOrder:3000})]);await page.evaluate(()=>toggle(0));expect(await dues(page)).toEqual({P:'2026-09-25',C:'2026-09-30',G:'2026-10-03',N:''});const out=await page.evaluate(()=>data.items.map(x=>({id:x.id,completed:x.completed,state:x.state,as:x.actual_start,ae:x.actual_end,ass:x.actual_start_source,aes:x.actual_end_source,summary:x.summary})));for(const x of out)expect(x).toMatchObject({completed:false,state:''});expect(out[1]).toMatchObject({as:undefined,ae:undefined,ass:undefined,aes:undefined,summary:'keep'})});

test('P7F-09 unfinished descendant still blocks recurring parent completion',async({page})=>{await boot(page,[recurring('P'),task('C',{parentId:'P',due:'2026-08-30'})]);const before=await snapshot(page);page.once('dialog',d=>d.accept());await page.evaluate(()=>toggle(0));expect(await snapshot(page)).toEqual(before)});

test('P7F-10/P7F-11 clearing parent Due leaves descendants untouched',async({page})=>{await boot(page,[recurring('P'),task('C',{parentId:'P',due:'2026-08-30'})]);await page.evaluate(()=>chg(0,'due',''));expect(await dues(page)).toEqual({P:'',C:'2026-08-30'});await page.evaluate(()=>chg(0,'due','2026-09-10'));expect(await dues(page)).toEqual({P:'2026-09-10',C:'2026-08-30'})});

test('P7F-12 cleared descendant stays empty and siblings stay unchanged during manual parent movement',async({page})=>{await boot(page,[recurring('P'),task('A',{parentId:'P',due:'2026-08-30'}),task('B',{parentId:'P',due:'2026-09-01',sortOrder:2000})]);await page.evaluate(()=>{chg(1,'due','');chg(0,'due','2026-08-27')});expect(await dues(page)).toEqual({P:'2026-08-27',A:'',B:'2026-09-01'})});

test('P7F-13 manual linked move is one atomic Undo/Redo transaction',async({page})=>{await boot(page,[recurring('P'),task('C',{parentId:'P',due:'2026-08-30'}),task('G',{parentId:'C',due:'2026-09-02'})]);const before=await snapshot(page);await page.evaluate(()=>chg(0,'due','2026-08-27'));const after=await snapshot(page);expect(await page.evaluate(()=>undoStack.length)).toBe(1);await page.keyboard.press('Control+z');expect(await snapshot(page)).toEqual(before);await page.keyboard.press('Control+y');expect(await snapshot(page)).toEqual(after)});

test('P7F-14 rollover move and reset is one atomic Undo/Redo transaction',async({page})=>{await boot(page,[recurring('P'),task('C',{parentId:'P',due:'2026-08-30',completed:true,state:'完了',actual_end:'2026-08-20'}),task('G',{parentId:'C',due:'2026-09-02',completed:true,state:'完了'})]);const before=await snapshot(page);await page.evaluate(()=>toggle(0));const after=await snapshot(page);expect(await page.evaluate(()=>undoStack.length)).toBe(1);await page.keyboard.press('Control+z');expect(await snapshot(page)).toEqual(before);await page.keyboard.press('Control+y');expect(await snapshot(page)).toEqual(after)});

test('P7F persistence remains Schema 2.0 with no offset fields',async({page})=>{await boot(page,[recurring('P'),task('C',{parentId:'P',due:'2026-08-30'})]);await page.evaluate(()=>chg(0,'due','2026-08-27'));const saved=await page.evaluate(()=>persistableData());expect(saved.schema_version).toBe('2.0');expect(JSON.stringify(saved)).not.toMatch(/due_offset|parent_due_offset|recurrence_offset_days/);expect(saved.items.map(x=>x.due)).toEqual(['2026-08-27','2026-08-30'])});

test('P7F-15 Gantt plan and due-only manual drag leave descendant Due unchanged',async({page})=>{await page.emulateMedia({reducedMotion:'no-preference'});await boot(page,[recurring('P'),task('C',{parentId:'P',due:'2026-08-30'}),task('X',{due:'2026-08-26',sortOrder:3000})],'team');await dragDays(page,page.locator('.ganttBar[data-task-id="P"]'),2);expect(await dues(page)).toEqual({P:'2026-08-27',C:'2026-08-30',X:'2026-08-26'});await expect(page.locator('.ganttRow[data-task-id="P"]')).toHaveClass(/sortMoveAnimating/);const parent=recurring('P');delete parent.planned_duration_days;await boot(page,[parent,task('C',{parentId:'P',due:'2026-08-30'}),task('X',{due:'2026-08-26',sortOrder:3000})],'team');await dragDays(page,page.locator('.ganttRow[data-task-id="P"] .ganttDueOnlyMarker'),2);expect(await dues(page)).toEqual({P:'2026-08-27',C:'2026-08-30',X:'2026-08-26'})});

test('P7F-G06 non-recurring milestone drag leaves descendant Due unchanged',async({page})=>{await boot(page,[task('P',{due:'2026-08-25',planned_duration_days:0}),task('C',{parentId:'P',due:'2026-08-30'}),task('X',{due:'2026-08-26',sortOrder:3000})],'team');await dragDays(page,page.locator('.ganttMilestone[data-task-id="P"]'),3);expect(await dues(page)).toEqual({P:'2026-08-28',C:'2026-08-30',X:'2026-08-26'})});

test('P7F-SCROLL no rendered row movement causes no animation and no automatic vertical jump',async({page})=>{const items=Array.from({length:35},(_,i)=>task('T'+i,{due:'2026-07-'+String((i%28)+1).padStart(2,'0'),sortOrder:(i+1)*1000}));items.push(task('P',{due:'2026-08-25',sortOrder:40000}),task('C',{parentId:'P',sortOrder:41000}));await boot(page,items,'team');const child=page.locator('.ganttRow[data-task-id="C"]');await child.scrollIntoViewIfNeeded();await page.waitForTimeout(200);const before=await page.evaluate(()=>({y:scrollY,p:document.querySelector('.ganttRow[data-task-id="P"]').getBoundingClientRect().top,c:document.querySelector('.ganttRow[data-task-id="C"]').getBoundingClientRect().top}));await page.evaluate(()=>setDueFromCalendar(data.items.findIndex(x=>x.id==='C'),'2026-08-30'));await page.waitForTimeout(100);const after=await page.evaluate(()=>({y:scrollY,p:document.querySelector('.ganttRow[data-task-id="P"]').getBoundingClientRect().top,c:document.querySelector('.ganttRow[data-task-id="C"]').getBoundingClientRect().top,anim:document.querySelectorAll('.sortMoveAnimating').length}));expect(after.y).toBe(before.y);expect(after.anim).toBe(0);expect(await page.evaluate(()=>({P:itemById('P').due,C:itemById('C').due}))).toEqual({P:'2026-08-25',C:'2026-08-30'})});

async function openAdd(page,direction='predecessor'){await page.locator('.ganttRow[data-task-id="A"] .relationTrigger').evaluate(el=>el.click());await page.getByRole('button',{name:direction==='predecessor'?'＋ 前工程を追加':'＋ 後工程を追加'}).click();await expect(page.locator('.relationForm')).toBeVisible()}
test('P6F-01 Cancel without candidate closes relation UI and is a data/history no-op',async({page})=>{await boot(page,[task('A'),task('B',{sortOrder:2000})],'team');const before=await snapshot(page);await openAdd(page);await page.getByRole('button',{name:'キャンセル'}).click();expect(await page.evaluate(()=>({open:relationOpenId,direction:relationFormDirection,candidate:relationSelectedTaskId,undo:undoStack.length}))).toEqual({open:'',direction:'',candidate:'',undo:0});expect(await snapshot(page)).toEqual(before);await expect(page.locator('#relationPopup')).toBeHidden();await expect(page.locator('#ganttView')).toBeVisible()});

test('P6F-02 Project candidate Cancel clears highlight, closes popup, and fresh Add still works',async({page})=>{await boot(page,[task('A'),task('B',{sortOrder:2000})],'team');await openAdd(page);await page.locator('.ganttRow[data-task-id="B"] .ganttTaskTitle').click();await expect(page.locator('.ganttRow[data-task-id="B"]')).toHaveClass(/dependencyCandidateRow/);await page.getByRole('button',{name:'キャンセル'}).click();await expect(page.locator('.dependencyCandidateRow')).toHaveCount(0);await expect(page.locator('#relationPopup')).toBeHidden();expect(await page.evaluate(()=>({direction:relationFormDirection,candidate:relationSelectedTaskId,deps:itemById('A').dependencies,undo:undoStack.length}))).toEqual({direction:'',candidate:'',deps:[],undo:0});await openAdd(page);await page.locator('.ganttRow[data-task-id="B"] .ganttTaskTitle').click();await page.locator('.relationForm .pri').click();expect(await page.evaluate(()=>itemById('A').dependencies)).toEqual([{task_id:'B',type:'finish_to_start'}])});

test('P6F-03 successor search candidate Cancel closes and clears temporary state',async({page})=>{await boot(page,[task('A'),task('B',{sortOrder:2000})],'team');await openAdd(page,'successor');await page.evaluate(()=>selectDependencyCandidate('B'));await page.getByRole('button',{name:'キャンセル'}).click();expect(await page.evaluate(()=>({open:relationOpenId,direction:relationFormDirection,candidate:relationSelectedTaskId,deps:itemById('A').dependencies,undo:undoStack.length}))).toEqual({open:'',direction:'',candidate:'',deps:[],undo:0});await expect(page.locator('#relationPopup')).toBeHidden()});

test('P6F-04 closing relation popup clears add mode and candidate state',async({page})=>{await boot(page,[task('A'),task('B',{sortOrder:2000})],'team');await openAdd(page);await page.evaluate(()=>{selectDependencyCandidate('B');closeRelationPopup()});expect(await page.evaluate(()=>({open:relationOpenId,direction:relationFormDirection,candidate:relationSelectedTaskId,undo:undoStack.length}))).toEqual({open:'',direction:'',candidate:'',undo:0});await expect(page.locator('.dependencyCandidateRow')).toHaveCount(0)});
