const {test,expect}=require('playwright/test');
const {APP}=require('./helpers/app-target');
const task=(id,extra={})=>({id,parentId:'',state:'未着手',impact:'',title:`Task ${id}`,owner:'Owner',due:'2026-08-20',planned_duration_days:3,summary:'',repeat:'',completed:false,source:'',asana_task_id:'',history:[],dependencies:[],sortOrder:Number(id.replace(/\D/g,''))*1000||1000,...extra});
const items=()=>Array.from({length:80},(_,i)=>{const d=new Date(Date.UTC(2026,7,1+i));return task(`T${i+1}`,{due:d.toISOString().slice(0,10)})});
async function boot(page){await page.setViewportSize({width:900,height:520});await page.goto(APP);await page.evaluate(()=>localStorage.clear());await page.reload();await page.evaluate(xs=>{applyJsonObject({schema_version:'1.8',items:xs},'sticky','sticky.json',null,{remember:false,writePermissionGranted:false});const spacer=document.createElement('div');spacer.id='stickyTestSpacer';spacer.style.height='900px';document.body.appendChild(spacer)},items())}
async function stick(page,host){await page.evaluate(sel=>window.scrollTo(0,document.querySelector(sel).getBoundingClientRect().top+scrollY+180),host);await page.waitForTimeout(50)}

test('STICKY-LIST-01: ToDo Listはviewport上端で固定し上下端・横scroll・編集を維持',async({page})=>{
  await boot(page);await page.locator('#dmTodoTree').click();await stick(page,'#listView');const layer=page.locator('.viewportStickyHeaderList');await expect(layer).toBeVisible();expect(Math.abs((await layer.boundingBox()).y)).toBeLessThanOrEqual(1);await page.locator('#listView').evaluate(el=>el.scrollLeft=120);await page.waitForTimeout(30);const transform=await layer.locator('table').evaluate(el=>getComputedStyle(el).transform);expect(transform).not.toBe('none');const title=page.locator('#row_T10 .titleText');await title.click();await expect(title).toBeFocused();await page.evaluate(()=>window.scrollTo(0,0));await page.waitForTimeout(30);await expect(layer).toBeHidden();
  await page.evaluate(()=>window.scrollTo(0,document.querySelector('#listView').getBoundingClientRect().bottom+scrollY+100));await page.waitForTimeout(30);await expect(page.locator('.viewportStickyHeaderList')).toBeHidden();
});

test('STICKY-GANTT-01: 左headerと日付headerを一体固定し横scroll・resize・bottom dockと共存',async({page})=>{
  await boot(page);await page.locator('#dmProjectDetail').click();await page.evaluate(()=>setMode('team'));await stick(page,'#ganttView');const head=page.locator('#ganttView .ganttHeader'),top=page.locator('#ganttView .projectTopDraftRow');await expect(head).toHaveClass(/hqaLiveSticky/);await expect(top).toHaveClass(/hqaLiveSticky/);expect(Math.abs((await head.boundingBox()).y)).toBeLessThanOrEqual(1);await expect(head.locator('.projectInfoTable')).toBeVisible();await expect(head.locator('.ganttDates')).toBeVisible();await page.evaluate(()=>setGanttTimelineScroll(220));await page.waitForTimeout(30);expect(await head.locator('.ganttTimelineClip>.ganttTimeline').evaluate(el=>el.style.transform)).toContain('-');const before=await head.locator('.ganttTaskHead').boundingBox();await page.evaluate(()=>{projectWidths.title+=35;applyUnifiedProjectWidths()});await page.waitForTimeout(30);expect((await head.locator('.ganttTaskHead').boundingBox()).width-before.width).toBeCloseTo(35,0);await expect(page.locator('.ganttScrollDock')).toHaveCount(1);
});

test('STICKY-GANTT-02: Gantt末尾ではghost headerを残さない',async({page})=>{await boot(page);await page.locator('#dmProjectDetail').click();await page.evaluate(()=>setMode('team'));await stick(page,'#ganttView');await expect(page.locator('#ganttView .ganttHeader')).toHaveClass(/hqaLiveSticky/);await page.evaluate(()=>window.scrollTo(0,document.querySelector('#ganttView').getBoundingClientRect().bottom+scrollY+100));await page.waitForTimeout(30);await expect(page.locator('#ganttView .ganttHeader')).not.toHaveClass(/hqaLiveSticky/)});
