const {test,expect}=require('playwright/test');
const {APP}=require('./helpers/app-target');
const task=(id,extra={})=>({id,parentId:'',state:'未着手',impact:'',title:id,owner:'担当',due:'2026-08-20',summary:'',repeat:'',completed:false,source:'',asana_task_id:'',history:[],dependencies:[],sortOrder:1000,...extra});
async function fresh(page,items=[],mode='personal'){await page.setViewportSize({width:1200,height:700});await page.goto(APP);await page.evaluate(()=>localStorage.clear());await page.reload();await expect(page.locator('body')).not.toHaveClass(/dbBooting/);await page.evaluate(xs=>applyJsonObject({schema_version:'1.9',items:xs},'rc','rc.json',null,{remember:false,writePermissionGranted:false}),items);await page.evaluate(m=>setMode(m),mode);await page.waitForTimeout(60)}

test('RC recurrence UI disables dependency participants, allows valid parent checklist, and rejects as true no-op',async({page})=>{await fresh(page,[task('A'),task('B',{dependencies:[{task_id:'A',type:'finish_to_start'}],sortOrder:2000}),task('P',{sortOrder:3000}),task('C',{parentId:'P',due:'',sortOrder:4000})]);for(const id of['A','B']){const select=page.locator(`#row_${id} .repeatSel`);await expect(select).toBeDisabled();await expect(select).toHaveClass(/recurrenceUnavailable/);expect(await select.getAttribute('title')).toBeTruthy()}for(const id of['P','C'])await expect(page.locator(`#row_${id} .repeatSel`)).toBeEnabled();const before=await page.evaluate(()=>({json:JSON.stringify(data.items),dirty,undo:undoStack.length,y:scrollY,timeline:ganttTimelineScrollLeft}));const result=await page.evaluate(()=>{let renders=0;const base=render;render=()=>{renders++;return base()};const ok=commitRepeatChange(0,'毎日',{type:'daily'});return{ok,renders,json:JSON.stringify(data.items),dirty,undo:undoStack.length,y:scrollY,timeline:ganttTimelineScrollLeft}});expect(result).toEqual({...before,ok:false,renders:0})});

test('RC legacy-invalid repeating task remains clearable but cannot switch to another non-empty rule',async({page})=>{await fresh(page,[task('A',{repeat:'毎日',recurrence_rule:{type:'daily'}}),task('B',{dependencies:[{task_id:'A',type:'finish_to_start'}],sortOrder:2000})]);const select=page.locator('#row_A .repeatSel');await expect(select).toBeEnabled();await select.selectOption('毎週');await expect(page.locator('#recurrenceEditorBack')).toHaveCount(0);expect(await page.evaluate(()=>itemById('A').repeat)).toBe('毎日');await select.selectOption('');expect(await page.evaluate(()=>({repeat:itemById('A').repeat,rule:itemById('A').recurrence_rule}))).toEqual({repeat:'',rule:undefined})});

test('RC bimonthly odd/even date and weekday rules preserve intent from previous due',async({page})=>{await fresh(page);const got=await page.evaluate(()=>{const n=(due,rule)=>nextRecurringDue({due,repeat:'隔月',recurrence_rule:rule});const odd={type:'bimonthly',parity:'odd',mode:'date',day:31},even={type:'bimonthly',parity:'even',mode:'date',day:31},friday={type:'bimonthly',parity:'even',mode:'weekday',ordinal:'last',weekday:5};return{odd1:n('2026-01-31',odd),odd2:n('2026-03-31',odd),evenMismatch:n('2026-01-31',even),evenNext:n('2026-02-28',even),friday:n('2026-02-27',friday),parityMismatch:n('2026-08-15',{type:'bimonthly',parity:'odd',mode:'date',day:15}),last:n('2026-01-31',{type:'bimonthly',parity:'even',mode:'date',day:'last'})}});expect(got).toEqual({odd1:'2026-03-31',odd2:'2026-05-31',evenMismatch:'2026-02-28',evenNext:'2026-04-30',friday:'2026-04-24',parityMismatch:'2026-09-15',last:'2026-02-28'})});

test('RC bimonthly dialog reopens, edits and Undo/Redo as one action',async({page})=>{await fresh(page,[task('A',{due:'2026-08-15'})]);await page.locator('#row_A .repeatSel').selectOption('隔月');await expect(page.locator('input[name="recParity"]')).toHaveCount(2);await page.locator('input[name="recParity"][value="odd"]').check();await page.locator('input[name="recMonthMode"][value="weekday"]').check();await page.locator('#recOrdinal').selectOption('last');await page.locator('#recWeekday').selectOption('5');await page.locator('.recurrenceEditor .pri').click();expect(await page.evaluate(()=>itemById('A').recurrence_rule)).toEqual({type:'bimonthly',parity:'odd',mode:'weekday',ordinal:'last',weekday:5});expect(await page.evaluate(()=>undoStack.length)).toBe(1);await page.locator('#row_A .recurrenceSettings').click();await expect(page.locator('input[name="recParity"][value="odd"]')).toBeChecked();await page.locator('.recurrenceEditor button',{hasText:'キャンセル'}).click();await page.evaluate(()=>performUndo());expect(await page.evaluate(()=>itemById('A').repeat)).toBe('');await page.evaluate(()=>performRedo());expect(await page.evaluate(()=>itemById('A').recurrence_rule)).toEqual({type:'bimonthly',parity:'odd',mode:'weekday',ordinal:'last',weekday:5})});

test('RC blank task supports bimonthly configuration',async({page})=>{await fresh(page);await page.locator('#b_repeat').selectOption('隔月');await page.locator('input[name="recParity"][value="even"]').check();await page.locator('#recMonthDay').selectOption('31');await page.locator('.recurrenceEditor .pri').click();await page.locator('#b_title').fill('new');await page.locator('#b_due').fill('2026/08/15');await page.evaluate(()=>commitBlank(true));expect(await page.evaluate(()=>data.items.find(x=>x.title==='new').recurrence_rule)).toEqual({type:'bimonthly',parity:'even',mode:'date',day:31})});

test('RC owner Enter commits once and leaves Project editing without scroll; Gantt editor remains Enter-committable',async({page})=>{await fresh(page,[task('A')],'team');await page.evaluate(()=>setProjectView('list'));await page.evaluate(()=>window.scrollTo(0,120));const input=page.locator('#row_A .ownerInput');await input.fill('project');const before=await page.evaluate(()=>({y:scrollY,undo:undoStack.length}));await input.press('Enter');await expect(input).not.toBeFocused();await expect.poll(()=>page.evaluate(()=>undoStack.length)).toBe(before.undo+1);expect(await page.evaluate(()=>({owner:itemById('A').owner,y:scrollY}))).toEqual({owner:'project',y:before.y});await page.evaluate(()=>{const cell=document.createElement('div');cell.id='rcGanttOwner';document.body.appendChild(cell);openGanttOwnerEditor(cell,'A')});const edit=page.locator('#rcGanttOwner input');await edit.fill('gantt');await edit.press('Enter');expect(await page.evaluate(()=>itemById('A').owner)).toBe('gantt')});

test('RC ordinary recurrence render preserves page and Gantt date anchor',async({page})=>{await fresh(page,[task('A',{due:'2026-08-15',planned_duration_days:2}),task('B',{due:'2030-01-01',planned_duration_days:2,sortOrder:2000})],'team');await page.evaluate(()=>{setProjectView('gantt');setGanttTimelineScroll(420);window.scrollTo(0,160)});const before=await page.evaluate(()=>rcCaptureViewport());await page.evaluate(()=>openRecurrenceEditor(0,'毎週'));await page.locator('input[name="recWeekday"][value="1"]').check();await page.locator('.recurrenceEditor .pri').click();const after=await page.evaluate(()=>rcCaptureViewport());expect(Math.abs(after.pageY-before.pageY)).toBeLessThanOrEqual(1);expect(Math.abs(after.anchorDay-before.anchorDay)).toBeLessThan(0.05);expect(after.outerLeft).toBe(before.outerLeft)});

test('RC owner, summary, planned and same-rank due edits preserve viewport/date anchor',async({page})=>{await fresh(page,[task('A',{due:'2026-08-15',planned_duration_days:2}),task('B',{due:'2030-01-01',planned_duration_days:2,sortOrder:2000})],'team');await page.evaluate(()=>{setProjectView('gantt');setGanttTimelineScroll(360);window.scrollTo(0,140)});const before=await page.evaluate(()=>rcCaptureViewport());await page.evaluate(()=>{chg(0,'owner','owner2');chg(0,'summary','summary2');changePlannedDuration(0,'3');const old=displaySortIndex('A');sortMoveAnimationArmed='due';itemById('A').due='2026-08-16';applyPostSortMove('A',old);render();sortMoveAnimationArmed=''});const after=await page.evaluate(()=>rcCaptureViewport());expect(Math.abs(after.pageY-before.pageY)).toBeLessThanOrEqual(1);expect(Math.abs(after.anchorDay-before.anchorDay)).toBeLessThan(0.05);await expect(page.locator('.sortMoveAnimating')).toHaveCount(0)});

async function armMove(page,id,due){return page.evaluate(({id,due})=>{const before=displaySortIndex(id);sortMoveAnimationArmed='rc-test';itemById(id).due=due;applyPostSortMove(id,before);render();sortMoveAnimationArmed='';return Array.from(document.querySelectorAll('.sortMoveAnimating')).map(row=>({id:row.dataset.taskId||row.id.replace(/^row_/,''),delta:Number(row.dataset.sortMoveDelta),transition:row.style.transition}))},{id,due})}

test('RC multi-row FLIP downward animates edited and displaced rows only for 2240ms',async({page})=>{await fresh(page,['A','B','C','D','E'].map((id,i)=>task(id,{due:`2026-08-0${i+1}`,planned_duration_days:1,sortOrder:(i+1)*1000})),'team');const rows=await armMove(page,'B','2026-08-06');expect(rows.map(x=>x.id).sort()).toEqual(['B','C','D','E']);expect(rows.find(x=>x.id==='B').delta).toBeLessThan(0);for(const id of['C','D','E'])expect(rows.find(x=>x.id===id).delta).toBeGreaterThan(0);expect(rows.some(x=>x.id==='A')).toBe(false);await page.waitForTimeout(40);await expect(page.locator('.sortMoveAnimating').first()).toHaveCSS('transition-duration','2.24s')});

test('RC reordered row follows minimally only after becoming fully offscreen',async({page})=>{await page.setViewportSize({width:1000,height:420});await fresh(page,Array.from({length:30},(_,i)=>task(String(i+1),{due:`2026-08-${String(i+1).padStart(2,'0')}`,planned_duration_days:1,sortOrder:(i+1)*1000})),'team');const start=await page.evaluate(()=>scrollY);await armMove(page,'1','2026-09-15');expect(await page.evaluate(()=>scrollY)).toBe(start);await page.waitForTimeout(2400);const result=await page.evaluate(()=>{const r=renderedTaskRow('1').getBoundingClientRect();return{y:scrollY,top:r.top,bottom:r.bottom,h:innerHeight}});expect(result.y).toBeGreaterThan(start);expect(result.bottom).toBeLessThanOrEqual(result.h+1);expect(result.top).toBeGreaterThan(result.h/2)});

test('RC multi-row FLIP upward and hierarchy block move in coherent directions',async({page})=>{await fresh(page,['A','B','C','D','E'].map((id,i)=>task(id,{due:`2026-08-0${i+1}`,planned_duration_days:1,sortOrder:(i+1)*1000})),'team');let rows=await armMove(page,'E','2026-07-31');expect(rows.find(x=>x.id==='E').delta).toBeGreaterThan(0);for(const id of['A','B','C','D'])expect(rows.find(x=>x.id===id).delta).toBeLessThan(0);await fresh(page,[task('X',{due:'2026-08-01',planned_duration_days:1}),task('P',{due:'2026-08-02',planned_duration_days:1,sortOrder:2000}),task('C',{parentId:'P',due:'2026-08-03',planned_duration_days:1,sortOrder:3000}),task('G',{parentId:'C',due:'2026-08-04',planned_duration_days:1,sortOrder:4000}),task('Z',{due:'2026-08-05',planned_duration_days:1,sortOrder:5000})],'team');rows=await armMove(page,'P','2026-08-06');const block=['P','C','G'].map(id=>rows.find(x=>x.id===id)?.delta);expect(block.every(Number.isFinite)).toBe(true);expect(new Set(block).size).toBe(1)});

test('RC reduced motion is safe and HQA2.3 conflict Arrow remains navigation',async({page})=>{await page.emulateMedia({reducedMotion:'reduce'});await fresh(page,[task('A',{due:'2026-08-01',planned_duration_days:1}),task('B',{due:'2026-08-02',planned_duration_days:1,dependencies:[{task_id:'A',type:'finish_to_start'}],sortOrder:2000}),task('C',{due:'2026-08-03',planned_duration_days:1,sortOrder:3000})],'team');await armMove(page,'C','2026-07-31');await expect(page.locator('.sortMoveAnimating')).toHaveCount(0);await page.evaluate(()=>setProjectView('gantt'));const conflict=page.locator('.ganttConflictItem').first();if(await conflict.count()){await conflict.click();const y=await page.evaluate(()=>scrollY);await page.keyboard.press('ArrowDown');expect(await page.evaluate(()=>scrollY)).toBe(y)}});

test('RC 1680x900 disabled recurrence, bimonthly dialog and FLIP visual states',async({page})=>{await page.setViewportSize({width:1680,height:900});await fresh(page,[task('A'),task('B',{dependencies:[{task_id:'A',type:'finish_to_start'}],sortOrder:2000}),task('C',{due:'2026-08-03',planned_duration_days:1,sortOrder:3000})],'team');await page.screenshot({path:'test-results/rc-recurrence-disabled.png'});await page.locator('#row_C .repeatSel').selectOption('隔月');await expect(page.locator('.recurrenceEditor')).toBeVisible();await page.screenshot({path:'test-results/rc-bimonthly-dialog.png'});await page.locator('.recurrenceEditor button',{hasText:'キャンセル'}).click();await fresh(page,['A','B','C','D','E'].map((id,i)=>task(id,{due:`2026-08-0${i+1}`,planned_duration_days:1,sortOrder:(i+1)*1000})),'team');await armMove(page,'B','2026-08-06');await page.waitForTimeout(500);await page.screenshot({path:'test-results/rc-multi-row-flip.png'});await expect(page.locator('.sortMoveAnimating')).toHaveCount(4)});
