const {test,expect}=require('playwright/test');
const APP='/asanya_task_manager_v200.html';
const task=(id,extra={})=>({id,parentId:'',state:'',impact:'',title:id,owner:'',due:'2026-08-31',planned_duration_days:1,summary:'',repeat:'',completed:false,source:'',asana_task_id:'',history:[],dependencies:[],sortOrder:1000,...extra});
async function boot(page,mode='personal'){await page.goto(APP);await page.evaluate(()=>localStorage.clear());await page.reload();await page.evaluate(({items,mode})=>{applyJsonObject({schema_version:'2.0',items},'f2','f2.json',null,{remember:false,writePermissionGranted:false});setView('all');setMode(mode);clearUndoHistory('f2')},{items:[task('A'),task('B',{sortOrder:2000})],mode})}
const title=(page,id)=>page.locator(`${id==='A'?'#row_A':'.ganttRow[data-task-id="'+id+'"]'} .titleText`);

test('F2-01 ToDo selected task focuses existing title editor',async({page})=>{await boot(page);await page.evaluate(()=>selectTask('A'));await page.keyboard.press('F2');await expect(page.locator('#row_A .titleText')).toBeFocused();expect(await page.evaluate(()=>selectedTaskId)).toBe('A')});

test('F2-02 Project selected task focuses unified existing title editor',async({page})=>{await boot(page,'team');await page.evaluate(()=>selectTask('A'));await page.keyboard.press('F2');await expect(page.locator('.ganttRow[data-task-id="A"] .titleText')).toBeFocused()});

test('F2-03 no selection is a complete no-op',async({page})=>{await boot(page);const before=await page.evaluate(()=>({json:JSON.stringify(data.items),draft:draftTaskId,undo:undoStack.length}));await page.evaluate(()=>{selectedTaskId='';render()});await page.keyboard.press('F2');expect(await page.evaluate(()=>({json:JSON.stringify(data.items),draft:draftTaskId,undo:undoStack.length}))).toEqual(before)});

test('F2-04 active Due and owner editors keep ownership',async({page})=>{await boot(page);await page.evaluate(()=>selectTask('A'));await page.locator('#row_A .dueTxt').click();const due=page.locator('#row_A input[type=text]');await due.focus();await page.keyboard.press('F2');await expect(due).toBeFocused();await boot(page,'team');await page.evaluate(()=>selectTask('A'));const owner=page.locator('.ganttRow[data-task-id="A"] .ownerInput');await owner.focus();await page.keyboard.press('F2');await expect(owner).toBeFocused()});

test('F2-05 already editing title does not duplicate or corrupt editor',async({page})=>{await boot(page);await page.evaluate(()=>selectTask('A'));await page.keyboard.press('F2');const el=page.locator('#row_A .titleText');await el.fill('編集中');await page.keyboard.press('F2');await expect(el).toBeFocused();await expect(el).toHaveText('編集中');await expect(page.locator('#row_A .titleText')).toHaveCount(1)});

test('F2-06/F2-07 Enter commit, Escape cancel, Undo/Redo retain existing semantics',async({page})=>{await boot(page);await page.evaluate(()=>selectTask('A'));await page.keyboard.press('F2');let el=page.locator('#row_A .titleText');await el.fill('変更後');await el.press('Enter');expect(await page.evaluate(()=>itemById('A').title)).toBe('変更後');expect(await page.evaluate(()=>undoStack.length)).toBe(1);await page.keyboard.press('Control+z');expect(await page.evaluate(()=>itemById('A').title)).toBe('A');await page.keyboard.press('Control+y');expect(await page.evaluate(()=>itemById('A').title)).toBe('変更後');await page.keyboard.press('F2');el=page.locator('#row_A .titleText');await el.fill('取消値');await el.press('Escape');expect(await page.evaluate(()=>itemById('A').title)).toBe('変更後')});

test('F2-08 IME composition remains normal after shortcut entry',async({page})=>{await boot(page);await page.evaluate(()=>selectTask('A'));await page.keyboard.press('F2');const el=page.locator('#row_A .titleText');await el.dispatchEvent('compositionstart',{data:'日'});await el.evaluate(node=>{node.textContent='日本語';node.dispatchEvent(new InputEvent('input',{bubbles:true,data:'日本語',inputType:'insertCompositionText'}));node.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',isComposing:true,keyCode:229,bubbles:true,cancelable:true}))});expect(await page.evaluate(()=>itemById('A').title)).toBe('A');await el.dispatchEvent('compositionend',{data:'日本語'});await el.press('Enter');expect(await page.evaluate(()=>itemById('A').title)).toBe('日本語')});

test('F2-09 dependency candidate workflow is preserved',async({page})=>{await boot(page,'team');await page.evaluate(()=>{relationOpenId='A';toggleRelation({stopPropagation(){}},'A');beginDependencyAdd('predecessor')});await expect(page.locator('#relationPopup')).toBeVisible();await page.keyboard.press('F2');expect(await page.evaluate(()=>({open:relationOpenId,direction:relationFormDirection,candidate:relationSelectedTaskId}))).toEqual({open:'A',direction:'predecessor',candidate:''});await expect(page.locator('.ganttRow[data-task-id="A"] .titleText')).not.toBeFocused()});
