const {test,expect}=require('playwright/test');
const {installFsAccessMock}=require('./helpers/fs-access-mock');
const {APP}=require('./helpers/app-target');
const isV250=APP.includes('v250');
const task=id=>({id,parentId:'',state:'',impact:'',title:id,owner:'',due:'',summary:'',repeat:'',completed:false,source:'',asana_task_id:'',history:[],dependencies:[],sortOrder:1000});
const json=(items,schema=isV250?'2.5':'1.8')=>JSON.stringify({schema_version:schema,...(schema==='2.5'?{workspace_info_markdown:''}:{}),items});
async function boot(page){await installFsAccessMock(page);await page.goto(APP);await page.evaluate(async()=>{localStorage.clear();if(indexedDB.databases)for(const db of await indexedDB.databases())indexedDB.deleteDatabase(db.name)});await page.reload()}
async function file(page,id,options){await page.evaluate(({id,options})=>__fsMock.create(id,options),{id,options})}
async function restore(page,id,name,handle=true){await page.evaluate(({id,name,handle})=>{const h=handle?__fsMock.handle(id):null;getLastDbRecord=async()=>({name,handle:h});window.__startup=restoreLastDbOnStartup()},{id,name,handle});await page.evaluate(()=>window.__startup)}
const state=page=>page.evaluate(()=>({loaded:dbDataLoaded,saveState,name:currentDbName,remembered:rememberedDbHandle?.__mockId||null,items:data.items.map(x=>x.id),undo:undoStack.length,redo:redoStack.length,timer:!!autoSaveTimer}));
test.beforeEach(async({page})=>boot(page));

test('STARTUP-01: recordなしは通常2択、handleなしは再選択resumeで編集不可',async({page})=>{await expect(page.locator('#dbStartScreen button:visible')).toHaveCount(2);await restore(page,'none','known.json',false);await expect(page.locator('#dbStartResumeName')).toHaveText('known.json');await expect(page.getByRole('button',{name:'前回DBを選択'})).toBeVisible();await expect(page.getByRole('button',{name:'別のDBを開く'})).toBeVisible();expect(await state(page)).toMatchObject({loaded:false,saveState:'resume',name:'known.json',items:[],timer:false})});

test('STARTUP-02: readwrite grantedはdisk最新値を自動再開しautosave可能',async({page})=>{await file(page,'last',{name:'last.json',text:json([task('LATEST')]),readPermission:'granted',writePermission:'granted'});await page.evaluate(()=>{undoStack.push({x:1});redoStack.push({x:1})});await restore(page,'last','last.json');expect(await state(page)).toMatchObject({loaded:true,saveState:'saved',name:'last.json',remembered:'last',items:['LATEST'],undo:0,redo:0});await expect(page.locator('#dbStartScreen')).toBeHidden();await expect(page.getByRole('button',{name:'書込許可'})).toHaveCount(0);expect(await page.evaluate(()=>({writePermissionGranted,direct:directSaveAvailable()}))).toEqual({writePermissionGranted:true,direct:true});await page.evaluate(()=>chg(0,'title','UPDATED'));await expect.poll(()=>page.evaluate(()=>JSON.parse(__fsMock.snapshot('last').text).items[0].title),{timeout:5000}).toBe('UPDATED')});

test('STARTUP-03: read granted/write promptはresume、1クリックreadwrite許可で同handleを開く',async({page})=>{await file(page,'prompt',{name:'prompt.json',text:json([task('P')]),readPermission:'granted',writePermission:'prompt',requestWriteResult:'granted'});await restore(page,'prompt','prompt.json');await expect(page.locator('#dbStartResumeName')).toHaveText('prompt.json');expect(await state(page)).toMatchObject({loaded:false,saveState:'resume',remembered:'prompt',items:[]});expect((await page.evaluate(()=>__fsMock.calls())).filter(x=>x.op==='requestPermission')).toHaveLength(0);await page.getByRole('button',{name:'前回DBを再開'}).click();await expect(page.getByRole('button',{name:'DBを開かない'})).toBeVisible();await page.locator('#pok').click();await expect(page.locator('#dbStartScreen')).toBeHidden();expect(await state(page)).toMatchObject({loaded:true,name:'prompt.json',items:['P']});expect(await page.evaluate(()=>({writePermissionGranted,direct:directSaveAvailable()}))).toEqual({writePermissionGranted:true,direct:true});const calls=await page.evaluate(()=>__fsMock.calls());expect(calls.filter(x=>x.op==='requestPermission')).toEqual([expect.objectContaining({id:'prompt',mode:'readwrite'})]);expect(calls.filter(x=>x.op==='showOpenFilePicker')).toHaveLength(0)});

test('STARTUP-04: denied/cancelはhandleとresume UIを維持しdiskを変更しない',async({page})=>{for(const action of ['cancel','denied']){await file(page,action,{name:action+'.json',text:json([task('D')]),readPermission:'granted',writePermission:'prompt',requestWriteResult:'denied'});const before=await page.evaluate(id=>__fsMock.snapshot(id),action);await restore(page,action,action+'.json');await page.getByRole('button',{name:'前回DBを再開'}).click();if(action==='cancel')await page.locator('#pcancel').click();else await page.locator('#pok').click();expect(await state(page)).toMatchObject({loaded:false,saveState:'resume',remembered:action,items:[]});await expect(page.getByRole('button',{name:'前回DBを再開'})).toBeVisible();const after=await page.evaluate(id=>__fsMock.snapshot(id),action);expect(after.text).toBe(before.text);expect(after.writeCount).toBe(before.writeCount)}});

test('STARTUP-06: picker DBはreadwrite許可成功時だけloaded、拒否時は選択前状態',async({page})=>{await file(page,'open-ok',{name:'open-ok.json',text:json([task('O')]),readPermission:'granted',writePermission:'granted'});await page.evaluate(()=>__fsMock.queueOpen('open-ok'));await page.locator('#startDbReadBtn').click();await expect(page.locator('#dbStartScreen')).toBeHidden();expect(await page.evaluate(()=>({ids:data.items.map(x=>x.id),writePermissionGranted,direct:directSaveAvailable()}))).toEqual({ids:['O'],writePermissionGranted:true,direct:true});await file(page,'open-no',{name:'open-no.json',text:json([task('NO')]),readPermission:'granted',writePermission:'prompt',requestWriteResult:'denied'});await page.evaluate(()=>__fsMock.queueOpen('open-no'));await page.locator('#dbReadBtn').click();await page.locator('#pok').click();await expect(page.locator('#dbStartScreen')).toBeHidden();expect(await page.evaluate(()=>({ids:data.items.map(x=>x.id),name:currentDbName}))).toEqual({ids:['O'],name:'open-ok.json'})});

test('STARTUP-05: malformed/newer Schemaはresume安全状態でdiskへ書かない',async({page})=>{for(const [id,text] of [['bad','{bad'],['newer',json([task('N')],'9.0')]]){await file(page,id,{name:id+'.json',text,readPermission:'granted',writePermission:'granted'});const before=await page.evaluate(id=>__fsMock.snapshot(id),id);await restore(page,id,id+'.json');expect(await state(page)).toMatchObject({loaded:false,saveState:'resume',remembered:id,items:[]});const after=await page.evaluate(id=>__fsMock.snapshot(id),id);expect(after.text).toBe(before.text);expect(after.writeCount).toBe(before.writeCount)}});
