const {test,expect}=require('playwright/test');
const {APP}=require('./helpers/app-target');
test.setTimeout(90000);
const task=(id,due,duration=1,sortOrder=1000)=>({id,parentId:'',state:'未着手',impact:'',title:id,owner:'',due,planned_duration_days:duration,summary:'',repeat:'',completed:false,source:'',asana_task_id:'',history:[],dependencies:[],sortOrder});
async function boot(page,items,view='gantt'){await page.emulateMedia({reducedMotion:'no-preference'});await page.goto(APP);await page.evaluate(()=>localStorage.clear());await page.reload();await page.evaluate(xs=>{applyJsonObject({schema_version:'1.8',items:xs},'undo-animation','undo-animation.json',null,{remember:false,writePermissionGranted:false});clearUndoHistory('undo-animation-test')},items);if(view!=='todo')await page.locator('#mTeam').click();if(view==='gantt')await page.evaluate(()=>setMode('team'))}
const ganttRow=(page,id)=>page.locator(`.ganttRow[data-task-id="${id}"]`);
async function editGanttDue(page,id,value){await ganttRow(page,id).locator('.ganttDue').click();const input=ganttRow(page,id).locator('.ganttDueText');await input.fill(value);await input.press('Enter')}
async function expectAnimation(page,id,kind){const row=ganttRow(page,id);await expect(row).toHaveClass(/sortMoveAnimating/);await expect(row).toHaveAttribute('data-sort-move-kind',kind)}
async function waitAnimation(page,id){await expect(ganttRow(page,id)).not.toHaveClass(/sortMoveAnimating/,{timeout:3000})}
async function dragDays(page,locator,days){await locator.scrollIntoViewIfNeeded();const b=await locator.boundingBox();if(!b)throw Error('drag target missing');await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.down();await page.mouse.move(b.x+b.width/2+days*28,b.y+b.height/2,{steps:8});await page.mouse.up()}

test('UNDO-SORT-01: Gantt d→1→Undo→d→1を3回繰返してもshortcut runtimeがdead化しない',async({page})=>{await boot(page,[task('A','2026-08-20'),task('B','2026-08-15',1,2000)]);const tomorrow=await page.evaluate(()=>addDays(ymd(),1));for(let n=0;n<3;n++){await ganttRow(page,'A').locator('.ganttDue').click();let input=ganttRow(page,'A').locator('.ganttDueText');await input.press('d');await input.press('1');expect(await page.evaluate(()=>itemById('A').due)).toBe(tomorrow);await page.keyboard.press('Control+z');expect(await page.evaluate(()=>itemById('A').due)).toBe('2026-08-20');const clean=await page.evaluate(()=>({active:activeUndoEditor,armed:dateShortcutArmed,target:dateShortcutTargetInput,ime:imeCompositionTarget,detached:!!activeUndoEditor&&!document.contains(activeUndoEditor)}));expect(clean).toEqual({active:null,armed:false,target:null,ime:null,detached:false});await page.keyboard.press('d');await page.keyboard.press('1');input=ganttRow(page,'A').locator('.ganttDueText');await expect(input).toBeFocused();await input.press('Enter');expect(await page.evaluate(()=>itemById('A').due)).toBe(tomorrow);await page.keyboard.press('Control+z');expect(await page.evaluate(()=>itemById('A').due)).toBe('2026-08-20')}});

test('UNDO-SORT-02: due変更のUndo/Redoはreverse/forward FLIPし2240ms後にcleanup',async({page})=>{await boot(page,[task('A','2026-08-20'),task('B','2026-08-15',1,2000)]);const initialTimeline=await page.evaluate(()=>ganttTimelineScrollLeft);await editGanttDue(page,'A','2026-08-10');await expectAnimation(page,'A','due');const row=ganttRow(page,'A');expect(await row.evaluate(el=>getComputedStyle(el).transitionDuration)).toBe('2.24s');await page.waitForTimeout(1000);await expect(row).toHaveClass(/sortMoveAnimating/);await waitAnimation(page,'A');await page.keyboard.press('Control+z');await expectAnimation(page,'A','due-undo');expect(await page.evaluate(()=>ganttTimelineScrollLeft)).toBe(initialTimeline);await waitAnimation(page,'A');await page.keyboard.press('Control+y');await expectAnimation(page,'A','due-redo');await waitAnimation(page,'A');await expect(row).not.toHaveAttribute('style',/transform|transition/)});

test('UNDO-SORT-03: durationのUndo/Redoだけsort変化時にFLIPしtitle/editor Undoは対象外',async({page})=>{await boot(page,[task('A','2026-08-20',1),task('B','2026-08-15',1,2000)] ,'gantt');let input=ganttRow(page,'A').locator('.plannedDays');await input.fill('10');await input.press('Enter');await expect(ganttRow(page,'A')).toHaveClass(/sortMoveAnimating/);await expect(ganttRow(page,'A')).not.toHaveClass(/sortMoveAnimating/);await page.keyboard.press('Control+z');await expect(ganttRow(page,'A')).toHaveAttribute('data-sort-move-kind','undo');await expect(ganttRow(page,'A')).not.toHaveClass(/sortMoveAnimating/);await page.keyboard.press('Control+y');await expect(ganttRow(page,'A')).toHaveAttribute('data-sort-move-kind','redo');await expect(ganttRow(page,'A')).not.toHaveClass(/sortMoveAnimating/);const title=ganttRow(page,'A').locator('.titleText');await title.click();await title.pressSequentially('X');await page.keyboard.press('Control+z');await expect(ganttRow(page,'A')).not.toHaveClass(/sortMoveAnimating/)});

test('UNDO-SORT-04: reduced motionは即時cleanup、List/ToDoの未確定due Ctrl+Z semantics維持',async({page})=>{await boot(page,[task('A','2026-08-20'),task('B','2026-08-15',1,2000)],'todo');await page.emulateMedia({reducedMotion:'reduce'});await page.locator('#row_A .dueTxt').click();let input=page.locator('#row_A input[id^="d"]');await input.fill('2026-08-10');await input.press('Enter');await expect(page.locator('#row_A')).not.toHaveClass(/sortMoveAnimating/);await page.locator('#row_A .dueTxt').click();input=page.locator('#row_A input[id^="d"]');await input.fill('2026-08-12');const history=await page.evaluate(()=>undoStack.length);await page.keyboard.press('Control+z');expect(await page.evaluate(()=>undoStack.length)).toBe(history);expect(await page.evaluate(()=>itemById('A').due)).toBe('2026-08-10')});

test('UNDO-SORT-05: calendar・plan・milestone・due-only dragのUndo/Redoも共通FLIP',async({page})=>{const scenarios=[{kind:'calendar',dueAction:true,items:[task('A','2026-08-20'),task('B','2026-08-15',1,2000)],act:async()=>{await ganttRow(page,'A').locator('.ganttDue .dueTxt').click();await ganttRow(page,'A').locator('.ganttDueCalendar').evaluate(el=>{el.value='2026-08-10';el.dispatchEvent(new Event('change',{bubbles:true}))})}},{kind:'plan',items:[task('A','2026-08-20'),task('B','2026-08-15',1,2000)],act:()=>dragDays(page,page.locator('.ganttBar[data-task-id="A"]'),-10)},{kind:'milestone',items:[task('A','2026-08-22',0),task('B','2026-08-15',1,2000)],act:()=>dragDays(page,page.locator('.ganttMilestone[data-task-id="A"]'),-10)},{kind:'marker',dueAction:true,items:[(()=>{const x=task('A','2026-08-20');delete x.planned_duration_days;return x})(),task('B','2026-08-15',1,2000)],act:()=>dragDays(page,ganttRow(page,'A').locator('.ganttDueOnlyMarker'),-10)}];for(const s of scenarios){await boot(page,s.items);await s.act();await expect(ganttRow(page,'A')).toHaveClass(/sortMoveAnimating/);await waitAnimation(page,'A');await page.keyboard.press('Control+z');await expectAnimation(page,'A',s.dueAction?'due-undo':'undo');await waitAnimation(page,'A');await page.keyboard.press('Control+y');await expectAnimation(page,'A',s.dueAction?'due-redo':'redo');await waitAnimation(page,'A')}});
