const {test,expect}=require('playwright/test');
const {APP}=require('./helpers/app-target');
const task=(id,extra={})=>({id,parentId:'',state:'未着手',impact:'',title:`Task ${id}`,owner:'担当',due:'2026-08-20',planned_duration_days:3,summary:'',repeat:'',completed:false,source:'',asana_task_id:'',history:[],dependencies:[],sortOrder:(Number(String(id).replace(/\D/g,''))||1)*1000,...extra});
async function fresh(page,items=[task('1')]){await page.setViewportSize({width:1000,height:560});await page.goto(APP);await page.evaluate(()=>localStorage.clear());await page.reload();await page.evaluate(xs=>applyJsonObject({schema_version:'1.8',items:xs},'hqa2','hqa2.json',null,{remember:false,writePermissionGranted:false}),items);await page.evaluate(()=>setMode('team'));await expect(page.locator('#ganttView')).toBeVisible()}

test('HQA2-WIDTH-01: Summary 300 default, 620 migration, custom preservation',async({page})=>{await fresh(page);expect(await page.evaluate(()=>projectWidths.summary)).toBe(300);await page.evaluate(()=>localStorage.setItem('yos_project_cols_v1',JSON.stringify({title:517,owner:81,summary:620})));await page.reload();expect(await page.evaluate(()=>({...projectWidths}))).toMatchObject({title:517,owner:81,summary:300});expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('yos_project_cols_v1')))).toEqual({title:517,owner:81,summary:300});await page.evaluate(()=>localStorage.setItem('yos_project_cols_v1',JSON.stringify({title:517,summary:411})));await page.reload();expect(await page.evaluate(()=>({...projectWidths}))).toMatchObject({title:517,summary:411})});

test('HQA2-HEIGHT-01: Detail ON/OFF top row and timeline heights match',async({page})=>{await fresh(page);const measure=()=>page.evaluate(()=>{const r=document.querySelector('.projectTopDraftRow').getBoundingClientRect(),l=document.querySelector('.projectTopDraftRow>.ganttLeftPane').getBoundingClientRect(),c=document.querySelector('.projectTopDraftRow>.ganttTimelineClip').getBoundingClientRect();return{row:r.height,left:l.height,clip:c.height,head:document.querySelector('.ganttHeader').getBoundingClientRect().height}});const on=await measure();await page.locator('#projectDetailBtn').click();const off=await measure();expect(Math.abs(on.row-off.row)).toBeLessThanOrEqual(1);expect(Math.abs(on.left-on.clip)).toBeLessThanOrEqual(1);expect(Math.abs(off.left-off.clip)).toBeLessThanOrEqual(1);expect(on.head).toBe(off.head)});

test('HQA2-DATES-01: timeline only uses two-line YYYY and zero-padded MM/DD',async({page})=>{await fresh(page,[task('1',{state:'進行中',actual_start:'2015-01-02',actual_end:'2015-01-03'}),task('2',{due:'2027-01-03'})]);const labels=page.locator('.ganttHeader .ganttDate');await expect(labels.first().locator('.ganttDateYear')).toHaveText(/^\d{4}$/);await expect(labels.first().locator('.ganttDateMonthDay')).toHaveText(/^\d{2}\/\d{2}$/);expect(await labels.evaluateAll(xs=>xs.every(x=>x.children.length===2&&x.querySelector('.ganttDateYear')&&x.querySelector('.ganttDateMonthDay')))).toBe(true);expect(await page.evaluate(()=>ganttDateLabel('2026-08-15'))).toBe('8/15');const d=page.locator('.ganttDate',{hasText:'2026'}).filter({has:page.locator('.ganttDateMonthDay',{hasText:'08/15'})});await expect(d).toHaveCount(1)});

test('HQA2-TIMELINE-01: first view is today-7 and subsequent render/detail/resize preserve scroll',async({page})=>{await fresh(page,[task('old',{due:'2016-01-01'}),task('future',{due:'2030-01-01'})]);const initial=await page.evaluate(()=>{const today=calendarDateToDay(ymd()),marker=document.querySelector('.ganttHeader .ganttToday'),min=today-Math.round(parseFloat(marker.style.left)/GANTT_DAY_WIDTH);return{scroll:ganttTimelineScrollLeft,min,today,target:(today-7-min)*GANTT_DAY_WIDTH,old:calendarDateToDay('2016-01-01')}});expect(initial.min).toBeLessThanOrEqual(initial.old-2);expect(Math.abs(initial.scroll-initial.target)).toBeLessThanOrEqual(1);await page.evaluate(()=>setGanttTimelineScroll(ganttTimelineScrollLeft+123));const user=await page.evaluate(()=>ganttTimelineScrollLeft);await page.evaluate(()=>render());expect(await page.evaluate(()=>ganttTimelineScrollLeft)).toBe(user);await page.locator('#projectDetailBtn').click();expect(await page.evaluate(()=>ganttTimelineScrollLeft)).toBe(user);await page.evaluate(()=>{projectWidths.owner+=15;applyUnifiedProjectWidths()});expect(await page.evaluate(()=>ganttTimelineScrollLeft)).toBe(user)});

test('HQA2-GROWTH-01: multiline top Summary pushes rows and updates sticky spacer',async({page})=>{await fresh(page,Array.from({length:70},(_,i)=>task(String(i+1),{sortOrder:(i+1)*1000})));const top=page.locator('.projectTopDraftRow'),first=page.locator('.ganttRow[data-task-id="1"]');const before={top:(await top.boundingBox()).height,row:(await first.boundingBox()).y};await page.locator('#b_summary').fill('a\nb\nc\nd\ne');await expect.poll(()=>top.evaluate(el=>el.getBoundingClientRect().height)).toBeGreaterThan(before.top);const grown={top:(await top.boundingBox()).height,row:(await first.boundingBox()).y};expect(grown.row-before.row).toBeGreaterThanOrEqual(grown.top-before.top-1);await page.evaluate(()=>window.scrollTo(0,document.querySelector('.ganttHeader').getBoundingClientRect().top+scrollY+2));await expect(top).toHaveClass(/hqaLiveSticky/);const spacer=page.locator('.hqaStickySpacer'),oldSpacer=(await spacer.boundingBox()).height;await page.locator('#b_summary').fill('a\nb\nc\nd\ne\nf\ng\nh');await expect.poll(()=>spacer.evaluate(el=>el.getBoundingClientRect().height)).toBeGreaterThan(oldSpacer);const occupied=(await page.locator('.ganttHeader').boundingBox()).height+(await top.boundingBox()).height;expect(Math.abs((await spacer.boundingBox()).height-occupied)).toBeLessThanOrEqual(1)});

test('HQA2-DRAFT-01: IME Escape is reserved, next Escape cancels from Summary and select',async({page})=>{await fresh(page);await page.evaluate(()=>selectTask('1'));await page.keyboard.press('Insert');let id=await page.evaluate(()=>draftTaskId),area=page.locator(`.ganttDraftRow[data-task-id="${id}"] .hierarchyDraftSummary`);await area.focus();await area.dispatchEvent('compositionstart');await area.dispatchEvent('keydown',{key:'Escape',code:'Escape',isComposing:true,keyCode:229});expect(await page.evaluate(()=>draftTaskId)).toBe(id);await area.dispatchEvent('compositionend',{data:''});await area.press('Escape');expect(await page.evaluate(()=>draftTaskId)).toBe('');await page.evaluate(()=>selectTask('1'));await page.keyboard.press('Enter');id=await page.evaluate(()=>draftTaskId);const select=page.locator(`.ganttDraftRow[data-task-id="${id}"] select`).first();await select.focus();await select.press('Escape');expect(await page.evaluate(()=>draftTaskId)).toBe('')});

test('HQA2-IMPACT-01: B display gains hyphen while canonical value stays unchanged',async({page})=>{await fresh(page,[task('1',{impact:'B-期限 期日までに誰かが困る'})]);const option=page.locator('#b_impact option[value="B-期限 期日までに誰かが困る"]');await expect(option).toHaveText('B-期日までに誰かが困る');expect(await page.evaluate(()=>itemById('1').impact)).toBe('B-期限 期日までに誰かが困る');expect(await page.locator('.ganttRow[data-task-id="1"] select option[value="B-期限 期日までに誰かが困る"]').first().textContent()).toBe('B-期日までに誰かが困る')});

test('HQA2-ALT-T-01: TOP in ToDo/Project, preserves state, and honors editing guards',async({page})=>{await fresh(page,Array.from({length:100},(_,i)=>task(String(i+1),{sortOrder:(i+1)*1000})));await page.evaluate(()=>{window.__topCalls=[];const base=window.scrollTo.bind(window);window.scrollTo=(arg,...rest)=>{window.__topCalls.push(arg);return base(arg,...rest)}});for(const next of ['personal','team']){await page.evaluate(m=>setMode(m),next);await page.evaluate(()=>window.scrollTo(0,700));await page.evaluate(()=>{document.querySelector('#ganttView')?.scrollTo({left:120});if(mode==='team')setGanttTimelineScroll(240)});const before=await page.evaluate(()=>({mode,selectedTaskId,outer:document.querySelector('#ganttView')?.scrollLeft||0,timeline:ganttTimelineScrollLeft,dirty,undo:undoStack.length}));await page.keyboard.press('Alt+t');await expect.poll(()=>page.evaluate(()=>scrollY)).toBeLessThan(5);expect(await page.evaluate(()=>({mode,selectedTaskId,outer:document.querySelector('#ganttView')?.scrollLeft||0,timeline:ganttTimelineScrollLeft,dirty,undo:undoStack.length}))).toEqual(before)}await page.evaluate(()=>window.scrollTo(0,700));await page.locator('#b_title').focus();await page.keyboard.press('Alt+t');expect(await page.evaluate(()=>scrollY)).toBeGreaterThan(400);await expect(page.locator('#shortcutHelp')).toContainText('Alt+T＝TOP');await expect(page.locator('#shortcutHelp')).not.toContainText(/Alt\+[PG]/)});

test('HQA2-VISUAL-01: 1680x900 visual states remain coherent',async({page})=>{await fresh(page,Array.from({length:45},(_,i)=>task(String(i+1),{due:i===0?'2016-01-01':i===1?'2030-01-01':`2026-08-${String(1+i%28).padStart(2,'0')}`,title:`Visual task ${i+1}`,summary:`Summary ${i+1}`,sortOrder:(i+1)*1000})));await page.setViewportSize({width:1680,height:900});await page.screenshot({path:'test-results/hqa2-detail-on.png'});await page.locator('#projectDetailBtn').click();await page.screenshot({path:'test-results/hqa2-detail-off.png'});await page.locator('#projectDetailBtn').click();await page.screenshot({path:'test-results/hqa2-today-minus-7.png'});const natural=await page.locator('.ganttHeader').evaluate(el=>el.getBoundingClientRect().top+scrollY);await page.evaluate(y=>window.scrollTo(0,y+2),natural);await expect(page.locator('.projectTopDraftRow')).toHaveClass(/hqaLiveSticky/);await page.screenshot({path:'test-results/hqa2-sticky-empty.png'});await page.locator('#b_summary').fill('line 1\nline 2\nline 3\nline 4\nline 5\nline 6');await page.screenshot({path:'test-results/hqa2-sticky-expanded.png'});await page.screenshot({path:'test-results/hqa2-two-line-dates.png',clip:await page.locator('.ganttHeader').boundingBox()})});
