const {test,expect}=require('playwright/test');
const {APP}=require('./helpers/app-target');
const task=(id,due,duration=1,sortOrder=1000)=>({id,parentId:'',state:'未着手',impact:'',title:id,owner:'',due,planned_duration_days:duration,summary:'',repeat:'',completed:false,source:'',asana_task_id:'',history:[],dependencies:[],sortOrder});
async function boot(page,items,gantt=false){await page.emulateMedia({reducedMotion:'no-preference'});await page.goto(APP);await page.evaluate(()=>localStorage.clear());await page.reload();await page.evaluate(xs=>{applyJsonObject({schema_version:'1.8',items:xs},'animation-paths','animation-paths.json',null,{remember:false,writePermissionGranted:false});clearUndoHistory('animation-paths-test')},items);await page.locator('#mTeam').click();if(gantt)await page.evaluate(()=>setMode('team'))}
async function row(page,id){return page.locator(await page.locator('#ganttView').isVisible()?`.ganttRow[data-task-id="${id}"]`:`#row_${id}`)}
async function expectMoved(page,id,kind){const target=await row(page,id);await expect(target).toHaveClass(/sortMoveAnimating/);await expect(target).toHaveAttribute('data-sort-move-kind',kind);await expect(target).not.toHaveClass(/sortMoveAnimating/)}
async function expectNotMoved(page,id){await page.waitForTimeout(40);await expect(await row(page,id)).not.toHaveClass(/sortMoveAnimating/)}
async function dragDays(page,locator,days){await locator.scrollIntoViewIfNeeded();const b=await locator.boundingBox();if(!b)throw Error('drag target missing');await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.down();await page.mouse.move(b.x+b.width/2+days*28,b.y+b.height/2,{steps:8});await page.mouse.up()}

test('SORT-ANIM-PATH-A/B: textとcalendarの期限変更はsort移動時だけ共通FLIP',async({page})=>{await boot(page,[task('A','2026-08-20'),task('B','2026-08-15',1,2000)]);await page.locator('#row_A .dueTxt').click();const input=page.locator('#row_A input[id^="d"]');await input.fill('2026-08-10');await input.press('Enter');await expectMoved(page,'A','due');await page.evaluate(()=>setDueFromCalendar(data.items.findIndex(x=>x.id==='A'),'2026-08-11'));await expectNotMoved(page,'A');await page.evaluate(()=>setDueFromCalendar(data.items.findIndex(x=>x.id==='A'),'2026-08-25'));await expectMoved(page,'A','calendar-due');expect(await page.evaluate(()=>undoStack.length)).toBe(3)});

test('SORT-ANIM-PATH-C: Gantt plan barとmilestone dragはsort移動時だけ共通FLIP',async({page})=>{await boot(page,[task('A','2026-08-20'),task('B','2026-08-15',1,2000),task('M','2026-08-22',0,3000)],true);await page.evaluate(()=>setGanttTimelineScroll(80));const bar=page.locator('.ganttBar[data-task-id="A"]');await bar.scrollIntoViewIfNeeded();const outer=await page.evaluate(()=>ganttView.scrollLeft);await dragDays(page,bar,-10);await expectMoved(page,'A','gantt-plan-drag');expect(await page.evaluate(()=>ganttView.scrollLeft)).toBe(outer);expect(await bar.evaluate(el=>{const a=el.getBoundingClientRect(),b=el.closest('.ganttTimelineClip').getBoundingClientRect();return a.right>=b.left&&a.left<=b.right})).toBe(true);await dragDays(page,bar,1);await expectNotMoved(page,'A');await dragDays(page,page.locator('.ganttMilestone[data-task-id="M"]'),-10);await expectMoved(page,'M','gantt-milestone-drag');expect(await page.evaluate(()=>undoStack.length)).toBe(3)});

test('SORT-ANIM-PATH-D: Gantt due-only marker dragはsort移動時だけ共通FLIP',async({page})=>{const dueOnly=task('D','2026-08-20',undefined);delete dueOnly.planned_duration_days;await boot(page,[dueOnly,task('B','2026-08-15',1,2000)],true);await page.evaluate(()=>setGanttTimelineScroll(60));const marker=page.locator('.ganttRow[data-task-id="D"] .ganttDueOnlyMarker');await marker.scrollIntoViewIfNeeded();const outer=await page.evaluate(()=>ganttView.scrollLeft);await dragDays(page,marker,-10);await expectMoved(page,'D','gantt-due-marker-drag');expect(await page.evaluate(()=>ganttView.scrollLeft)).toBe(outer);expect(await marker.evaluate(el=>{const a=el.getBoundingClientRect(),b=el.closest('.ganttTimelineClip').getBoundingClientRect();return a.right>=b.left&&a.left<=b.right})).toBe(true);await dragDays(page,marker,1);await expectNotMoved(page,'D');expect(await page.evaluate(()=>undoStack.length)).toBe(2)});
