const {test,expect}=require('playwright/test');
const {APP}=require('./helpers/app-target');
const task=(id,extra={})=>({id,parentId:'',state:'未着手',impact:'',title:id,owner:'担当',due:'2026-08-20',summary:'',repeat:'',completed:false,source:'',asana_task_id:'',history:[],dependencies:[],sortOrder:1000,...extra});
async function fresh(page,items=[],schema='1.9'){await page.goto(APP);await page.evaluate(()=>localStorage.clear());await page.reload();await expect(page.locator('body')).not.toHaveClass(/dbBooting/);await page.evaluate(({items,schema})=>applyJsonObject({schema_version:schema,items},'recurrence','recurrence.json',null,{remember:false,writePermissionGranted:false}),{items,schema});await page.waitForTimeout(50)}

test('HQA2.3 conflict button releases focus and ArrowDown/Up navigates without page scroll',async({page})=>{const items=[task('A',{due:'2026-08-20',planned_duration_days:5,sortOrder:1000}),task('B',{due:'2026-08-18',planned_duration_days:2,dependencies:[{task_id:'A',type:'finish_to_start'}],sortOrder:2000}),task('C',{due:'2026-08-22',planned_duration_days:2,sortOrder:3000})];await fresh(page,items);await page.evaluate(()=>setMode('team'));const conflict=page.locator('.ganttConflictItem').first();await conflict.click();expect(await page.evaluate(()=>document.activeElement?.matches('.ganttConflictItem,.ganttWarn'))).toBe(false);const before=await page.evaluate(()=>({y:scrollY,outer:ganttView.scrollLeft,timeline:ganttTimelineScrollLeft}));await page.keyboard.press('ArrowDown');expect(await page.evaluate(()=>selectedTaskId)).toBe('C');expect(await page.evaluate(()=>({y:scrollY,outer:ganttView.scrollLeft,timeline:ganttTimelineScrollLeft,toast:getComputedStyle(document.getElementById('toast')).display,orange:document.querySelectorAll('.conflictAttention').length,blue:document.querySelectorAll('.ganttSelected').length}))).toEqual({...before,toast:'none',orange:0,blue:1});await page.keyboard.press('ArrowUp');expect(await page.evaluate(()=>selectedTaskId)).toBe('B');await page.locator('#projectDetailBtn').focus();const selected=await page.evaluate(()=>selectedTaskId);await page.keyboard.press('ArrowDown');expect(await page.evaluate(()=>selectedTaskId)).toBe(selected)});

test('recurrence engine uses previous scheduled due and preserves intent',async({page})=>{await fresh(page);const values=await page.evaluate(()=>{const n=(due,repeat,recurrence_rule)=>nextRecurringDue({due,repeat,recurrence_rule});return{daily:n('2026-08-20','毎日',{type:'daily'}),weekly:n('2026-08-17','毎週',{type:'weekly',weekdays:[1]}),multi1:n('2026-08-17','毎週',{type:'weekly',weekdays:[1,3,5]}),multi2:n('2026-08-21','毎週',{type:'weekly',weekdays:[1,3,5]}),bi:n('2026-08-20','隔週',{type:'biweekly'}),m31a:n('2025-01-31','毎月',{type:'monthly',mode:'date',day:31}),m31b:n('2025-02-28','毎月',{type:'monthly',mode:'date',day:31}),last:n('2025-03-31','毎月',{type:'monthly',mode:'date',day:'last'}),first:n('2026-08-04','毎月',{type:'monthly',mode:'weekday',ordinal:1,weekday:2}),fourth:n('2026-08-25','毎月',{type:'monthly',mode:'weekday',ordinal:4,weekday:2}),lastFri:n('2026-08-28','毎月',{type:'monthly',mode:'weekday',ordinal:'last',weekday:5}),year:n('2026-08-20','毎年',{type:'yearly',month:8,day:20}),leap1:n('2024-02-29','毎年',{type:'yearly',month:2,day:29}),leap2:n('2027-02-28','毎年',{type:'yearly',month:2,day:29})}});expect(values).toEqual({daily:'2026-08-21',weekly:'2026-08-24',multi1:'2026-08-19',multi2:'2026-08-24',bi:'2026-09-03',m31a:'2025-02-28',m31b:'2025-03-31',last:'2025-04-30',first:'2026-09-01',fourth:'2026-09-22',lastFri:'2026-09-25',year:'2027-08-20',leap1:'2025-02-28',leap2:'2028-02-29'})});

test('completion rolls the same task forward from previous due and preserves identity/hierarchy',async({page})=>{await fresh(page,[task('P',{due:''}),task('R',{parentId:'P',due:'2026-08-17',repeat:'毎週',recurrence_rule:{type:'weekly',weekdays:[1,3,5]}}),task('X',{state:'完了',completed:true})]);await page.evaluate(()=>toggle(data.items.findIndex(x=>x.id==='R')));const result=await page.evaluate(()=>{const current=itemById('R');return{count:data.items.length,completed:current.completed,due:current.due,parentId:current.parentId,deps:current.dependencies,rule:current.recurrence_rule}});expect(result).toEqual({count:3,completed:false,due:'2026-08-19',parentId:'P',deps:[],rule:{type:'weekly',weekdays:[1,3,5]}})});

test('completion date and actual end never influence recurrence; missing due is atomic no-op',async({page})=>{await fresh(page,[task('R',{due:'2026-08-17',repeat:'毎週',recurrence_rule:{type:'weekly',weekdays:[1]},actual_start:'2026-08-20',actual_end:'2026-08-21',actual_start_source:'user',actual_end_source:'user'}),task('N',{due:'',repeat:'毎日',recurrence_rule:{type:'daily'},sortOrder:2000})]);await page.evaluate(()=>{toggle(0);toggle(1)});expect(await page.evaluate(()=>data.items.map(x=>({title:x.title,due:x.due})).filter(x=>x.title==='R'||x.title==='N'))).toEqual([{title:'R',due:'2026-08-24'},{title:'N',due:''}]);await expect(page.locator('#toast')).toContainText('次回の繰返し期限を計算できない')});

test('repeat is rejected for predecessor, successor, FS/FF participation without mutation',async({page})=>{for(const type of ['finish_to_start','finish_to_finish']){await fresh(page,[task('A'),task('B',{dependencies:[{task_id:'A',type}],sortOrder:2000})]);const before=await page.evaluate(()=>JSON.stringify({items:data.items,dirty,undo:undoStack.length}));expect(await page.evaluate(()=>commitRepeatChange(0,'毎日',{type:'daily'}))).toBe(false);expect(await page.evaluate(()=>commitRepeatChange(1,'毎日',{type:'daily'}))).toBe(false);expect(await page.evaluate(()=>JSON.stringify({items:data.items,dirty,undo:undoStack.length}))).toBe(before)}});

test('adding FS/FF with repeating predecessor or successor is rejected; legacy invalid relation remains removable',async({page})=>{for(const direction of ['predecessor','successor']){await fresh(page,[task('A',{repeat:'毎日',recurrence_rule:{type:'daily'}}),task('B',{sortOrder:2000})]);await page.evaluate(dir=>{relationOpenId='B';relationSelectedTaskId='A';relationFormDirection=dir;addDependencyFromForm()},direction);expect(await page.evaluate(()=>data.items.flatMap(x=>x.dependencies).length)).toBe(0)}await fresh(page,[task('A',{repeat:'毎日',recurrence_rule:{type:'daily'}}),task('B',{dependencies:[{task_id:'A',type:'finish_to_finish'}],sortOrder:2000})]);await page.evaluate(()=>removeDependency('A','B'));expect(await page.evaluate(()=>itemById('B').dependencies)).toEqual([])});

test('recurring Due anchor accepts checklist child while nested recurrence stays blocked',async({page})=>{await fresh(page,[task('R',{repeat:'毎日',recurrence_rule:{type:'daily'}}),task('B',{parentId:'R',due:'',sortOrder:2000}),task('C',{parentId:'B',due:'',sortOrder:3000})]);expect(await page.evaluate(()=>commitRepeatChange(1,'毎日',{type:'daily'}))).toBe(false);expect(await page.evaluate(()=>commitRepeatChange(2,'毎日',{type:'daily'}))).toBe(false);const before=await page.evaluate(()=>({count:data.items.length,undo:undoStack.length}));await page.evaluate(()=>{selectedTaskId='R';startDraftTask('child')});const created=await page.evaluate(()=>{const x=itemById(draftTaskId);return{count:data.items.length,undo:undoStack.length,draft:draftTaskId,parentId:x.parentId,due:x.due,repeat:x.repeat}});expect(created).toMatchObject({count:before.count+1,undo:before.undo,parentId:'R',due:'',repeat:''});await page.evaluate(()=>cancelDraftTask(draftTaskId));await page.evaluate(()=>{selectedTaskId='R';addChild(data.items.findIndex(x=>x.id==='R'))});expect(await page.evaluate(()=>itemById(draftTaskId))).toMatchObject({parentId:'R',due:'',repeat:''})});

test('Schema 1.8 migrates to 2.0 preserving actual sources and recurrence intent without dirty write',async({page})=>{const items=[task('W',{due:'2026-08-17',repeat:'毎週',actual_start:'2026-08-15',actual_end:'2026-08-16',actual_start_source:'system',actual_end_source:'user'}),task('M',{due:'2026-01-31',repeat:'毎月',sortOrder:2000}),task('Y',{due:'2024-02-29',repeat:'毎年',sortOrder:3000})];await fresh(page,items,'1.8');expect(await page.evaluate(()=>({version:CURRENT_SCHEMA_VERSION,loaded:loadedSchemaVersion,pending:schemaMigrationPending,dirty,items:data.items.map(x=>({id:x.id,start:x.actual_start_source,end:x.actual_end_source,rule:x.recurrence_rule}))}))).toEqual({version:'2.0',loaded:'1.8',pending:true,dirty:false,items:[{id:'W',start:'system',end:'user',rule:{type:'weekly',weekdays:[1]}},{id:'M',start:undefined,end:undefined,rule:{type:'monthly',mode:'date',day:31}},{id:'Y',start:undefined,end:undefined,rule:{type:'yearly',month:2,day:29}}]});expect(await page.evaluate(()=>persistableData().schema_version)).toBe('2.0')});

test('Schema 1.9 compatibility, bimonthly migration and Schema 2.1 rejection',async({page})=>{await fresh(page,[task('L',{repeat:'隔月',due:'2026-01-31'})]);expect(await page.evaluate(()=>({next:nextRecurringDue(itemById('L')),summary:recurrenceSummary(itemById('L')),rule:itemById('L').recurrence_rule}))).toEqual({next:'2026-03-31',summary:'奇数月 31日',rule:{type:'bimonthly',parity:'odd',mode:'date',day:31}});await page.evaluate(()=>render());await expect(page.locator('#row_L .repeatSel option',{hasText:'隔月'})).toHaveCount(1);await fresh(page,[task('N')]);await expect(page.locator('#row_N .repeatSel option',{hasText:'隔月'})).toHaveCount(1);expect(await page.evaluate(()=>{try{prepareSchemaObject({schema_version:'2.1',items:[]});return false}catch(e){return e.schemaKind==='newer'}})).toBe(true)});

test('weekly modal validates, Cancel is no-op, Save is one Undo action and can reopen',async({page})=>{await fresh(page,[task('A',{due:'2026-08-17'})]);const before=await page.evaluate(()=>JSON.stringify({task:itemById('A'),dirty,undo:undoStack.length}));await page.evaluate(()=>openRecurrenceEditor(0,'毎週'));await page.locator('input[name="recWeekday"]').evaluateAll(xs=>xs.forEach(x=>x.checked=false));await page.locator('.recurrenceEditor .pri').click();await expect(page.locator('#recurrenceValidation')).toContainText('1つ以上');expect(await page.evaluate(()=>JSON.stringify({task:itemById('A'),dirty,undo:undoStack.length}))).toBe(before);await page.locator('input[name="recWeekday"][value="1"]').check();await page.locator('input[name="recWeekday"][value="3"]').check();await page.locator('.recurrenceEditor .pri').click();await expect.poll(()=>page.evaluate(()=>undoStack.length)).toBe(1);expect(await page.evaluate(()=>itemById('A').recurrence_rule)).toEqual({type:'weekly',weekdays:[1,3]});await page.locator('#row_A .recurrenceSettings').click();await expect(page.locator('input[name="recWeekday"][value="3"]')).toBeChecked();await page.locator('.recurrenceEditor button',{hasText:'キャンセル'}).click();expect(await page.evaluate(()=>itemById('A').recurrence_rule)).toEqual({type:'weekly',weekdays:[1,3]});await page.evaluate(()=>performUndo());expect(await page.evaluate(()=>({repeat:itemById('A').repeat,rule:itemById('A').recurrence_rule}))).toEqual({repeat:'',rule:undefined});await page.evaluate(()=>performRedo());expect(await page.evaluate(()=>itemById('A').recurrence_rule)).toEqual({type:'weekly',weekdays:[1,3]})});

test('monthly weekday/date/last configuration saves and reopens',async({page})=>{await fresh(page,[task('A')]);await page.evaluate(()=>openRecurrenceEditor(0,'毎月'));await page.locator('input[name="recMonthMode"][value="weekday"]').check();await page.locator('#recOrdinal').selectOption('last');await page.locator('#recWeekday').selectOption('5');await page.locator('.recurrenceEditor .pri').click();expect(await page.evaluate(()=>itemById('A').recurrence_rule)).toEqual({type:'monthly',mode:'weekday',ordinal:'last',weekday:5});await page.locator('#row_A .recurrenceSettings').click();await page.locator('input[name="recMonthMode"][value="date"]').check();await page.locator('#recMonthDay').selectOption('last');await page.locator('.recurrenceEditor .pri').click();expect(await page.evaluate(()=>itemById('A').recurrence_rule)).toEqual({type:'monthly',mode:'date',day:'last'})});

test('blank ToDo and Project can retain weekly/monthly configuration on commit',async({page})=>{for(const mode of ['personal','team']){await fresh(page);await page.evaluate(m=>setMode(m),mode);const repeat=mode==='personal'?'毎週':'毎月';await page.evaluate(rep=>openRecurrenceEditor(-1,rep),repeat);if(repeat==='毎週'){await page.locator('input[name="recWeekday"][value="3"]').check()}else{await page.locator('#recMonthDay').selectOption('31')}await page.locator('.recurrenceEditor .pri').click();await page.locator('#b_title').fill(mode);await page.locator('#b_due').fill('2026/08/20');await page.evaluate(()=>commitBlank(true));const made=await page.evaluate(title=>{const x=data.items.find(t=>t.title===title);return{repeat:x?.repeat,rule:x?.recurrence_rule}},mode);expect(made.repeat).toBe(repeat);expect(made.rule).toBeTruthy()}});

test('1680x900 recurrence controls and weekly/monthly dialogs remain visually coherent',async({page})=>{await page.setViewportSize({width:1680,height:900});await fresh(page,[task('W',{title:'Weekly visual task',repeat:'毎週',recurrence_rule:{type:'weekly',weekdays:[1,3,5]}}),task('M',{title:'Monthly visual task',repeat:'毎月',recurrence_rule:{type:'monthly',mode:'weekday',ordinal:'last',weekday:5},sortOrder:2000})]);await page.locator('#row_W .recurrenceSettings').click();await expect(page.locator('.recurrenceEditor')).toBeVisible();await page.screenshot({path:'test-results/hqa23-todo-weekly.png'});await page.locator('.recurrenceEditor button',{hasText:'キャンセル'}).click();await page.evaluate(()=>setMode('team'));await page.locator('#row_M .recurrenceSettings').click();await expect(page.locator('.recurrenceEditor')).toBeVisible();const box=await page.locator('.recurrenceEditor').boundingBox();expect(box.x).toBeGreaterThanOrEqual(0);expect(box.x+box.width).toBeLessThanOrEqual(1680);expect(box.y+box.height).toBeLessThanOrEqual(900);await page.screenshot({path:'test-results/hqa23-project-monthly.png'});await page.locator('.recurrenceEditor button',{hasText:'キャンセル'}).click();const alignment=await page.evaluate(()=>{const left=document.querySelector('.ganttHeader .ganttLeftPane').getBoundingClientRect(),timeline=document.querySelector('.ganttHeader .ganttTimelineClip').getBoundingClientRect();return Math.abs(timeline.left-left.right)});expect(alignment).toBeLessThan(1)});
