const {test,expect}=require('playwright/test');
const APP='/asana_style_task_manager_v200_dev.html';
const task=(id,extra={})=>({id,parentId:'',state:'未着手',impact:'',title:id,owner:'担当',due:'2026-08-20',planned_duration_days:3,summary:'',repeat:'',completed:false,source:'',asana_task_id:'',history:[],dependencies:[],sortOrder:1000,...extra});
const conflicts=()=>[task('A',{title:'先行A',due:'2026-08-20',planned_duration_days:5,sortOrder:1000}),task('B',{title:'後続B',due:'2026-08-18',planned_duration_days:2,dependencies:[{task_id:'A',type:'finish_to_start'}],sortOrder:2000}),task('C',{title:'後続C',due:'2026-08-19',planned_duration_days:2,dependencies:[{task_id:'A',type:'finish_to_finish'}],sortOrder:3000})];
async function fresh(page,items=conflicts(),modeName='team'){await page.setViewportSize({width:1100,height:620});await page.goto(APP);await page.evaluate(()=>localStorage.clear());await page.reload();await expect(page.locator('body')).not.toHaveClass(/dbBooting/);await page.evaluate(xs=>applyJsonObject({schema_version:'1.8',items:xs},'hqa22','hqa22.json',null,{remember:false,writePermissionGranted:false}),items);await page.evaluate(m=>setMode(m),modeName);await page.waitForTimeout(80)}
async function clickConflict(page,index=0){await page.evaluate(i=>document.querySelectorAll('.ganttConflictItem')[i].click(),index);await expect(page.locator('#toast')).toBeVisible()}

test('HQA2.2 conflict explanation and orange attention persist without timeout or scroll dismissal',async({page})=>{await fresh(page);await clickConflict(page);const text=await page.locator('#toast').innerText();expect(await page.evaluate(()=>({timer:hqa21ConflictTimer,task:activeConflictTaskId,index:activeConflictIndex}))).toEqual({timer:0,task:'B',index:0});await page.waitForTimeout(6200);await expect(page.locator('#toast')).toHaveText(text);await expect(page.locator('.ganttRow[data-task-id="B"]')).toHaveClass(/conflictAttention/);await page.evaluate(()=>{window.scrollTo(0,200);setGanttTimelineScroll(ganttTimelineScrollLeft+28);document.getElementById('ganttView').scrollLeft+=20});await expect(page.locator('#toast')).toHaveText(text);await expect(page.locator('.ganttRow[data-task-id="B"]')).toHaveClass(/conflictAttention/)});

test('HQA2.2 another conflict replaces message and task attention',async({page})=>{await fresh(page);await clickConflict(page,0);await clickConflict(page,1);await expect(page.locator('#toast')).toContainText('後続C');await expect(page.locator('.ganttRow[data-task-id="C"]')).toHaveClass(/conflictAttention/);await expect(page.locator('.ganttRow[data-task-id="B"]')).not.toHaveClass(/conflictAttention/);expect(await page.evaluate(()=>activeConflictTaskId)).toBe('C')});

test('HQA2.2 normal mouse, Arrow, search, edit and mode changes clear conflict context',async({page})=>{await fresh(page);await clickConflict(page);await page.locator('.ganttRow[data-task-id="C"] .ganttTimelineClip').click();await expect(page.locator('#toast')).toBeHidden();await clickConflict(page);await page.keyboard.press('ArrowDown');await expect(page.locator('#toast')).toBeHidden();await clickConflict(page);await page.evaluate(()=>flashTaskRow('C'));await expect(page.locator('#toast')).toBeHidden();await clickConflict(page);await page.locator('.ganttRow[data-task-id="B"] .titleText').focus();await expect(page.locator('#toast')).toBeHidden();await clickConflict(page);await page.evaluate(()=>setMode('personal'));await expect(page.locator('#toast')).toBeHidden();expect(await page.evaluate(()=>({task:activeConflictTaskId,index:activeConflictIndex}))).toEqual({task:'',index:-1})});

test('HQA2.2 summary/actual/relation edit and DB replacement clear conflict context',async({page})=>{await fresh(page);await clickConflict(page);await page.evaluate(()=>openSummaryModal('B'));await expect(page.locator('#toast')).toBeHidden();await page.locator('#summaryModalCancel').click();await page.evaluate(()=>setMode('team'));await clickConflict(page);await page.evaluate(()=>openActualEditor('B'));await expect(page.locator('#toast')).toBeHidden();await page.evaluate(()=>closeActualEditor());await clickConflict(page);await page.evaluate(()=>{relationPopup.style.display='block';const input=document.createElement('input');relationPopup.appendChild(input);input.focus()});await expect(page.locator('#toast')).toBeHidden();await page.evaluate(()=>{relationPopup.style.display='none';relationPopup.querySelector('input')?.remove()});await clickConflict(page);const conflictText=await page.locator('#toast').innerText();await page.evaluate(xs=>applyJsonObject({schema_version:'1.9',items:xs},'other','other.json',{name:'other.json'},{remember:false,writePermissionGranted:false}),[task('X')]);expect(await page.evaluate(()=>({task:activeConflictTaskId,attention:document.querySelectorAll('.conflictAttention').length}))).toEqual({task:'',attention:0});await expect(page.locator('#toast')).not.toHaveText(conflictText);await expect(page.locator('#toast')).toContainText('other.json')});

test('HQA2.2 unrelated toast remains temporary and clears conflict context',async({page})=>{await fresh(page);await clickConflict(page);await page.evaluate(()=>toastMsg('通常通知'));await expect(page.locator('#toast')).toHaveText('通常通知');expect(await page.evaluate(()=>activeConflictTaskId)).toBe('');await page.waitForTimeout(5200);await expect(page.locator('#toast')).toBeHidden()});

test('HQA2.2 Project ArrowDown then D1 opens newly selected due and Enter commits',async({page})=>{await fresh(page,[task('A',{due:'2026-08-20',sortOrder:1000}),task('B',{due:'2026-08-21',sortOrder:2000})]);await page.evaluate(()=>hqa21SelectWithoutRender('A'));const before=await page.evaluate(()=>({dirty,undo:undoStack.length}));await page.keyboard.press('ArrowDown');expect(await page.evaluate(()=>selectedTaskId)).toBe('B');await page.keyboard.press('d');await expect(page.locator('#shortcutHint')).toHaveClass(/show/);await page.keyboard.press('1');const input=page.locator('.ganttRow[data-task-id="B"] .ganttDueText');await expect(input).toBeVisible();await expect(input).toBeFocused();await expect(input).toHaveValue(await page.evaluate(()=>editDateText(addDays(ymd(),1))));expect(await page.evaluate(()=>({dirty,undo:undoStack.length}))).toEqual(before);await input.press('Enter');expect(await page.evaluate(()=>itemById('B').due)).toBe(await page.evaluate(()=>addDays(ymd(),1)))});

test('HQA2.2 Project ArrowUp D0 and ToDo D digit use current selected task',async({page})=>{await fresh(page,[task('A',{sortOrder:1000}),task('B',{sortOrder:2000})]);await page.evaluate(()=>hqa21SelectWithoutRender('B'));await page.keyboard.press('ArrowUp');await page.keyboard.press('D');await page.keyboard.press('0');await expect(page.locator('.ganttRow[data-task-id="A"] .ganttDueText')).toBeFocused();await page.locator('.ganttRow[data-task-id="A"] .ganttDueText').press('Escape');await page.evaluate(()=>setMode('personal'));await page.evaluate(()=>hqa21SelectWithoutRender('A'));await page.keyboard.press('d');await page.keyboard.press('2');const input=page.locator('#row_A input[id^="d"]');await expect(input).toBeFocused();await expect(input).toHaveValue(await page.evaluate(()=>editDateText(addDays(ymd(),2))))});

test('HQA2.2 Arrow selection leaves exactly one blue selection without removing attentions',async({page})=>{await fresh(page,[task('A',{sortOrder:1000}),task('B',{sortOrder:2000}),task('C',{sortOrder:3000})]);await page.evaluate(()=>{hqa21SelectWithoutRender('A');searchAttentionTaskId='A';sortAttentionTaskId='C';document.querySelector('.ganttRow[data-task-id="A"]').classList.add('searchAttention');document.querySelector('.ganttRow[data-task-id="C"]').classList.add('sortAttention')});for(const key of ['ArrowDown','ArrowDown','ArrowUp','ArrowUp','ArrowDown'])await page.keyboard.press(key);const project=await page.evaluate(()=>({selected:selectedTaskId,outer:document.querySelectorAll('#ganttView .ganttRow.ganttSelected').length,inner:document.querySelectorAll('#ganttView tr.selectedRow').length,search:document.querySelectorAll('#ganttView .searchAttention').length,sort:document.querySelectorAll('#ganttView .sortAttention').length}));expect(project).toEqual({selected:'B',outer:1,inner:0,search:1,sort:1});await page.evaluate(()=>setMode('personal'));await page.evaluate(()=>hqa21SelectWithoutRender('A'));for(const key of ['ArrowDown','ArrowDown','ArrowUp'])await page.keyboard.press(key);expect(await page.evaluate(()=>({selected:selectedTaskId,count:document.querySelectorAll('#listView tr.selectedRow').length}))).toEqual({selected:'B',count:1})});

test('HQA2.2 1680x900 visual states remain coherent',async({page},testInfo)=>{await fresh(page,conflicts());await page.setViewportSize({width:1680,height:900});await clickConflict(page);await page.waitForTimeout(6200);await page.screenshot({path:testInfo.outputPath('conflict-persistent.png'),fullPage:false});await page.keyboard.press('ArrowDown');expect(await page.evaluate(()=>({selected:selectedTaskId,blue:document.querySelectorAll('#ganttView .ganttRow.ganttSelected').length,conflict:document.querySelectorAll('#ganttView .conflictAttention').length}))).toEqual({selected:'C',blue:1,conflict:0});await page.screenshot({path:testInfo.outputPath('arrow-single-selection.png'),fullPage:false});await page.keyboard.press('d');await page.keyboard.press('1');await expect(page.locator('.ganttRow[data-task-id="C"] .ganttDueText')).toBeFocused();await page.screenshot({path:testInfo.outputPath('arrow-due-editor.png'),fullPage:false});await page.locator('.ganttRow[data-task-id="C"] .ganttDueText').press('Escape');await clickConflict(page);await page.locator('.ganttRow[data-task-id="C"] .titleText').focus();await expect(page.locator('#toast')).toBeHidden();await page.screenshot({path:testInfo.outputPath('edit-clears-conflict.png'),fullPage:false})});
