const {test,expect}=require('playwright/test');
const {APP}=require('./helpers/app-target');
const task=(id,extra={})=>({id,parentId:'',state:'',impact:'',title:id,owner:'',due:'2026-08-20',planned_duration_days:2,summary:'',repeat:'',completed:false,source:'',asana_task_id:'',history:[],dependencies:[],sortOrder:1000,...extra});
async function boot(page,items,mode='team',view='open'){await page.goto(APP);await page.evaluate(()=>localStorage.clear());await page.reload();await page.evaluate(async({items,mode,view})=>{await applyJsonObject({schema_version:'2.0',items},'hotfix','hotfix.json',null,{remember:false,writePermissionGranted:false});setMode(mode);setView(view);clearUndoHistory('hotfix')},{items,mode,view})}
const grow=(page,id)=>page.locator(`.ganttRow[data-task-id="${id}"]`),box=(page,id)=>page.locator(`.doneBulkCheck[data-task-id="${id}"]`);

test('H45-A1/A2 Project状態完了は未終了に残り終了済みには出ない',async({page})=>{await boot(page,[task('A',{state:'未着手'})]);await grow(page,'A').locator('.ganttState select').selectOption('完了');expect(await page.evaluate(()=>itemById('A'))).toMatchObject({id:'A',state:'完了',completed:false});await expect(grow(page,'A')).toHaveCount(1);await expect(grow(page,'A')).toHaveClass(/ganttDone/);await expect(grow(page,'A').locator('.doneBtn')).toHaveAttribute('title','終了する');await expect(grow(page,'A').locator('.ganttTaskTitle')).toHaveCSS('text-decoration-line','line-through');await page.locator('#vDone').click();await expect(grow(page,'A')).toHaveCount(0);expect(await page.evaluate(()=>data.items.filter(x=>x.id==='A').length)).toBe(1)});

test('H45-A3 ToDoとProjectは共通の未終了・終了済みfilterを持つ',async({page})=>{await boot(page,[task('A',{state:'完了',completed:true})]);await expect(grow(page,'A')).toHaveCount(0);await page.locator('#vDone').click();await expect(grow(page,'A')).toHaveCount(1);await page.evaluate(()=>setMode('personal'));await page.locator('#vOpen').click();await expect(page.locator('#row_A')).toHaveCount(0);await page.locator('#vDone').click();await expect(page.locator('#row_A')).toHaveCount(1)});

test('H45-A4/A5 ToDo終了は両viewの終了済みに入り、再オープンで未終了へ戻る',async({page})=>{await boot(page,[task('A')],'personal','open');await page.locator('#row_A .doneBtn').click();await page.evaluate(()=>setMode('team'));await expect(grow(page,'A')).toHaveCount(0);await page.locator('#vDone').click();await expect(grow(page,'A')).toHaveCount(1);await expect(grow(page,'A')).toHaveClass(/ganttDone/);await page.evaluate(()=>setMode('personal'));await page.locator('#row_A .doneBtn').click();await page.evaluate(()=>setMode('team'));await page.locator('#vOpen').click();await expect(grow(page,'A')).toHaveCount(1);await page.locator('#vDone').click();await expect(grow(page,'A')).toHaveCount(0);await page.evaluate(()=>setMode('personal'));await page.locator('#vOpen').click();await expect(page.locator('#row_A')).toHaveCount(1)});

test('H45-A6 recurring Status完了はrolloverせず、終了だけが同一IDを次回へ進める',async({page})=>{await boot(page,[task('R',{state:'進行中',repeat:'毎日',recurrence_rule:{type:'daily'}})]);await grow(page,'R').locator('.ganttState select').selectOption('完了');expect(await page.evaluate(()=>({count:data.items.length,item:itemById('R')}))).toMatchObject({count:1,item:{id:'R',due:'2026-08-20',state:'完了',completed:false}});await grow(page,'R').locator('.doneBtn').click();expect(await page.evaluate(()=>({count:data.items.length,item:itemById('R')}))).toMatchObject({count:1,item:{id:'R',due:'2026-09-05',state:'',completed:false}});await page.mouse.wheel(0,100);await expect(grow(page,'R')).toHaveCount(1);await page.locator('#vDone').click();await expect(grow(page,'R')).toHaveCount(0)});

test('H45-B1..B5 Project Doneは共有checkbox・master・indeterminate・visible selection',async({page})=>{await boot(page,[task('A',{state:'完了',completed:true}),task('B',{state:'完了',completed:true,sortOrder:2000}),task('C',{state:'完了',completed:true,sortOrder:3000})],'team','done');await expect(box(page,'A')).toBeVisible();await page.evaluate(()=>{selectedTaskId='C';render()});await box(page,'A').check();expect(await page.evaluate(()=>({ids:[...doneBulkSelection],selectedTaskId}))).toEqual({ids:['A'],selectedTaskId:'C'});expect(await page.locator('#doneBulkMaster').evaluate(el=>el.indeterminate)).toBe(true);await grow(page,'B').evaluate(el=>el.style.display='none');await page.locator('#doneBulkMaster').check();expect(new Set(await page.evaluate(()=>[...doneBulkSelection]))).toEqual(new Set(['A','C']));await page.locator('#doneBulkMaster').uncheck();expect(await page.evaluate(()=>[...doneBulkSelection])).toEqual([]);await page.locator('#vOpen').click();await expect(page.locator('.doneBulkCheck')).toHaveCount(0)});

test('H45-B6..B8 Project Cancel/Confirm/Undo/Redoと依存cleanup',async({page})=>{await boot(page,[task('A',{state:'完了',completed:true}),task('B',{state:'完了',completed:true,sortOrder:2000}),task('C',{state:'完了',completed:true,dependencies:[{task_id:'A',type:'finish_to_start'}],sortOrder:3000})],'team','done');await box(page,'A').check();await box(page,'B').check();const before=await page.evaluate(()=>({json:JSON.stringify(data.items),undo:undoStack.length,dirty}));page.once('dialog',d=>d.dismiss());await page.locator('#doneBulkDelete').click();expect(await page.evaluate(()=>({json:JSON.stringify(data.items),undo:undoStack.length,dirty}))).toEqual(before);page.once('dialog',d=>d.accept());await page.locator('#doneBulkDelete').click();expect(await page.evaluate(()=>({ids:data.items.map(x=>x.id),deps:itemById('C').dependencies,sel:[...doneBulkSelection]}))).toEqual({ids:['C'],deps:[],sel:[]});await page.keyboard.press('Control+z');expect(await page.evaluate(()=>data.items.map(x=>x.id))).toEqual(['A','B','C']);await page.keyboard.press('Control+y');expect(await page.evaluate(()=>data.items.map(x=>x.id))).toEqual(['C'])});

test('H45-B9 ToDo/Project mode切替でbulk selectionを隔離',async({page})=>{await boot(page,[task('A',{state:'完了',completed:true}),task('B',{state:'完了',completed:true,sortOrder:2000})],'personal','done');await box(page,'A').check();await page.evaluate(()=>setMode('team'));expect(await page.evaluate(()=>[...doneBulkSelection])).toEqual([]);await box(page,'B').check();await page.evaluate(()=>setMode('personal'));expect(await page.evaluate(()=>[...doneBulkSelection])).toEqual([]);await expect(page.locator('#doneBulkDelete')).toBeDisabled()});
