const {test,expect}=require('playwright/test');
const {APP}=require('./helpers/app-target');
const task=(id,extra={})=>({id,parentId:'',state:'',impact:'',title:id,owner:'',due:'2026-08-20',planned_duration_days:2,summary:'',repeat:'',completed:false,source:'',asana_task_id:'',history:[],dependencies:[],sortOrder:1000,...extra});
async function boot(page,items){await page.setViewportSize({width:1200,height:650});await page.goto(APP);await page.evaluate(()=>localStorage.clear());await page.reload();await page.evaluate(items=>{applyJsonObject({schema_version:'2.0',items},'phase4-final','phase4-final.json',null,{remember:false,writePermissionGranted:false});setView('all');setMode('team');clearUndoHistory('phase4-final')},items)}
const row=(page,id)=>page.locator(`.ganttRow[data-task-id="${id}"]`);

test('P4F-A1..A4 Project rollover FLIPは旧status/plan/actualを保持しcleanup後に次回表示',async({page})=>{
  await boot(page,[task('R',{due:'2026-08-01',state:'進行中',repeat:'毎月',recurrence_rule:{type:'monthly',mode:'date',day:1},actual_start:'2026-07-30',actual_end:'2026-08-01',actual_start_source:'user',actual_end_source:'user'}),...Array.from({length:7},(_,i)=>task('T'+i,{due:`2026-08-${String(i+3).padStart(2,'0')}`,sortOrder:(i+2)*1000}))]);
  await row(page,'R').locator('.doneBtn').click();
  expect(await page.evaluate(()=>({due:itemById('R').due,state:itemById('R').state,actual:itemById('R').actual_start}))).toEqual({due:'2026-10-01',state:'',actual:undefined});
  await expect(row(page,'R')).toHaveClass(/sortMoveAnimating/);await expect(row(page,'R')).toHaveClass(/recurrencePresentationPending/);
  await expect(row(page,'R').locator('.ganttState select')).toHaveValue('進行中');await expect(row(page,'R').locator('.ganttPlanned input')).toHaveValue('2');await expect(row(page,'R').locator('.actualLine,.actualSameDay,.actualPoint')).toHaveCount(1);
  await expect.poll(()=>row(page,'R').locator('.sortMoveAnimating').count(),{timeout:4000}).toBe(0);await expect(row(page,'R').locator('.ganttState select')).toHaveValue('');await expect(row(page,'R').locator('.actualLine,.actualSameDay,.actualPoint')).toHaveCount(0);await expect(row(page,'R')).not.toHaveClass(/recurrencePresentationPending/)
});

test('P4F-A5 no-move rolloverは待たずにcanonical次回表示',async({page})=>{await boot(page,[task('R',{repeat:'毎日',recurrence_rule:{type:'daily'},state:'進行中',actual_start:'2026-08-19'})]);await row(page,'R').locator('.doneBtn').click();await expect(row(page,'R')).not.toHaveClass(/sortMoveAnimating/);await expect(row(page,'R').locator('.ganttState select')).toHaveValue('');expect(await page.evaluate(()=>itemById('R').due)).toBe('2026-09-05');await expect(row(page,'R').locator('.actualLine,.actualSameDay,.actualPoint')).toHaveCount(0)});

test('P4F-A6 vertical wheel cancelはsnapshotを即破棄',async({page})=>{await boot(page,[task('R',{due:'2026-08-01',repeat:'毎月',recurrence_rule:{type:'monthly',mode:'date',day:1},state:'進行中',actual_start:'2026-08-01'}),task('A',{due:'2026-08-02',sortOrder:2000}),task('B',{due:'2026-08-03',sortOrder:3000})]);await row(page,'R').locator('.doneBtn').click();await expect(row(page,'R')).toHaveClass(/recurrencePresentationPending/);await page.mouse.wheel(0,120);await expect(row(page,'R')).not.toHaveClass(/recurrencePresentationPending/);await expect(row(page,'R').locator('.ganttState select')).toHaveValue('');await expect(row(page,'R').locator('.actualLine,.actualSameDay,.actualPoint')).toHaveCount(0)});

test('P4F-A7 horizontal wheelはrollover FLIPをcancelしない',async({page})=>{await boot(page,[task('R',{due:'2026-08-01',repeat:'毎月',recurrence_rule:{type:'monthly',mode:'date',day:1},state:'進行中'}),task('A',{due:'2026-08-02',sortOrder:2000}),task('B',{due:'2026-08-03',sortOrder:3000})]);await row(page,'R').locator('.doneBtn').click();await expect(row(page,'R')).toHaveClass(/sortMoveAnimating/);await row(page,'R').dispatchEvent('wheel',{deltaX:120,deltaY:0});await page.waitForTimeout(100);await expect(row(page,'R')).toHaveClass(/sortMoveAnimating/);await page.mouse.wheel(0,120)});

test('P4F-A8 rollover Undo/Redoは1 transactionのまま',async({page})=>{const original=task('R',{repeat:'毎日',recurrence_rule:{type:'daily'},state:'進行中',actual_start:'2026-08-19',actual_start_source:'user'});await boot(page,[original]);const normalizedOriginal=await page.evaluate(()=>JSON.parse(JSON.stringify(itemById('R'))));await row(page,'R').locator('.doneBtn').click();expect(await page.evaluate(()=>undoStack.length)).toBe(1);await page.keyboard.press('Control+z');expect(await page.evaluate(()=>itemById('R'))).toEqual(normalizedOriginal);await page.keyboard.press('Control+y');expect(await page.evaluate(()=>itemById('R'))).toMatchObject({id:'R',due:'2026-09-05',state:'',completed:false})});
