const {test,expect}=require('playwright/test');
const {APP}=require('./helpers/app-target');
const task=(id,extra={})=>({id,parentId:'',state:'完了',impact:'',title:id,owner:'',due:'2026-08-20',summary:'',repeat:'',completed:true,source:'',asana_task_id:'',history:[],dependencies:[],sortOrder:1000,...extra});
async function boot(page,items){await page.goto(APP);await page.evaluate(()=>localStorage.clear());await page.reload();await page.evaluate(async items=>{await applyJsonObject({schema_version:'2.0',items},'phase5','phase5.json',null,{remember:false,writePermissionGranted:false});setMode('personal');setView('done');clearUndoHistory('phase5')},items)}
const box=(page,id)=>page.locator(`.doneBulkCheck[data-task-id="${id}"]`);

test('P5-B1 checkboxと一括削除UIはToDo/ProjectのDoneだけ',async({page})=>{await boot(page,[task('A')]);await expect(box(page,'A')).toBeVisible();await expect(page.locator('#doneBulkMaster')).toBeVisible();await expect(page.locator('#doneBulkToolbar')).toBeVisible();await page.locator('#vOpen').click();await expect(page.locator('.doneBulkCheck')).toHaveCount(0);await expect(page.locator('#doneBulkToolbar')).not.toBeVisible();await page.locator('#vAll').click();await expect(page.locator('.doneBulkCheck')).toHaveCount(0);await page.locator('#vDone').click();await page.locator('#mTeam').click();await expect(box(page,'A')).toBeVisible();await expect(page.locator('#doneBulkMaster')).toBeVisible();await expect(page.locator('#doneBulkToolbar')).toBeVisible();await page.locator('#vOpen').click();await expect(page.locator('.doneBulkCheck')).toHaveCount(0)});

test('P5-B2/B3/B4 row選択・全選択・indeterminateはnormal selectionと分離',async({page})=>{await boot(page,[task('A'),task('B',{sortOrder:2000}),task('C',{sortOrder:3000})]);await page.evaluate(()=>{selectedTaskId='C';render()});await box(page,'A').check();expect(await page.evaluate(()=>({ids:[...doneBulkSelection],selectedTaskId}))).toEqual({ids:['A'],selectedTaskId:'C'});await expect(page.locator('#doneBulkDelete')).toHaveText('選択した1件を削除');expect(await page.locator('#doneBulkMaster').evaluate(el=>el.indeterminate)).toBe(true);await page.locator('#doneBulkMaster').check();expect(new Set(await page.evaluate(()=>[...doneBulkSelection]))).toEqual(new Set(['A','B','C']));await page.locator('#doneBulkMaster').uncheck();expect(await page.evaluate(()=>[...doneBulkSelection])).toEqual([])});

test('P5-B5 masterは現在表示中の完了結果だけをtask IDで選択',async({page})=>{await boot(page,[task('A'),task('B',{sortOrder:2000}),task('C',{sortOrder:3000})]);await page.locator('#row_B').evaluate(el=>el.style.display='none');await page.locator('#doneBulkMaster').check();expect(new Set(await page.evaluate(()=>[...doneBulkSelection]))).toEqual(new Set(['A','C']));await page.locator('#row_B').evaluate(el=>el.style.display='table-row');await box(page,'B').check();expect(new Set(await page.evaluate(()=>[...doneBulkSelection]))).toEqual(new Set(['A','B','C']))});

test('P5-B6 Cancelはdata・selection・history・dirtyを完全no-op',async({page})=>{await boot(page,[task('A'),task('B',{sortOrder:2000})]);await box(page,'A').check();const before=await page.evaluate(()=>({json:JSON.stringify(data.items),ids:[...doneBulkSelection],undo:undoStack.length,dirty}));page.once('dialog',d=>d.dismiss());await page.locator('#doneBulkDelete').click();expect(await page.evaluate(()=>({json:JSON.stringify(data.items),ids:[...doneBulkSelection],undo:undoStack.length,dirty}))).toEqual(before)});

test('P5-B7/B8 confirmは一括削除し1 Undo/Redoで全件復元',async({page})=>{await boot(page,[task('A'),task('B',{sortOrder:2000}),task('C',{sortOrder:3000})]);await box(page,'A').check();await box(page,'B').check();page.once('dialog',d=>d.accept());await page.locator('#doneBulkDelete').click();expect(await page.evaluate(()=>data.items.map(x=>x.id))).toEqual(['C']);expect(await page.evaluate(()=>[...doneBulkSelection])).toEqual([]);expect(await page.evaluate(()=>undoStack.length)).toBe(1);await page.keyboard.press('Control+z');expect(await page.evaluate(()=>data.items.map(x=>x.id))).toEqual(['A','B','C']);await page.keyboard.press('Control+y');expect(await page.evaluate(()=>data.items.map(x=>x.id))).toEqual(['C'])});

test('P5-B9/B10/B11 hierarchyは既存単体規則、依存参照は全削除IDをcleanup',async({page})=>{await boot(page,[task('P'),task('C',{parentId:'P',sortOrder:2000}),task('K',{parentId:'C',sortOrder:3000}),task('R',{dependencies:[{task_id:'P',type:'finish_to_start'},{task_id:'C',type:'finish_to_finish'}],sortOrder:4000})]);await box(page,'P').check();page.once('dialog',d=>d.accept());await page.locator('#doneBulkDelete').click();expect(await page.evaluate(()=>({ids:data.items.map(x=>x.id),parent:itemById('C').parentId,deps:itemById('R').dependencies}))).toEqual({ids:['C','K','R'],parent:'P',deps:[{task_id:'C',type:'finish_to_finish'}]});await box(page,'C').check();await box(page,'K').check();page.once('dialog',d=>d.accept());await page.locator('#doneBulkDelete').click();expect(await page.evaluate(()=>({ids:data.items.map(x=>x.id),deps:itemById('R').dependencies}))).toEqual({ids:['R'],deps:[]})});

test('P5-B12/B13/B14 selectedTask・永続化・legacy recurrenceを安全に削除',async({page})=>{await boot(page,[task('R',{repeat:'毎日',recurrence_rule:{type:'daily'}}),task('U',{sortOrder:2000})]);await page.evaluate(()=>{selectedTaskId='R';render()});await box(page,'R').check();page.once('dialog',d=>d.accept());await page.locator('#doneBulkDelete').click();expect(await page.evaluate(()=>({selectedTaskId,ids:data.items.map(x=>x.id),saved:persistableData().items.map(x=>x.id),due:itemById('U').due}))).toEqual({selectedTaskId:'',ids:['U'],saved:['U'],due:'2026-08-20'});await page.keyboard.press('Control+z');expect(await page.evaluate(()=>itemById('R'))).toMatchObject({id:'R',due:'2026-08-20',repeat:'毎日',completed:true})});

test('P5-B5 lifecycleはharmless renderで保持しDone離脱・DB採用でclear',async({page})=>{await boot(page,[task('A')]);await box(page,'A').check();await page.evaluate(()=>render());expect(await page.evaluate(()=>[...doneBulkSelection])).toEqual(['A']);await page.locator('#vAll').click();expect(await page.evaluate(()=>[...doneBulkSelection])).toEqual([]);await page.locator('#vDone').click();await box(page,'A').check();await page.evaluate(async()=>applyJsonObject({schema_version:'2.0',items:[{...itemById('A'),id:'B',title:'B'}]},'new','new.json',null,{remember:false,writePermissionGranted:false}));expect(await page.evaluate(()=>[...doneBulkSelection])).toEqual([])});
