const {test,expect}=require('playwright/test');
const {APP}=require('./helpers/app-target');
const task=(id,due,sortOrder)=>({id,parentId:'',state:'未着手',impact:'',title:id,owner:'',due,planned_duration_days:1,summary:'',repeat:'',completed:false,source:'',asana_task_id:'',history:[],dependencies:[],sortOrder});
const items=()=>Array.from({length:18},(_,i)=>task(`T${i+1}`,`2026-08-${String(23+i).padStart(2,'0')}`,(i+1)*1000));
async function fresh(page,mode){await page.setViewportSize({width:1000,height:420});await page.goto(APP);await page.evaluate(()=>localStorage.clear());await page.reload();await page.evaluate(xs=>applyJsonObject({schema_version:'2.0',items:xs},'due-follow','due-follow.json',null,{remember:false,writePermissionGranted:false}),items());await page.evaluate(mode=>{setMode(mode);if(mode==='personal')setSortMode('date')},mode);await page.waitForTimeout(60)}
const row=(page,mode,id)=>page.locator(mode==='team'?`.ganttRow[data-task-id="${id}"]`:`#row_${id}`);
async function editorShortcut(page,mode,id){const host=row(page,mode,id);await host.locator('.dueTxt').click();const input=host.locator('input[type="text"][id^="d"]');await input.press('d');await input.press('9');await page.keyboard.press('Enter')}

for(const mode of['personal','team'])test(`PHASE2-DUE-FOLLOW-01 ${mode}: no pre-FLIP vertical jump, then minimal visible follow`,async({page})=>{
  await fresh(page,mode);await row(page,mode,'T1').evaluate(el=>el.scrollIntoView({block:'center'}));if(mode==='team')await page.evaluate(()=>{ganttView.scrollLeft=40;projectOuterScrollLeft=ganttView.scrollLeft;setGanttTimelineScroll(180)});
  const before=await page.evaluate(()=>({index:displaySortIndex('T1'),pageY:scrollY,listTop:listView.scrollTop,ganttTop:ganttView.scrollTop,outer:ganttView.scrollLeft,timeline:ganttTimelineScrollLeft}));await editorShortcut(page,mode,'T1');
  const started=await page.evaluate(()=>({draft:draftTaskId,pageY:scrollY,listTop:listView.scrollTop,ganttTop:ganttView.scrollTop,outer:ganttView.scrollLeft,timeline:ganttTimelineScrollLeft}));expect(started).toEqual({draft:'',pageY:before.pageY,listTop:before.listTop,ganttTop:before.ganttTop,outer:before.outer,timeline:before.timeline});
  await expect(row(page,mode,'T1')).toHaveClass(/sortMoveAnimating/);await expect(row(page,mode,'T1')).toHaveAttribute('data-sort-move-kind','due');await expect.poll(()=>page.locator('.sortMoveAnimating').count(),{timeout:4000}).toBe(0);
  expect(await row(page,mode,'T1').evaluate(el=>{const r=el.getBoundingClientRect(),s=taskVerticalScroller(el),p=s===document.scrollingElement||s===document.documentElement||s===document.body,b=rcUsableVerticalBounds(s,p);return r.top>=b.top&&r.bottom<=b.bottom})).toBe(true);
  expect(await page.evaluate(()=>itemById('T1').due)).toBe(await page.evaluate(()=>addDays(ymd(),9)));expect(await page.evaluate(()=>displaySortIndex('T1'))).toBeGreaterThan(before.index)
});

test('PHASE2-DUE-FOLLOW-02 non-editing d9 path still animates and Undo restores Due',async({page})=>{await fresh(page,'personal');await row(page,'personal','T1').click();await page.keyboard.press('d');await page.keyboard.press('9');const input=row(page,'personal','T1').locator('input[type="text"][id^="d"]');if(await input.isVisible())await input.press('Enter');await expect(row(page,'personal','T1')).toHaveClass(/sortMoveAnimating/);await page.keyboard.press('Control+z');expect(await page.evaluate(()=>itemById('T1').due)).toBe('2026-08-23')});
test('PHASE2-DUE-FOLLOW-03 same value and same-rank change cause no follow jump',async({page})=>{await fresh(page,'personal');const first=row(page,'personal','T1');await first.locator('.dueTxt').click();let input=first.locator('input[type="text"][id^="d"]');await input.fill('2026/08/23');await input.press('Enter');await expect(first).not.toHaveClass(/sortMoveAnimating/);const before=await page.evaluate(()=>({pageY:scrollY,listTop:listView.scrollTop,ganttTop:ganttView.scrollTop}));await first.locator('.dueTxt').click();input=first.locator('input[type="text"][id^="d"]');await input.fill('2026/08/22');await input.press('Enter');await expect(first).not.toHaveClass(/sortMoveAnimating/);expect(await page.evaluate(()=>({pageY:scrollY,listTop:listView.scrollTop,ganttTop:ganttView.scrollTop}))).toEqual(before)});
test('PHASE2-DUE-FOLLOW-04 pending FLIP suppresses vertical restore and bypasses legacy center follow',async({page})=>{await fresh(page,'personal');await row(page,'personal','T1').evaluate(el=>el.scrollIntoView({block:'center'}));await page.evaluate(()=>{window.__dueScrollTrace=[];const state=(label,s)=>({label,suppressed:!!s?.suppressVertical,pageY:scrollY,listTop:listView.scrollTop,ganttTop:ganttView.scrollTop});const restore=rcRestoreViewport;rcRestoreViewport=function(s,...rest){__dueScrollTrace.push(state('before',s));const result=restore(s,...rest);__dueScrollTrace.push(state('after',s));return result};const legacy=focusPostSortTask;window.__legacyFocusCalls=0;focusPostSortTask=function(...args){__legacyFocusCalls++;return legacy(...args)}});await editorShortcut(page,'personal','T1');const result=await page.evaluate(()=>({trace:__dueScrollTrace,legacy:__legacyFocusCalls}));expect(result.trace.length).toBeGreaterThanOrEqual(4);expect(result.trace.every(x=>x.suppressed)).toBe(true);for(let i=0;i<result.trace.length;i+=2)expect(result.trace[i+1]).toMatchObject({pageY:result.trace[i].pageY,listTop:result.trace[i].listTop,ganttTop:result.trace[i].ganttTop});expect(result.legacy).toBe(0)});
test('PHASE2-DUE-FOLLOW-05 active editor d1 commits after input event and starts FLIP without Enter or premature scroll',async({page})=>{await fresh(page,'personal');await page.evaluate(()=>{itemById('T1').due='2026-09-10';save();render();clearUndoHistory('active-editor-d1-reorder')});const target=row(page,'personal','T1');await target.evaluate(el=>el.scrollIntoView({block:'center'}));await target.locator('.dueTxt').click();const input=target.locator('input[type="text"][id^="d"]');const before=await page.evaluate(()=>({due:itemById('T1').due,index:displaySortIndex('T1'),pageY:scrollY,listTop:listView.scrollTop,undo:undoStack.length}));await input.press('d');await input.press('1');expect(await page.evaluate(()=>itemById('T1').due===addDays(ymd(),1))).toBe(true);await expect(target).toHaveClass(/sortMoveAnimating/);expect(await page.evaluate(()=>({pageY:scrollY,listTop:listView.scrollTop}))).toEqual({pageY:before.pageY,listTop:before.listTop});expect(await page.evaluate(()=>undoStack.length)).toBe(before.undo+1);expect(await page.evaluate(()=>displaySortIndex('T1'))).not.toBe(before.index);await expect.poll(()=>page.locator('.sortMoveAnimating').count(),{timeout:4000}).toBe(0);await page.keyboard.press('Control+z');expect(await page.evaluate(()=>itemById('T1').due)).toBe(before.due);await page.keyboard.press('Control+y');expect(await page.evaluate(()=>itemById('T1').due===addDays(ymd(),1))).toBe(true)});
test('PHASE2-DUE-FOLLOW-06 active editor d1 same-rank commit has no FLIP and no vertical jump',async({page})=>{await fresh(page,'personal');await page.evaluate(()=>{itemById('T1').due=addDays(ymd(),1);save();render();clearUndoHistory('same-rank-d1')});const target=row(page,'personal','T1');await target.locator('.dueTxt').click();const input=target.locator('input[type="text"][id^="d"]'),before=await page.evaluate(()=>({pageY:scrollY,listTop:listView.scrollTop,ganttTop:ganttView.scrollTop}));await input.press('d');await input.press('1');await page.waitForTimeout(80);await expect(target).not.toHaveClass(/sortMoveAnimating/);expect(await page.evaluate(()=>({pageY:scrollY,listTop:listView.scrollTop,ganttTop:ganttView.scrollTop}))).toEqual(before)});
