const {test,expect}=require('playwright/test');
const {APP}=require('./helpers/app-target');
const task=(id,title=id,extra={})=>({id,parentId:'',state:'',impact:'',title,owner:'',due:'',summary:'',repeat:'',completed:false,source:'',asana_task_id:'',history:[],dependencies:[],sortOrder:1000,...extra});
async function boot(page){await page.goto(APP);await page.evaluate(()=>localStorage.clear());await page.reload()}
async function setData(page,items,schema='1.8'){await page.evaluate(({items,schema})=>applyJsonObject({schema_version:schema,items},'test','phase2.json',null,{remember:false,writePermissionGranted:false}),{items,schema})}
async function gantt(page){await page.evaluate(()=>setMode('team'));await expect(page.locator('#ganttView')).toBeVisible()}
async function show(page,items,schema='1.8'){await setData(page,items,schema);await gantt(page)}
async function drag(page,locator,days){await locator.evaluate(el=>{const host=el.closest('.ganttTimeline'),clip=document.querySelector('.ganttHeader .ganttTimelineClip');if(host&&clip){const left=parseFloat(el.style.left)||0;setGanttTimelineScroll(Math.max(0,left-clip.clientWidth/2))}});await locator.scrollIntoViewIfNeeded();const b=await locator.boundingBox();if(!b)throw new Error('drag target missing');await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.down();await page.mouse.move(b.x+b.width/2+days*28,b.y+b.height/2,{steps:6});await page.mouse.up()}
test.beforeEach(async({page})=>boot(page));

test('ACTUAL2-SCHEMA-01: 1.5/1.6/1.7互換、source補完、孤立source除去、2.0保存',async({page})=>{
  const result=await page.evaluate(async()=>{const versions={};for(const schema of ['1.5','1.6','1.7']){await applyJsonObject({schema_version:schema,items:[{id:'x',title:schema,actual_start:'2026-08-01',actual_end:'2026-08-02',actual_start_source:schema==='1.7'?undefined:'system'}]},'test',schema+'.json',null,{remember:false,writePermissionGranted:false});versions[schema]={...itemById('x')}}await applyJsonObject({schema_version:'1.8',items:[{id:'clean',title:'clean',actual_start_source:'system',actual_end_source:'user'},{id:'sources',title:'sources',actual_start:'2026-08-01',actual_start_source:'system',actual_end:'2026-08-02',actual_end_source:'user'}]},'test','1.8.json',null,{remember:false,writePermissionGranted:false});return{versions,saved:persistableData()}});
expect(result.versions['1.5']).toMatchObject({actual_start_source:'user',actual_end_source:'user'});expect(result.versions['1.6']).toMatchObject({actual_start_source:'user',actual_end_source:'user'});expect(result.versions['1.7']).toMatchObject({actual_start_source:'user',actual_end_source:'user'});expect(result.saved.schema_version).toBe(await page.evaluate(()=>CURRENT_SCHEMA_VERSION));expect(result.saved.items[0]).not.toHaveProperty('actual_start_source');expect(result.saved.items[0]).not.toHaveProperty('actual_end_source');expect(result.saved.items[1]).toMatchObject({actual_start_source:'system',actual_end_source:'user'});
});

test('ACTUAL2-STATE-01: ガント状態変更で未設定実績だけをsystem補助設定して保持',async({page})=>{
  await show(page,[task('fresh','新規',{state:'未着手'}),task('existing','既存',{state:'未着手',actual_start:'2026-07-01',actual_start_source:'user'}),task('direct','直接完了',{state:'未着手'}),task('keep','保持',{state:'進行中',actual_start:'2026-06-01',actual_start_source:'user',actual_end:'2026-06-02',actual_end_source:'user'})]);const today=await page.evaluate(()=>ymd());
  await page.locator('.ganttRow[data-task-id="fresh"] .ganttState select').selectOption('進行中');expect(await page.evaluate(()=>itemById('fresh'))).toMatchObject({actual_start:today,actual_start_source:'system'});
  await page.locator('.ganttRow[data-task-id="existing"] .ganttState select').selectOption('進行中');expect(await page.evaluate(()=>itemById('existing'))).toMatchObject({actual_start:'2026-07-01',actual_start_source:'user'});
  await page.locator('.ganttRow[data-task-id="direct"] .ganttState select').selectOption('完了');expect(await page.evaluate(()=>itemById('direct'))).toMatchObject({actual_start:today,actual_start_source:'system',actual_end:today,actual_end_source:'system'});
  await page.locator('.ganttRow[data-task-id="keep"] .ganttState select').selectOption('保留');await page.locator('.ganttRow[data-task-id="keep"] .ganttState select').selectOption('中止');expect(await page.evaluate(()=>itemById('keep'))).toMatchObject({actual_start:'2026-06-01',actual_end:'2026-06-02'});
});

test('ACTUAL2-STATE-02: 完了の未来開始日は終了を自動生成せず警告',async({page})=>{
  await show(page,[task('future','未来',{state:'進行中',actual_start:'2099-01-01',actual_start_source:'user'})]);const click=page.locator('.ganttRow[data-task-id="future"] .ganttState select').selectOption('完了');const dialog=await page.waitForEvent('dialog');expect(dialog.message()).toContain('未来');await dialog.accept();await click;const x=await page.evaluate(()=>itemById('future'));expect(x.state).toBe('完了');expect(x).not.toHaveProperty('actual_end');expect(x.actual_start_source).toBe('user');
});

test('ACTUAL2-VIEW-01: 状態別表示とsystem/user点・tooltip',async({page})=>{
  const actual={actual_start:'2026-08-01',actual_start_source:'system',actual_end:'2026-08-03',actual_end_source:'user'};await show(page,[task('not','未着手',{state:'未着手',...actual}),task('run','進行中',{state:'進行中',actual_start:'2026-08-01',actual_start_source:'system'}),task('hold','保留',{state:'保留',...actual}),task('cancel','中止',{state:'中止',...actual}),task('done','完了',{state:'完了',...actual})]);
  await expect(page.locator('.ganttRow[data-task-id="not"] .actualLine')).toHaveCount(0);expect(await page.evaluate(()=>itemById('not').actual_start)).toBe('2026-08-01');await expect(page.locator('.ganttRow[data-task-id="run"] .actualDot.start')).toHaveClass(/system/);await expect(page.locator('.ganttRow[data-task-id="hold"] .actualLine')).toHaveClass(/hold/);await expect(page.locator('.ganttRow[data-task-id="cancel"] .actualLine')).toHaveClass(/cancelled/);await expect(page.locator('.ganttRow[data-task-id="done"] .actualDot.end')).toHaveClass(/user/);await expect(page.locator('.ganttRow[data-task-id="done"] .actualLine')).toHaveAttribute('data-gantt-tip',/自動設定[\s\S]*手動設定/);
});

test('ACTUAL2-CLEAR-01: 個別クリアと進行中・終了ありの開始クリア禁止',async({page})=>{
  await show(page,[task('clear','クリア',{state:'保留',actual_start:'2026-08-01',actual_start_source:'system',actual_end:'2026-08-03',actual_end_source:'user'}),task('run','進行中',{state:'進行中',actual_start:'2026-08-01',actual_start_source:'system'})]);
  await expect(page.locator('.actualEditBtn')).toHaveCount(0);await page.evaluate(()=>openTaskDetailPane('clear'));let pane=page.locator('#taskDetailPane'),start=pane.getByRole('textbox',{name:'実績開始',exact:true}),end=pane.getByRole('textbox',{name:'実績終了',exact:true});await start.fill('');await start.press('Enter');expect(await page.evaluate(()=>itemById('clear').actual_start)).toBe('2026-08-01');await end.fill('');await end.press('Enter');let x=await page.evaluate(()=>itemById('clear'));expect(x).not.toHaveProperty('actual_end');expect(x).not.toHaveProperty('actual_end_source');await start.fill('');await start.press('Enter');x=await page.evaluate(()=>itemById('clear'));expect(x).not.toHaveProperty('actual_start');expect(x).not.toHaveProperty('actual_start_source');await page.evaluate(()=>openTaskDetailPane('run'));pane=page.locator('#taskDetailPane');start=pane.getByRole('textbox',{name:'実績開始',exact:true});await start.fill('');await start.press('Enter');expect(await page.evaluate(()=>itemById('run').actual_start)).toBe('2026-08-01');
});

test('ACTUAL2-DRAG-01: 完了実績の中央・左右・同日dragと計画値独立',async({page})=>{
  await show(page,[task('range','範囲',{state:'完了',due:'2026-08-20',planned_duration_days:5,actual_start:'2026-08-10',actual_start_source:'system',actual_end:'2026-08-14',actual_end_source:'system'}),task('point','点',{state:'完了',actual_start:'2026-08-10',actual_start_source:'system',actual_end:'2026-08-10',actual_end_source:'system'})]);
  await drag(page,page.locator('.ganttRow[data-task-id="range"] .actualLine'),3);let x=await page.evaluate(()=>itemById('range'));expect(x).toMatchObject({actual_start:'2026-08-13',actual_end:'2026-08-17',actual_start_source:'user',actual_end_source:'user',due:'2026-08-20',planned_duration_days:5});await drag(page,page.locator('.ganttRow[data-task-id="range"] .actualDot.start'),-1);x=await page.evaluate(()=>itemById('range'));expect(x.actual_start).toBe('2026-08-12');expect(x.actual_end).toBe('2026-08-17');await drag(page,page.locator('.ganttRow[data-task-id="range"] .actualDot.end'),1);x=await page.evaluate(()=>itemById('range'));expect(x.actual_end).toBe('2026-08-18');await drag(page,page.locator('.ganttRow[data-task-id="point"] .actualSameDay'),2);expect(await page.evaluate(()=>itemById('point'))).toMatchObject({actual_start:'2026-08-12',actual_end:'2026-08-12',actual_start_source:'user',actual_end_source:'user'});
});

test('ACTUAL2-DRAG-02: 進行中・保留・中止は開始点だけ／実績値だけを変更',async({page})=>{
  await show(page,[task('run','進行中',{state:'進行中',due:'2026-08-20',planned_duration_days:3,actual_start:'2026-08-01',actual_start_source:'system'}),task('hold','保留',{state:'保留',actual_start:'2026-08-01',actual_start_source:'system'}),task('cancel','中止',{state:'中止',actual_start:'2026-08-01',actual_start_source:'system'})]);for(const id of ['run','hold','cancel']){await expect(page.locator(`.ganttRow[data-task-id="${id}"] .actualDot.end`)).toHaveCount(0);await drag(page,page.locator(`.ganttRow[data-task-id="${id}"] .actualDot.start`),1);const x=await page.evaluate(id=>itemById(id),id);expect(x.actual_start).toBe('2026-08-02');expect(x.actual_start_source).toBe('user');expect(x).not.toHaveProperty('actual_end')}const run=await page.evaluate(()=>itemById('run'));expect(run).toMatchObject({due:'2026-08-20',planned_duration_days:3});
});

test('ACTUAL2-GANTT-EDIT-01: 列順、計画inline編集、期限編集、矛盾0件非表示',async({page})=>{
  await show(page,[task('edit','編集',{state:'未着手',owner:'担当',due:'2026-08-20',planned_duration_days:5})]);expect((await page.locator('.ganttHeader .projectInfoTable th').allTextContents()).map(x=>x.trim())).toEqual(['完了','子','ステータス','タイトル','担当','計画日数','繰返し','期限','影響区分','概要']);await expect(page.locator('.ganttConflictSummary')).toHaveCount(0);await page.locator('.ganttRow[data-task-id="edit"] .ganttPlanned').click();let input=page.locator('.ganttRow[data-task-id="edit"] .ganttPlanned input');await input.fill('0');await input.press('Enter');expect(await page.evaluate(()=>itemById('edit').planned_duration_days)).toBe(0);await expect(page.locator('.ganttRow[data-task-id="edit"] .ganttMilestone')).toBeVisible();await page.locator('.ganttRow[data-task-id="edit"] .ganttPlanned').click();input=page.locator('.ganttRow[data-task-id="edit"] .ganttPlanned input');await input.fill('9');await input.press('Escape');expect(await page.evaluate(()=>itemById('edit').planned_duration_days)).toBe(0);await page.locator('.ganttRow[data-task-id="edit"] .ganttDue .dueTxt').click();input=page.locator('.ganttRow[data-task-id="edit"] .ganttDueText');await input.fill('2026-08-25');await input.press('Enter');expect(await page.evaluate(()=>itemById('edit').due)).toBe('2026-08-25');
});

test('ACTUAL2-LIST-ENTER-01: Project計画日数はEnter確定してblur',async({page})=>{
  await setData(page,[task('list','リスト')]);await page.locator('#mTeam').click();const input=page.locator('#row_list .plannedDays');await input.fill('7');await input.press('Enter');expect(await page.evaluate(()=>itemById('list').planned_duration_days)).toBe(7);expect(await page.evaluate(()=>document.activeElement?.classList.contains('plannedDays'))).toBe(false);
});

test('ACTUAL2-GANTT-EDIT-02: inline親期限編集は子孫を動かさず親包含・FS・期限超過を再評価',async({page})=>{
  await show(page,[task('parent','親',{due:'2026-08-20',planned_duration_days:10}),task('child','子',{parentId:'parent',due:'2026-08-25',planned_duration_days:2}),task('A','A',{due:'2026-08-10',planned_duration_days:1}),task('B','B',{due:'2026-08-12',planned_duration_days:2,dependencies:[{task_id:'A',type:'finish_to_start'}]})]);expect(await page.evaluate(()=>parentPlanConflicts().length)).toBe(1);expect(await page.evaluate(()=>plannedScheduleConflicts().length)).toBe(0);
  await page.locator('.ganttRow[data-task-id="parent"] .ganttDue .dueTxt').click();let input=page.locator('.ganttRow[data-task-id="parent"] .ganttDueText');await input.fill('2026-08-30');await input.press('Enter');expect(await page.evaluate(()=>parentPlanConflicts().length)).toBe(0);expect(await page.evaluate(()=>itemById('child').due)).toBe('2026-08-25');
  await page.locator('.ganttRow[data-task-id="B"] .ganttPlanned').click();input=page.locator('.ganttRow[data-task-id="B"] .ganttPlanned input');await input.fill('3');await input.press('Enter');expect(await page.evaluate(()=>plannedScheduleConflicts().length)).toBe(1);expect(await page.evaluate(()=>itemById('A').due)).toBe('2026-08-10');
  await page.locator('.ganttRow[data-task-id="B"] .ganttDue .dueTxt').click();input=page.locator('.ganttRow[data-task-id="B"] .ganttDueText');await input.fill('2000-01-01');await input.press('Enter');await expect(page.locator('.ganttRow[data-task-id="B"] .ganttDue')).toHaveClass(/late/);
});
