const {test,expect}=require('playwright/test');
const {APP}=require('./helpers/app-target');
const task=(id,due,duration=1,extra={})=>({id,parentId:'',state:'未着手',impact:'',title:id,owner:'',due,planned_duration_days:duration,summary:'',repeat:'',completed:false,source:'',asana_task_id:'',history:[],dependencies:[],sortOrder:1000,...extra});
async function boot(page,items){await page.emulateMedia({reducedMotion:'no-preference'});await page.goto(APP);await page.evaluate(()=>localStorage.clear());await page.reload();await page.evaluate(xs=>{applyJsonObject({schema_version:'1.8',items:xs},'animation','animation.json',null,{remember:false,writePermissionGranted:false});clearUndoHistory('animation-test')},items)}
async function listDue(page,id,value){await page.locator(`#row_${id} .dueTxt`).click();const input=page.locator(`#row_${id} input[id^="d"]`);await input.fill(value);await input.press('Enter')}
async function ganttDue(page,id,value){await page.locator(`.ganttRow[data-task-id="${id}"] .ganttDue .dueTxt`).click();const input=page.locator(`.ganttRow[data-task-id="${id}"] .ganttDueText`);await input.fill(value);await input.press('Enter')}
async function expectAnimation(page,selector,kind){const row=page.locator(selector);await expect(row).toHaveClass(/sortMoveAnimating/);await expect(row).toHaveAttribute('data-sort-move-kind',kind);await expect.poll(()=>row.evaluate(el=>getComputedStyle(el).transform),{timeout:6000}).toBe('none');await expect(row).not.toHaveClass(/sortMoveAnimating/)}

test('SORT-ANIM-01: ToDo期限移動はFLIP・selected・follow、Undoは1段',async({page})=>{await boot(page,[task('A','2026-08-20'),task('B','2026-08-10',1,{sortOrder:2000})]);await page.locator('#mPersonal').click();await page.locator('#sDate').click();await listDue(page,'A','2026-08-05');await expectAnimation(page,'#row_A','due');await expect(page.locator('#row_A')).toHaveClass(/selectedRow/);expect(await page.evaluate(()=>({due:itemById('A').due,history:undoStack.length}))).toEqual({due:'2026-08-05',history:1});await page.keyboard.press('Control+z');expect(await page.evaluate(()=>itemById('A').due)).toBe('2026-08-20')});

test('SORT-ANIM-02: Project期限移動だけをanimationし非移動は対象外',async({page})=>{await boot(page,[task('A','2026-08-20'),task('B','2026-08-10',1,{sortOrder:2000})]);await page.locator('#mTeam').click();await ganttDue(page,'A','2026-08-05');await expectAnimation(page,'.ganttRow[data-task-id="A"]','due');await ganttDue(page,'A','2026-08-06');await expect(page.locator('.ganttRow[data-task-id="A"]')).not.toHaveClass(/sortMoveAnimating/)});

test('SORT-ANIM-03: Project Ganttはtimeline込みrow全体を動かし表示日付anchorを維持',async({page})=>{await boot(page,[task('A','2026-10-20'),task('B','2026-08-10',1,{sortOrder:2000}),task('C','2026-12-10',1,{sortOrder:3000})]);await page.locator('#mTeam').click();await page.evaluate(()=>setMode('team'));await page.evaluate(()=>setGanttTimelineScroll(160));const before=await page.evaluate(()=>rcCaptureViewport());await ganttDue(page,'A','2026-08-05');await expectAnimation(page,'.ganttRow[data-task-id="A"]','due');const after=await page.evaluate(()=>rcCaptureViewport());expect(Math.abs(after.anchorDay-before.anchorDay)).toBeLessThan(0.05);expect(after.outerLeft).toBe(before.outerLeft);await expect(page.locator('.ganttScrollDock')).toHaveCount(1)});

test('SORT-ANIM-04: 計画日数によるeffective start移動だけをanimation',async({page})=>{await boot(page,[task('A','2026-08-20',1),task('B','2026-08-15',1,{sortOrder:2000})]);await page.locator('#mTeam').click();const input=page.locator('.ganttRow[data-task-id="A"] .plannedDays');await input.fill('10');await input.press('Enter');await expectAnimation(page,'.ganttRow[data-task-id="A"]','planned');expect(await page.evaluate(()=>({duration:itemById('A').planned_duration_days,history:undoStack.length,selected:selectedTaskId}))).toEqual({duration:10,history:1,selected:'A'})});
