const {test,expect}=require('playwright/test');
const {APP}=require('./helpers/app-target');
const task=(id,extra={})=>({id,parentId:'',state:'未着手',impact:'',title:id,owner:'',due:'2026-08-20',summary:'',repeat:'',completed:false,source:'',asana_task_id:'',history:[],dependencies:[],sortOrder:1000,...extra});
async function boot(page,items,done=false){await page.goto(APP);await page.evaluate(()=>localStorage.clear());await page.reload();await page.evaluate(async({items,done})=>{await applyJsonObject({schema_version:'2.0',items},'phase6','phase6.json',null,{remember:false,writePermissionGranted:false});setMode('team');setView(done?'done':'open');clearUndoHistory('phase6')},{items,done})}
async function openAdd(page,id,direction){await page.locator(`.ganttRow[data-task-id="${id}"] .relationTrigger`).evaluate(el=>el.click());await page.getByRole('button',{name:direction==='predecessor'?'＋ 前工程を追加':'＋ 後工程を追加'}).click();await expect(page.locator('.relationForm')).toBeVisible()}
const title=(page,id)=>page.locator(`.ganttRow[data-task-id="${id}"] .ganttTaskTitle`);
const state=page=>page.evaluate(()=>({open:relationOpenId,direction:relationFormDirection,candidate:relationSelectedTaskId,selected:selectedTaskId,deps:data.items.map(x=>[x.id,x.dependencies])}));

test('P6-01/P6-02 Project行は前工程・後工程候補だけを選択する',async({page})=>{for(const direction of ['predecessor','successor']){await boot(page,[task('A'),task('B',{sortOrder:2000})]);await openAdd(page,'A',direction);const selectedBefore=await page.evaluate(()=>selectedTaskId);await title(page,'B').click();expect(await state(page)).toEqual({open:'A',direction,candidate:'B',selected:selectedBefore,deps:[['A',[]],['B',[]]]});await expect(page.locator('#relSelected')).toContainText('選択: B');await expect(page.locator('.ganttRow[data-task-id="B"]')).toHaveClass(/dependencyCandidateRow/);await expect(page.locator('#relationPopup')).toBeVisible()}});

test('P6-03/P6-10 追加時だけ正しい向きで確定しUndo/Redoできる',async({page})=>{for(const direction of ['predecessor','successor']){await boot(page,[task('A'),task('B',{sortOrder:2000})]);await openAdd(page,'A',direction);await title(page,'B').click();expect(await page.evaluate(()=>undoStack.length)).toBe(0);await page.locator('.relationForm .pri').click();expect(await page.evaluate(()=>({A:itemById('A').dependencies,B:itemById('B').dependencies}))).toEqual(direction==='predecessor'?{A:[{task_id:'B',type:'finish_to_start'}],B:[]}:{A:[],B:[{task_id:'A',type:'finish_to_start'}]});await expect(page.locator('.dependencyCandidateRow')).toHaveCount(0);await page.keyboard.press('Control+z');expect(await page.evaluate(()=>data.items.flatMap(x=>x.dependencies))).toEqual([]);await page.keyboard.press('Control+y');expect(await page.evaluate(()=>data.items.flatMap(x=>x.dependencies).length)).toBe(1)}});

test('P6-04 候補BからCへ変更しCだけを追加',async({page})=>{await boot(page,[task('A'),task('B',{sortOrder:2000}),task('C',{sortOrder:3000})]);await openAdd(page,'A','predecessor');await title(page,'B').click();await title(page,'C').click();await expect(page.locator('.ganttRow[data-task-id="B"]')).not.toHaveClass(/dependencyCandidateRow/);await expect(page.locator('.ganttRow[data-task-id="C"]')).toHaveClass(/dependencyCandidateRow/);expect(await page.evaluate(()=>undoStack.length)).toBe(0);await page.locator('.relationForm .pri').click();expect(await page.evaluate(()=>itemById('A').dependencies)).toEqual([{task_id:'C',type:'finish_to_start'}])});

test('P6-05 popup検索とProject行の候補表示が同期',async({page})=>{await boot(page,[task('A'),task('B',{title:'検索B',sortOrder:2000}),task('C',{title:'検索C',sortOrder:3000})]);await openAdd(page,'A','predecessor');await page.locator('#relSearch').fill('検索B');await page.locator('.relationCandidate').click();await expect(page.locator('.ganttRow[data-task-id="B"]')).toHaveClass(/dependencyCandidateRow/);await page.locator('#relSearch').fill('');await title(page,'C').click();await expect(page.locator('#relSelected')).toContainText('検索C');await expect(page.locator('.relationCandidate.selected')).toContainText('検索C')});

test('P6-06/P6-07/P6-08 self・Cancel・closeはdata/historyを変更せず一時状態をclear',async({page})=>{await boot(page,[task('A'),task('B',{sortOrder:2000})]);await openAdd(page,'A','predecessor');await title(page,'A').click();expect((await state(page)).candidate).toBe('');await expect(page.locator('#relationPopup')).toBeVisible();await title(page,'B').click();await page.getByRole('button',{name:'キャンセル'}).click();expect(await page.evaluate(()=>({open:relationOpenId,direction:relationFormDirection,candidate:relationSelectedTaskId,deps:itemById('A').dependencies,undo:undoStack.length}))).toEqual({open:'',direction:'',candidate:'',deps:[],undo:0});await expect(page.locator('#relationPopup')).toBeHidden();await expect(page.locator('.dependencyCandidateRow')).toHaveCount(0);await openAdd(page,'A','predecessor');await title(page,'B').click();await page.evaluate(()=>closeRelationPopup());expect(await page.evaluate(()=>({open:relationOpenId,direction:relationFormDirection,candidate:relationSelectedTaskId,undo:undoStack.length}))).toEqual({open:'',direction:'',candidate:'',undo:0});await expect(page.locator('.dependencyCandidateRow')).toHaveCount(0)});

test('P6-09 row経路でもduplicate・cycle・recurrenceの既存検証を使用',async({page})=>{await boot(page,[task('A',{dependencies:[{task_id:'B',type:'finish_to_start'}]}),task('B',{sortOrder:2000})]);await openAdd(page,'A','predecessor');await title(page,'B').click();await page.locator('.relationForm .pri').click();await expect(page.locator('#toast')).toContainText('すでに登録');expect(await page.evaluate(()=>itemById('A').dependencies.length)).toBe(1);await boot(page,[task('A',{dependencies:[{task_id:'B',type:'finish_to_start'}]}),task('B',{sortOrder:2000})]);await openAdd(page,'B','predecessor');await title(page,'A').click();page.once('dialog',d=>d.accept());await page.locator('.relationForm .pri').click();expect(await page.evaluate(()=>itemById('B').dependencies)).toEqual([]);await boot(page,[task('A'),task('R',{repeat:'毎日',recurrence_rule:{type:'daily'},sortOrder:2000})]);await openAdd(page,'A','predecessor');await title(page,'R').click();await page.locator('.relationForm .pri').click();await expect(page.locator('#toast')).toContainText('繰返しタスク');expect(await page.evaluate(()=>itemById('A').dependencies)).toEqual([])});

test('P6-11 縦横scroll後も候補mode・popup・選択が維持',async({page})=>{const items=Array.from({length:45},(_,i)=>task('T'+i,{title:'長い候補 '+i,due:'2028-12-31',planned_duration_days:900,sortOrder:(i+1)*1000}));await boot(page,items);await openAdd(page,'T0','successor');await page.locator('.ganttRow[data-task-id="T40"]').scrollIntoViewIfNeeded();await page.evaluate(()=>{document.getElementById('ganttView').scrollLeft=120;setGanttTimelineScroll(240)});await title(page,'T40').click();expect(await page.evaluate(()=>({open:relationOpenId,direction:relationFormDirection,candidate:relationSelectedTaskId,timeline:ganttTimelineScrollLeft}))).toEqual({open:'T0',direction:'successor',candidate:'T40',timeline:240});await expect(page.locator('#relationPopup')).toBeVisible()});

test('P6-12 explicit Due/controlとDone checkboxは候補選択に誤作動しない',async({page})=>{await boot(page,[task('A'),task('B',{sortOrder:2000})]);await openAdd(page,'A','predecessor');await page.locator('.ganttRow[data-task-id="B"] .ganttDue').click();expect(await page.evaluate(()=>relationSelectedTaskId)).toBe('');await expect(page.locator('.ganttRow[data-task-id="B"] .ganttDueText')).toBeVisible();await boot(page,[task('A',{completed:true,state:'完了'}),task('B',{completed:true,state:'完了',sortOrder:2000})],true);await openAdd(page,'A','predecessor');await page.locator('.doneBulkCheck[data-task-id="B"]').check();expect(await page.evaluate(()=>({candidate:relationSelectedTaskId,bulk:[...doneBulkSelection]}))).toEqual({candidate:'',bulk:['B']})});

test('P6-13 ToDoの依存編集案内は従来どおり',async({page})=>{await boot(page,[task('A'),task('B',{dependencies:[{task_id:'A',type:'finish_to_start'}],sortOrder:2000})]);await page.locator('#mPersonal').click();await page.locator('#row_B .relationTrigger').click();await expect(page.locator('.todoProjectGuide')).toContainText('依存関係の設定・変更はProjectで行います');await expect(page.getByRole('button',{name:'＋ 前工程を追加'})).toHaveCount(0);expect(await page.evaluate(()=>mode)).toBe('personal')});
