const {test,expect}=require('playwright/test');
test.setTimeout(15000);
const {APP}=require('./helpers/app-target');
const task=(id,title=id,extra={})=>({id,parentId:'',state:'',impact:'',title,owner:'',due:'',summary:'',repeat:'',completed:false,source:'',asana_task_id:'',history:[],dependencies:[],sortOrder:1000,...extra});
async function boot(page,items){await page.goto(APP);await page.evaluate(()=>localStorage.clear());await page.reload();await page.evaluate(items=>applyJsonObject({schema_version:'1.8',items},'test','ux.json',null,{remember:false,writePermissionGranted:false}),items)}
async function gantt(page){await page.evaluate(()=>setMode('team'));await expect(page.locator('#ganttView')).toBeVisible()}

test('PARENT-TITLE-01: direct childを持つtaskのタイトルだけList/Ganttで太字',async({page})=>{
  await boot(page,[task('P','Parent'),task('C','Child',{parentId:'P'}),task('G','Grandchild',{parentId:'C'})]);await page.evaluate(()=>setMode('personal'));for(const id of ['P','C'])await expect(page.locator(`#row_${id} .titleText`)).toHaveClass(/parentTaskTitle/);await expect(page.locator('#row_G .titleText')).not.toHaveClass(/parentTaskTitle/);await gantt(page);for(const id of ['P','C'])await expect(page.locator(`.ganttRow[data-task-id="${id}"] .ganttTaskTitle`)).toHaveCSS('font-weight','700');await expect(page.locator('.ganttRow[data-task-id="G"] .ganttTaskTitle')).toHaveCSS('font-weight','400');expect(await page.locator('.ganttRow[data-task-id="P"] .ganttOwner').evaluate(el=>getComputedStyle(el).fontWeight)).toBe('400');
});

test('FAVICON-01: single-file SVG faviconをheadに保持',async({page})=>{await page.goto(APP);const icon=page.locator('head link[rel="icon"][type="image/svg+xml"]');await expect(icon).toHaveCount(1);await expect(icon).toHaveAttribute('href',/^data:image\/svg\+xml,/)});

test('TODO-DATE-FOLLOW-02: Insertドラフトの期限確定後も再配置・選択・attention・子Insertを維持',async({page})=>{
  await boot(page,[task('base','Base',{due:'2026-08-30'}),task('late','Late',{due:'2026-09-01',sortOrder:2000})]);await page.evaluate(()=>setMode('personal'));await page.evaluate(()=>setSortMode('date'));await page.evaluate(()=>selectTask('base'));await page.keyboard.press('Enter');const id=await page.evaluate(()=>draftTaskId);await page.locator(`#row_${id} .titleText`).fill('Early');await page.locator(`#row_${id} .titleText`).press('Enter');await page.locator(`#row_${id} input[id^="d"]`).fill('2026-08-01');await page.locator(`#row_${id} input[id^="d"]`).press('Enter');await expect(page.locator(`#row_${id}`)).toHaveClass(/selectedRow/);await expect(page.locator(`#row_${id}`)).toHaveClass(/sortAttention/);await page.keyboard.press('Insert');expect(await page.evaluate(id=>itemById(draftTaskId)?.parentId,id)).toBe(id);
});

test('GANTT-FRAME-02: selected/search/sortは行全体の明確な枠で階層背景より優先',async({page})=>{
  await boot(page,[task('P','Parent',{due:'2026-08-20',planned_duration_days:2}),task('C','Child',{parentId:'P',due:'2026-08-18',planned_duration_days:1})]);await gantt(page);await page.locator('.ganttRow[data-task-id="C"] .ganttTaskName').click();const row=page.locator('.ganttRow[data-task-id="C"]');await expect(row).toHaveClass(/ganttSelected/);expect(await row.evaluate(e=>getComputedStyle(e,'::after').boxShadow)).toContain('rgb(68, 114, 196)');await page.locator('#taskSearchBtn').click();await page.locator('#taskSearchInput').fill('Child');await page.locator('.taskSearchResult').click();await expect(row).toHaveClass(/searchAttention/);expect(await row.evaluate(e=>getComputedStyle(e,'::after').boxShadow)).toContain('rgb(208, 164, 54)');
});

test('GANTT-INDENT-02: Ganttだけ階層indentを半減',async({page})=>{
  await boot(page,[task('P'),task('C','C',{parentId:'P'}),task('G','G',{parentId:'C'})]);await page.evaluate(()=>setMode('personal'));expect(await page.locator('#row_G .indent').evaluate(e=>parseInt(e.style.width,10))).toBe(22);await page.evaluate(()=>setMode('team'));expect(await page.locator('#row_G .indent').evaluate(e=>parseInt(e.style.width,10))).toBe(44);await page.evaluate(()=>setMode('team'));expect(await page.locator('.ganttRow[data-task-id="G"] .indent').evaluate(e=>parseInt(e.style.width,10))).toBe(44);
});

test('SHORTCUT-ALT-S-01: 全viewで検索focus、editor・IME中は抑制しAlt+Gを維持',async({page})=>{
  await boot(page,[task('A','Alpha')]);for(const setup of [async()=>page.evaluate(()=>setMode('personal')),async()=>{await page.evaluate(()=>setMode('team'))},async()=>{await page.evaluate(()=>setMode('team'))}]){await setup();await page.keyboard.press('Alt+s');await expect(page.locator('#taskSearchInput')).toBeFocused();await page.locator('#taskSearchPopup button').filter({hasText:'閉じる'}).click()}await page.evaluate(()=>setMode('team'));await page.locator('#b_title').focus();await page.keyboard.press('Alt+s');await expect(page.locator('#taskSearchPopup')).toBeHidden();await page.locator('#b_title').evaluate(el=>el.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true,data:'あ'})));await page.keyboard.press('Alt+s');await expect(page.locator('#taskSearchPopup')).toBeHidden();await page.locator('#b_title').evaluate(el=>el.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true,data:'あ'})));await page.locator('body').click({position:{x:5,y:5}});await page.keyboard.press('Alt+g');await expect(page.locator('#ganttView')).toBeVisible();
});

test('GANTT-DUE-ONLY-01: due-only markerは表示専用で正式plan・保存値・親summaryへ混入しない',async({page})=>{
  await boot(page,[task('P','Parent'),task('D','Due only',{parentId:'P',due:'2026-12-20'}),task('N','None',{sortOrder:3000}),task('O','Official',{due:'2026-12-22',planned_duration_days:2,sortOrder:4000}),task('M','Milestone',{due:'2026-12-24',planned_duration_days:0,sortOrder:5000})]);await gantt(page);await expect(page.locator('.ganttRow[data-task-id="D"] .ganttDueOnlyMarker')).toHaveCount(1);await expect(page.locator('.ganttRow[data-task-id="N"] .ganttDueOnlyMarker')).toHaveCount(0);await expect(page.locator('.ganttRow[data-task-id="O"] .ganttDueOnlyMarker')).toHaveCount(0);await expect(page.locator('.ganttRow[data-task-id="M"] .ganttMilestone')).toHaveCount(1);await expect(page.locator('.ganttRow[data-task-id="P"] .ganttBar.summary')).toHaveCount(0);const saved=await page.evaluate(()=>persistableData().items.find(x=>x.id==='D'));expect(saved).not.toHaveProperty('planned_duration_days');expect(saved).not.toHaveProperty('planned_start');expect(saved).not.toHaveProperty('sort_start');
});

test('GANTT-DUE-ONLY-SEARCH-01: 検索はplan優先・なければ期限markerへ横追従しtooltipはMeiryo',async({page})=>{
  await boot(page,[task('D','Far due only',{due:'2027-12-20'}),task('N','No schedule',{sortOrder:2000})]);await gantt(page);await page.evaluate(()=>setGanttTimelineScroll(0));await page.locator('#taskSearchBtn').click();await page.locator('#taskSearchInput').fill('Far due');await page.locator('.taskSearchResult').click();await page.waitForTimeout(600);expect(await page.evaluate(()=>ganttTimelineScrollLeft)).toBeGreaterThan(0);const marker=page.locator('.ganttDueOnlyMarker');await marker.hover();await expect(page.locator('#ganttCustomTip')).toContainText('計画日数未設定');expect(await page.locator('#ganttCustomTip').evaluate(e=>getComputedStyle(e).fontFamily)).toMatch(/Meiryo/);await page.waitForTimeout(300);const before=await page.evaluate(()=>rcCaptureViewport().anchorDay);await page.locator('#taskSearchInput').fill('No schedule');await page.locator('.taskSearchResult').click();await page.waitForTimeout(300);const after=await page.evaluate(()=>rcCaptureViewport().anchorDay);expect(Math.abs(after-before)).toBeLessThanOrEqual(5);
});

test('TODO-TREE-FOLLOW-03: 期限編集のtree sort後に選択・赤attention・Insert親を維持',async({page})=>{
  await boot(page,[task('early','Early',{due:'2026-08-10'}),task('late','Late',{due:'2026-08-30',sortOrder:2000})]);await page.evaluate(()=>setMode('personal'));await page.evaluate(()=>setSortMode('tree'));await page.locator('#row_late .dueTxt').click();const input=page.locator('#row_late input[id^="d"]');await input.fill('2026-08-01');await input.press('Enter');const row=page.locator('#row_late');await expect(row).toHaveClass(/selectedRow/);await expect(row).toHaveClass(/sortAttention/);expect(await page.locator('#body tr:not(.blank)').first().getAttribute('id')).toBe('row_late');await page.keyboard.press('Insert');expect(await page.evaluate(()=>itemById(draftTaskId)?.parentId)).toBe('late');
});

test('SHORTCUT-ALT-S-02: Alt+Sは全viewでopen/focusとcloseをtoggle',async({page})=>{
  await boot(page,[task('A')]);for(const setup of [async()=>page.evaluate(()=>setMode('personal')),async()=>{await page.evaluate(()=>setMode('team'))},async()=>{await page.evaluate(()=>setMode('team'))}]){await setup();await page.keyboard.press('Alt+s');await expect(page.locator('#taskSearchInput')).toBeFocused();await page.keyboard.press('Alt+s');await expect(page.locator('#taskSearchPopup')).toBeHidden()}
});

test('GANTT-FRAME-03: 可視row矩形のpseudo枠でsearch/sortがselectedより優先',async({page})=>{
  await boot(page,[task('A','Alpha',{due:'2026-08-20',planned_duration_days:2})]);await gantt(page);const row=page.locator('.ganttRow[data-task-id="A"]');await row.locator('.ganttTaskName').click();let style=await row.evaluate(e=>({row:e.getBoundingClientRect(),after:getComputedStyle(e,'::after').boxShadow}));expect(style.after).toContain('rgb(68, 114, 196)');expect(style.row.width).toBeLessThanOrEqual(await page.locator('#ganttView').evaluate(e=>e.scrollWidth+1));await page.evaluate(()=>{sortAttentionTaskId='A';render()});style=await row.evaluate(e=>getComputedStyle(e,'::after').boxShadow);expect(style).toContain('rgb(207, 89, 101)');await page.locator('#taskSearchBtn').click();expect(await row.evaluate(e=>getComputedStyle(e,'::after').boxShadow)).toContain('rgb(68, 114, 196)');
});

test('GANTT-DUE-FORMAT-02: Gantt期限列は共通dueLabと一致',async({page})=>{
  await boot(page,[]);const dates=await page.evaluate(()=>({today:ymd(),tomorrow:addDays(ymd(),1),near:addDays(ymd(),3),other:`${Number(ymd().slice(0,4))+1}-01-15`}));await page.evaluate(items=>applyJsonObject({schema_version:'1.8',items},'test','dates.json',null,{remember:false,writePermissionGranted:false}),Object.entries(dates).map(([id,due],i)=>task(id,id,{due,sortOrder:(i+1)*1000})));await gantt(page);for(const [id]of Object.entries(dates)){const expected=await page.evaluate(id=>dueLab(itemById(id).due),id);await expect(page.locator(`.ganttRow[data-task-id="${id}"] .ganttDue .dueTxt`)).toHaveText(expected)}
});

test('GANTT-DUE-MARKER-DRAG-02: marker dragはdueだけを日単位変更しsort追従、Escは取消',async({page})=>{
  await boot(page,[task('A','Later',{due:'2026-08-20'}),task('B','Earlier',{due:'2026-08-10',sortOrder:2000})]);await gantt(page);const marker=page.locator('.ganttRow[data-task-id="A"] .ganttDueOnlyMarker');const size=await marker.evaluate(e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return{w:r.width,h:r.height,color:s.borderColor}});expect(size.w).toBeLessThanOrEqual(6);expect(size.h).toBeLessThanOrEqual(6);await marker.scrollIntoViewIfNeeded();const box=await marker.boundingBox();await page.mouse.move(box.x+2,box.y+2);await page.mouse.down();await page.mouse.move(box.x-12*28+2,box.y+2,{steps:6});await page.mouse.up();expect(await page.evaluate(()=>({due:itemById('A').due,planned:itemById('A').planned_duration_days,selected:selectedTaskId,attention:sortAttentionTaskId,dirty}))).toEqual({due:'2026-08-08',planned:undefined,selected:'A',attention:'A',dirty:true});await expect(page.locator('.ganttRow[data-task-id="A"]')).toHaveClass(/sortAttention/);await expect(page.locator('.ganttRow[data-task-id="A"] .ganttDue .dueTxt')).toHaveText(await page.evaluate(()=>dueLab('2026-08-08')));const moved=page.locator('.ganttRow[data-task-id="A"] .ganttDueOnlyMarker'),b2=await moved.boundingBox();await page.mouse.move(b2.x+2,b2.y+2);await page.mouse.down();await page.mouse.move(b2.x+30,b2.y+2);await page.keyboard.press('Escape');expect(await page.evaluate(()=>itemById('A').due)).toBe('2026-08-08');expect(await page.locator('.ganttRow[data-task-id="A"] .ganttMilestone')).toHaveCount(0);
});

test('TODO-TREE-BLANK-FOLLOW-04: 新規追加行でもtree sort後の選択・追従・赤attention・Insertを維持',async({page})=>{
  await boot(page,[task('A','A',{due:'2026-08-20'}),task('B','B',{due:'2026-08-30',sortOrder:2000})]);await page.evaluate(()=>setMode('personal'));await page.evaluate(()=>setSortMode('tree'));await page.locator('#b_title').fill('New first');await page.locator('#b_title').press('Enter');await page.locator('#b_due').fill('2026-08-01');await page.locator('#b_due').press('Enter');const id=await page.evaluate(()=>selectedTaskId);await expect(page.locator(`#row_${id}`)).toHaveClass(/sortAttention/);expect(await page.locator('#body tr:not(.blank)').first().getAttribute('id')).toBe('row_'+id);await page.keyboard.press('Insert');expect(await page.evaluate(()=>itemById(draftTaskId)?.parentId)).toBe(id);
});

test('GANTT-POST-SORT-04: 通常due・duration・plan dragを共通follow＋赤枠へ統一',async({page})=>{
  await boot(page,[task('A','A',{due:'2026-08-20',planned_duration_days:1}),task('B','B',{due:'2026-08-15',planned_duration_days:1,sortOrder:2000})]);await gantt(page);const red='rgb(207, 89, 101)',blue='rgb(68, 114, 196)';
  await page.locator('.ganttRow[data-task-id="A"] .ganttDue').click();let input=page.locator('.ganttRow[data-task-id="A"] .ganttDueText');await input.fill('2026-08-10');await input.press('Enter');let row=page.locator('.ganttRow[data-task-id="A"]');await expect(row).toHaveClass(/sortAttention/);expect(await row.evaluate(e=>getComputedStyle(e,'::after').boxShadow)).toContain(red);expect(await page.evaluate(()=>selectedTaskId)).toBe('A');await page.locator('#taskSearchBtn').click();expect(await row.evaluate(e=>getComputedStyle(e,'::after').boxShadow)).toContain(blue);await page.locator('#taskSearchPopup button').filter({hasText:'閉じる'}).click();
  await page.locator('.ganttRow[data-task-id="A"] .ganttDue').click();input=page.locator('.ganttRow[data-task-id="A"] .ganttDueText');await input.fill('2026-08-20');await input.press('Enter');await page.locator('#taskSearchBtn').click();await page.locator('#taskSearchPopup button').filter({hasText:'閉じる'}).click();await page.locator('.ganttRow[data-task-id="A"] .ganttPlanned').click();input=page.locator('.ganttRow[data-task-id="A"] .ganttPlanned input');await input.fill('20');await input.press('Enter');row=page.locator('.ganttRow[data-task-id="A"]');await expect(row).toHaveClass(/sortAttention/);expect(await row.evaluate(e=>getComputedStyle(e,'::after').boxShadow)).toContain(red);
  await page.locator('.ganttRow[data-task-id="B"] .ganttTaskName').click();const bar=page.locator('.ganttRow[data-task-id="B"] .ganttBar');for(let pass=0;pass<2;pass++){await bar.evaluate(el=>{const clip=el.closest('.ganttTimelineClip');setGanttTimelineScroll(Math.max(0,el.offsetLeft-clip.clientWidth/2));el.scrollIntoView({block:'nearest',inline:'center',behavior:'instant'})});await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));const box=await bar.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x-8*28+box.width/2,box.y+box.height/2,{steps:8});await page.mouse.up()}const brow=page.locator('.ganttRow[data-task-id="B"]');await expect(brow).toHaveClass(/sortAttention/);expect(await brow.evaluate(e=>getComputedStyle(e,'::after').boxShadow)).toContain(red);expect(await page.evaluate(()=>selectedTaskId)).toBe('B');
});

test('LIST-ROW-FRAME-01: ToDo/Listは外周だけを青黄赤にし内部cell境界を太くしない',async({page})=>{
  await boot(page,[task('A','A',{due:'2026-08-20'}),task('B','B',{due:'2026-08-30',sortOrder:2000})]);for(const setup of [async()=>{await page.evaluate(()=>setMode('personal'));await page.locator('#vAll').click()}]){await setup();await page.evaluate(()=>selectTask('A'));const row=page.locator('#row_A'),middle=row.locator('td').nth(2);expect(await row.locator('td').first().evaluate(e=>getComputedStyle(e,'::after').borderTopColor)).toBe('rgb(68, 114, 196)');expect(await row.locator('td').last().evaluate(e=>getComputedStyle(e,'::after').borderRightWidth)).toBe('3px');expect(await middle.evaluate(e=>Math.max(parseFloat(getComputedStyle(e).borderLeftWidth),parseFloat(getComputedStyle(e).borderRightWidth)))).toBeLessThanOrEqual(1);await page.evaluate(()=>{searchAttentionTaskId='A';sortAttentionTaskId='';render()});expect(await middle.evaluate(e=>getComputedStyle(e,'::after').borderTopColor)).toBe('rgb(208, 164, 54)');await page.evaluate(()=>{searchAttentionTaskId='';sortAttentionTaskId='A';render()});expect(await middle.evaluate(e=>getComputedStyle(e,'::after').borderTopColor)).toBe('rgb(207, 89, 101)')}
});

test('GANTT-SORT-HSCROLL-01: sort追従はplanとの前後だけ最小scrollし重なり中は維持',async({page})=>{
  await boot(page,[task('A','Long',{due:'2026-08-31',planned_duration_days:31}),task('F','Far',{due:'2026-12-31',planned_duration_days:1,sortOrder:2000})]);await gantt(page);await page.locator('#ganttView').evaluate(e=>e.style.width='620px');await page.waitForTimeout(100);const geometry=await page.evaluate(()=>{const row=document.querySelector('.ganttRow[data-task-id="A"]'),bar=row.querySelector('.ganttBar'),clip=document.querySelector('.ganttHeader .ganttTimelineClip');return{start:parseFloat(bar.style.left),end:parseFloat(bar.style.left)+parseFloat(bar.style.width),viewport:clip.clientWidth}});await page.evaluate(()=>setGanttTimelineScroll(0));await page.evaluate(()=>focusPostSortTask('A'));await page.waitForTimeout(100);const before=await page.evaluate(()=>ganttTimelineScrollLeft);expect(Math.abs(before-Math.max(0,geometry.start-10*28))).toBeLessThanOrEqual(2);const overlap=Math.max(0,geometry.start+9*28);await page.evaluate(v=>setGanttTimelineScroll(v),overlap);const actualOverlap=await page.evaluate(()=>ganttTimelineScrollLeft);await page.evaluate(()=>focusPostSortTask('A'));await page.waitForTimeout(100);expect(await page.evaluate(()=>ganttTimelineScrollLeft)).toBe(actualOverlap);await page.evaluate(v=>setGanttTimelineScroll(v),geometry.end+5*28);const actualAfter=await page.evaluate(()=>ganttTimelineScrollLeft);expect(actualAfter).toBeGreaterThan(geometry.end);await page.evaluate(()=>focusPostSortTask('A'));await page.waitForTimeout(100);const after=await page.evaluate(()=>ganttTimelineScrollLeft);expect(Math.abs(after-Math.max(0,geometry.end-10*28))).toBeLessThanOrEqual(2);
});

test('LIST-OVERDUE-Z-01: overdueピンクを残して青黄赤外周pseudoを最前面表示',async({page})=>{
  await boot(page,[task('O','Overdue',{due:'2020-01-02'})]);for(const setup of [async()=>{await page.evaluate(()=>setMode('personal'));await page.locator('#vAll').click()}]){await setup();await page.evaluate(()=>selectTask('O'));const due=page.locator('#row_O td').filter({has:page.locator('.dueTxt')});const pink=await due.evaluate(e=>getComputedStyle(e.querySelector('.late')||e).backgroundColor);expect(pink).not.toBe('rgba(0, 0, 0, 0)');expect(await due.evaluate(e=>({z:getComputedStyle(e,'::after').zIndex,color:getComputedStyle(e,'::after').borderTopColor}))).toEqual({z:'30',color:'rgb(68, 114, 196)'});await page.evaluate(()=>{searchAttentionTaskId='O';render()});expect(await page.locator('#row_O td').filter({has:page.locator('.dueTxt')}).evaluate(e=>getComputedStyle(e,'::after').borderTopColor)).toBe('rgb(208, 164, 54)');await page.evaluate(()=>{searchAttentionTaskId='';sortAttentionTaskId='O';render()});expect(await page.locator('#row_O td').filter({has:page.locator('.dueTxt')}).evaluate(e=>getComputedStyle(e,'::after').borderTopColor)).toBe('rgb(207, 89, 101)')}
});
