const {test,expect}=require('playwright/test');
const {APP}=require('./helpers/app-target');

async function boot(page,mode,view,sortCase){
  await page.setViewportSize({width:1280,height:600});await page.goto(APP);await page.evaluate(()=>localStorage.clear());await page.reload();
  await page.evaluate(({mode,view,sortCase})=>{const make=(id,due,sortOrder,parentId='')=>({id,parentId,state:'未着手',impact:'',title:id,owner:'',due,planned_duration_days:1,summary:'',repeat:'',completed:false,source:'',asana_task_id:'',history:[],dependencies:[],sortOrder});const xs=[];for(let i=0;i<80;i++)xs.push(make(`R${i}`,addDays(ymd(),i-40),(i+1)*1000));if(sortCase){xs[40].id='TARGET';xs[40].title='TARGET';xs[40].due=addDays(ymd(),35)}else{xs[40].id='PARENT';xs[40].title='PARENT';xs.splice(41,0,make('TARGET','',1000,'PARENT'))}applyJsonObject({schema_version:'2.0',items:xs},'v211-hotfix','v211-hotfix.json',null,{remember:false,writePermissionGranted:false});setMode(mode);setView(view);if(mode==='personal')setSortMode(sortCase?'date':'tree')},{mode,view,sortCase});await page.waitForTimeout(100)
}
const row=(page,mode)=>page.locator(mode==='team'?'.ganttRow[data-task-id="TARGET"]':'#row_TARGET');
async function centerAndOpen(page,mode){const target=row(page,mode);await target.evaluate(el=>el.scrollIntoView({block:'center',behavior:'auto'}));await page.waitForTimeout(150);await target.locator('.dueTxt').click();return target.locator('input[type="text"][id^="d"]')}

for(const mode of['personal','team'])for(const view of['open','all'])test(`V211-DUE-A ${mode}/${view}: descendant no-sort d1 preserves viewport without FLIP`,async({page})=>{await boot(page,mode,view,false);const selector=mode==='team'?'.ganttRow[data-task-id]':'#tbl tbody tr[id^="row_"]',beforeOrder=await page.locator(selector).evaluateAll(es=>es.map(e=>e.dataset.taskId||e.id.replace(/^row_/,''))),input=await centerAndOpen(page,mode),before=await page.evaluate(()=>({y:scrollY,list:listView.scrollTop,gantt:ganttView.scrollTop}));await page.keyboard.press('d');await page.waitForTimeout(100);await page.keyboard.press('1');await page.waitForTimeout(150);expect(await page.evaluate(()=>itemById('TARGET').due)).toBe(await page.evaluate(()=>addDays(ymd(),1)));expect(await page.locator(selector).evaluateAll(es=>es.map(e=>e.dataset.taskId||e.id.replace(/^row_/,'')))).toEqual(beforeOrder);await expect(row(page,mode)).not.toHaveClass(/sortMoveAnimating/);expect(await page.evaluate(()=>({y:scrollY,list:listView.scrollTop,gantt:ganttView.scrollTop}))).toEqual(before)});
for(const mode of['personal','team'])for(const view of['open','all'])test(`V211-DUE-B ${mode}/${view}: genuine-sort d9 starts FLIP without pre-scroll`,async({page})=>{await boot(page,mode,view,true);const input=await centerAndOpen(page,mode),before=await page.evaluate(()=>({index:displaySortIndex('TARGET'),y:scrollY,list:listView.scrollTop,gantt:ganttView.scrollTop}));await page.keyboard.press('d');await page.waitForTimeout(100);await page.keyboard.press('9');expect(await page.evaluate(()=>itemById('TARGET').due)).toBe(await page.evaluate(()=>addDays(ymd(),9)));expect(await page.evaluate(()=>displaySortIndex('TARGET'))).not.toBe(before.index);await expect(row(page,mode)).toHaveClass(/sortMoveAnimating/);expect(await page.evaluate(()=>({y:scrollY,list:listView.scrollTop,gantt:ganttView.scrollTop}))).toEqual({y:before.y,list:before.list,gantt:before.gantt})});
for(const mode of['personal','team'])test(`V211-DUE-C ${mode}: Enter and calendar comparison paths retain viewport`,async({page})=>{await boot(page,mode,'open',false);let input=await centerAndOpen(page,mode),before=await page.evaluate(()=>scrollY);await input.fill('2026/09/10');await input.press('Enter');expect(Math.abs(await page.evaluate(()=>scrollY)-before)).toBeLessThanOrEqual(2);input=await centerAndOpen(page,mode);before=await page.evaluate(()=>scrollY);await page.evaluate(()=>setDueFromCalendar(data.items.indexOf(itemById('TARGET')),'2026-09-11'));expect(Math.abs(await page.evaluate(()=>scrollY)-before)).toBeLessThanOrEqual(2);expect(await page.evaluate(()=>itemById('TARGET').due)).toBe('2026-09-11')});
